In [1]:
import pandas as pd

df_1 = pd.read_parquet("sparse/parquets/BagofWordsLemmatization.parquet")
df_2 = pd.read_parquet("sparse/parquets/BagofWordsPortersStemmer.parquet")
df_3 = pd.read_parquet("sparse/parquets/BagofWordsPorterStemmerQueriesStemmed.parquet")
df_4 = pd.read_parquet("sparse/parquets/BM25-LemmatizationNumbersReplaced.parquet")
df_5 = pd.read_parquet("sparse/parquets/BM25Lemmatization.parquet")
df_6 = pd.read_parquet("sparse/parquets/BM25LemmatizationCrossEncoder.parquet")
df_7 = pd.read_parquet("sparse/parquets/BM25LemmatizationCrossEncoderWithQueryExpansion.parquet")
df_8 = pd.read_parquet("sparse/parquets/BM25LemmatizationNumbersDeleted.parquet")
df_9 = pd.read_parquet("sparse/parquets/BM25PorterStemmer.parquet")
df_10 = pd.read_parquet("sparse/parquets/BM25PorterStemmerQueriesStemmed.parquet")
df_11 = pd.read_parquet("sparse/parquets/BM25PseudoRelevanceFeedback.parquet")
df_12 = pd.read_parquet("sparse/parquets/TF-IDFLemmatization.parquet")
df_13 = pd.read_parquet("sparse/parquets/TF-IDFPorterStemmer.parquet")
df_14 = pd.read_parquet("sparse/parquets/TF-IDFPorterStemmerQueriesStemmed.parquet")
df_15 = pd.read_parquet("dense/parquets/SentenceTransformer.parquet")
df_16 = pd.read_parquet("dense/parquets/SenTransformerMulti_qa.parquet")
df_17 = pd.read_parquet("dense/parquets/SenTransformerMinilm_l12.parquet")
df_18 = pd.read_parquet("dense/parquets/minilm_l12_reranking.parquet")
df_19 = pd.read_parquet("hybrid_search.parquet")

df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10, df_11, df_12, df_13, df_14, df_15, df_16, df_17, df_18, df_19], ignore_index=True)

In [2]:
df

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min,Unnamed: 0
0,Bag of Words - Lemmatization,10.360816,12.548836,83.333333,0.0,14.495339,16.820556,100.000000,0.0,22.063712,...,0.096886,0.432415,0.342429,1.0,0.0,0.430649,0.339678,1.0,0.0,NaN
1,Bag of Words - Porter's Stemmer,7.398910,12.611218,83.333333,0.0,10.567355,16.846272,100.000000,0.0,15.484765,...,0.068984,0.480932,0.363727,1.0,0.0,0.482569,0.361898,1.0,0.0,0.0
2,Bag of Words - Porter's Stemmer Queries Stemmed,10.287783,12.582727,83.333333,0.0,14.316609,16.524250,100.000000,0.0,21.855956,...,0.094823,0.432826,0.338533,1.0,0.0,0.429764,0.335320,1.0,0.0,NaN
3,BM25 - Lemmatization Numbers Replaced,13.627131,14.542782,83.333333,0.0,19.451965,19.650279,100.000000,0.0,27.950139,...,0.134112,0.500102,0.358471,1.0,0.0,0.501126,0.356007,1.0,0.0,NaN
4,BM25 - Lemmatization,14.593247,14.569564,83.333333,0.0,20.865220,19.584312,100.000000,0.0,29.847645,...,0.143757,0.505786,0.353880,1.0,0.0,0.506285,0.350688,1.0,0.0,NaN
5,BM25 - Lemmatization Cross Encoder,15.759954,14.439942,83.333333,0.0,20.865220,19.584312,100.000000,0.0,32.841644,...,0.153571,0.804835,0.327528,1.0,0.0,0.811885,0.291716,1.0,0.0,NaN
6,BM25 - Lemmatization Cross Encoder With Query ...,15.642264,14.461900,83.333333,0.0,20.540319,19.448146,100.000000,0.0,32.523084,...,0.152152,0.804181,0.326229,1.0,0.0,0.811250,0.289479,1.0,0.0,NaN
7,BM25 - Lemmatization Numbers Deleted,14.544665,14.487861,83.333333,0.0,20.671437,19.478079,100.000000,0.0,29.721448,...,0.141529,0.502118,0.354464,1.0,0.0,0.502874,0.351062,1.0,0.0,NaN
8,BM25 - Porter's Stemmer,9.352940,13.872295,83.333333,0.0,13.876176,19.458257,100.000000,0.0,19.044321,...,0.091605,0.541213,0.369604,1.0,0.0,0.548739,0.365356,1.0,0.0,NaN
9,BM25 - Porter's Stemmer Queries Stemmed,14.478316,14.481887,83.333333,0.0,20.702477,19.543478,100.000000,0.0,29.667590,...,0.141490,0.508070,0.349112,1.0,0.0,0.508130,0.345892,1.0,0.0,NaN
10,BM25PseudoRelevanceFeedback,16.024472,14.739417,83.333333,0.0,21.604635,20.202779,100.000000,0.0,33.067867,...,0.157476,0.799510,0.331981,1.0,0.0,0.808502,0.291541,1.0,0.0,NaN
11,TF-IDF - Lemmatization,12.413277,13.835136,83.333333,0.0,17.267444,18.049535,100.000000,0.0,25.761773,...,0.117186,0.475983,0.344134,1.0,0.0,0.475855,0.336552,1.0,0.0,NaN
12,TF-IDF - Porter's Stemmer,8.381096,13.166462,83.333333,0.0,12.009182,17.836521,100.000000,0.0,17.340720,...,0.078554,0.507657,0.362174,1.0,0.0,0.510121,0.357903,1.0,0.0,NaN
13,TF-IDF - Porter's Stemmer Queries Stemmed,12.394036,13.796899,83.333333,0.0,17.063580,18.097022,100.000000,0.0,25.720222,...,0.115298,0.477876,0.338497,1.0,0.0,0.476669,0.331437,1.0,0.0,NaN
14,Sentence Transformer,12.089882,12.455515,66.666667,0.0,15.568538,15.745450,85.714286,0.0,27.049861,...,0.111715,0.695169,0.365791,1.0,0.0,0.703160,0.310758,1.0,0.0,NaN
15,SenTransformer multi_qa,11.927286,11.864656,71.428571,0.0,15.364111,15.377768,100.000000,0.0,26.855956,...,0.111127,0.715174,0.354878,1.0,0.0,0.714065,0.300219,1.0,0.0,NaN
16,SenTransformer minilm_l12,12.984136,12.349759,83.333333,0.0,16.480406,15.229594,100.000000,0.0,28.573407,...,0.118783,0.708287,0.353963,1.0,0.0,0.709100,0.296196,1.0,0.0,NaN
17,minilm_l12_reranking,14.169270,12.872118,66.666667,0.0,17.231414,15.961054,100.000000,0.0,31.260388,...,0.134332,0.750344,0.352292,1.0,0.0,0.752008,0.307466,1.0,0.0,NaN
18,Hybrid Search,17.071468,14.247436,83.333333,0.0,23.777552,20.117251,100.000000,0.0,35.817175,...,0.170402,0.784984,0.330350,1.0,0.0,0.789487,0.288096,1.0,0.0,NaN

In [3]:
df.columns

Index(['Method', 'recall_5_mean', 'recall_5_std', 'recall_5_max',
       'recall_5_min', 'recall_10_mean', 'recall_10_std', 'recall_10_max',
       'recall_10_min', 'precision_5_mean', 'precision_5_std',
       'precision_5_max', 'precision_5_min', 'precision_10_mean',
       'precision_10_std', 'precision_10_max', 'precision_10_min',
       'f_score_5_mean', 'f_score_5_std', 'f_score_5_max', 'f_score_5_min',
       'f_score_10_mean', 'f_score_10_std', 'f_score_10_max', 'f_score_10_min',
       'MAP_5', 'MAP_10', 'NDCG_5_mean', 'NDCG_5_std', 'NDCG_5_max',
       'NDCG_5_min', 'NDCG_10_mean', 'NDCG_10_std', 'NDCG_10_max',
       'NDCG_10_min', 'Unnamed: 0'],
      dtype='str')

In [4]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [5]:
df

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,Bag of Words - Lemmatization,10.360816,12.548836,83.333333,0.0,14.495339,16.820556,100.000000,0.0,22.063712,...,0.080840,0.096886,0.432415,0.342429,1.0,0.0,0.430649,0.339678,1.0,0.0
1,Bag of Words - Porter's Stemmer,7.398910,12.611218,83.333333,0.0,10.567355,16.846272,100.000000,0.0,15.484765,...,0.056182,0.068984,0.480932,0.363727,1.0,0.0,0.482569,0.361898,1.0,0.0
2,Bag of Words - Porter's Stemmer Queries Stemmed,10.287783,12.582727,83.333333,0.0,14.316609,16.524250,100.000000,0.0,21.855956,...,0.079560,0.094823,0.432826,0.338533,1.0,0.0,0.429764,0.335320,1.0,0.0
3,BM25 - Lemmatization Numbers Replaced,13.627131,14.542782,83.333333,0.0,19.451965,19.650279,100.000000,0.0,27.950139,...,0.108940,0.134112,0.500102,0.358471,1.0,0.0,0.501126,0.356007,1.0,0.0
4,BM25 - Lemmatization,14.593247,14.569564,83.333333,0.0,20.865220,19.584312,100.000000,0.0,29.847645,...,0.116666,0.143757,0.505786,0.353880,1.0,0.0,0.506285,0.350688,1.0,0.0
5,BM25 - Lemmatization Cross Encoder,15.759954,14.439942,83.333333,0.0,20.865220,19.584312,100.000000,0.0,32.841644,...,0.122148,0.153571,0.804835,0.327528,1.0,0.0,0.811885,0.291716,1.0,0.0
6,BM25 - Lemmatization Cross Encoder With Query ...,15.642264,14.461900,83.333333,0.0,20.540319,19.448146,100.000000,0.0,32.523084,...,0.121822,0.152152,0.804181,0.326229,1.0,0.0,0.811250,0.289479,1.0,0.0
7,BM25 - Lemmatization Numbers Deleted,14.544665,14.487861,83.333333,0.0,20.671437,19.478079,100.000000,0.0,29.721448,...,0.115245,0.141529,0.502118,0.354464,1.0,0.0,0.502874,0.351062,1.0,0.0
8,BM25 - Porter's Stemmer,9.352940,13.872295,83.333333,0.0,13.876176,19.458257,100.000000,0.0,19.044321,...,0.072112,0.091605,0.541213,0.369604,1.0,0.0,0.548739,0.365356,1.0,0.0
9,BM25 - Porter's Stemmer Queries Stemmed,14.478316,14.481887,83.333333,0.0,20.702477,19.543478,100.000000,0.0,29.667590,...,0.114719,0.141490,0.508070,0.349112,1.0,0.0,0.508130,0.345892,1.0,0.0
10,BM25PseudoRelevanceFeedback,16.024472,14.739417,83.333333,0.0,21.604635,20.202779,100.000000,0.0,33.067867,...,0.123887,0.157476,0.799510,0.331981,1.0,0.0,0.808502,0.291541,1.0,0.0
11,TF-IDF - Lemmatization,12.413277,13.835136,83.333333,0.0,17.267444,18.049535,100.000000,0.0,25.761773,...,0.097513,0.117186,0.475983,0.344134,1.0,0.0,0.475855,0.336552,1.0,0.0
12,TF-IDF - Porter's Stemmer,8.381096,13.166462,83.333333,0.0,12.009182,17.836521,100.000000,0.0,17.340720,...,0.063347,0.078554,0.507657,0.362174,1.0,0.0,0.510121,0.357903,1.0,0.0
13,TF-IDF - Porter's Stemmer Queries Stemmed,12.394036,13.796899,83.333333,0.0,17.063580,18.097022,100.000000,0.0,25.720222,...,0.096138,0.115298,0.477876,0.338497,1.0,0.0,0.476669,0.331437,1.0,0.0
14,Sentence Transformer,12.089882,12.455515,66.666667,0.0,15.568538,15.745450,85.714286,0.0,27.049861,...,0.093745,0.111715,0.695169,0.365791,1.0,0.0,0.703160,0.310758,1.0,0.0
15,SenTransformer multi_qa,11.927286,11.864656,71.428571,0.0,15.364111,15.377768,100.000000,0.0,26.855956,...,0.093419,0.111127,0.715174,0.354878,1.0,0.0,0.714065,0.300219,1.0,0.0
16,SenTransformer minilm_l12,12.984136,12.349759,83.333333,0.0,16.480406,15.229594,100.000000,0.0,28.573407,...,0.099883,0.118783,0.708287,0.353963,1.0,0.0,0.709100,0.296196,1.0,0.0
17,minilm_l12_reranking,14.169270,12.872118,66.666667,0.0,17.231414,15.961054,100.000000,0.0,31.260388,...,0.114530,0.134332,0.750344,0.352292,1.0,0.0,0.752008,0.307466,1.0,0.0
18,Hybrid Search,17.071468,14.247436,83.333333,0.0,23.777552,20.117251,100.000000,0.0,35.817175,...,0.131637,0.170402,0.784984,0.330350,1.0,0.0,0.789487,0.288096,1.0,0.0

In [ ]:
method_type = []

for i in range(14):
    method_type.append("LEXICOGRAPHIC")

for i in range(4):
    method_type.append("SEMANTIC")

method_type.append("HYBRID")

In [7]:
df.insert(1, "Method Type", method_type)

In [8]:
df

,Method,Method Type,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,10.360816,12.548836,83.333333,0.0,14.495339,16.820556,100.000000,0.0,...,0.080840,0.096886,0.432415,0.342429,1.0,0.0,0.430649,0.339678,1.0,0.0
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,7.398910,12.611218,83.333333,0.0,10.567355,16.846272,100.000000,0.0,...,0.056182,0.068984,0.480932,0.363727,1.0,0.0,0.482569,0.361898,1.0,0.0
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,10.287783,12.582727,83.333333,0.0,14.316609,16.524250,100.000000,0.0,...,0.079560,0.094823,0.432826,0.338533,1.0,0.0,0.429764,0.335320,1.0,0.0
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,13.627131,14.542782,83.333333,0.0,19.451965,19.650279,100.000000,0.0,...,0.108940,0.134112,0.500102,0.358471,1.0,0.0,0.501126,0.356007,1.0,0.0
4,BM25 - Lemmatization,LEXICOGRAPHIC,14.593247,14.569564,83.333333,0.0,20.865220,19.584312,100.000000,0.0,...,0.116666,0.143757,0.505786,0.353880,1.0,0.0,0.506285,0.350688,1.0,0.0
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,15.759954,14.439942,83.333333,0.0,20.865220,19.584312,100.000000,0.0,...,0.122148,0.153571,0.804835,0.327528,1.0,0.0,0.811885,0.291716,1.0,0.0
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,15.642264,14.461900,83.333333,0.0,20.540319,19.448146,100.000000,0.0,...,0.121822,0.152152,0.804181,0.326229,1.0,0.0,0.811250,0.289479,1.0,0.0
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,14.544665,14.487861,83.333333,0.0,20.671437,19.478079,100.000000,0.0,...,0.115245,0.141529,0.502118,0.354464,1.0,0.0,0.502874,0.351062,1.0,0.0
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,9.352940,13.872295,83.333333,0.0,13.876176,19.458257,100.000000,0.0,...,0.072112,0.091605,0.541213,0.369604,1.0,0.0,0.548739,0.365356,1.0,0.0
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,14.478316,14.481887,83.333333,0.0,20.702477,19.543478,100.000000,0.0,...,0.114719,0.141490,0.508070,0.349112,1.0,0.0,0.508130,0.345892,1.0,0.0
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,16.024472,14.739417,83.333333,0.0,21.604635,20.202779,100.000000,0.0,...,0.123887,0.157476,0.799510,0.331981,1.0,0.0,0.808502,0.291541,1.0,0.0
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,12.413277,13.835136,83.333333,0.0,17.267444,18.049535,100.000000,0.0,...,0.097513,0.117186,0.475983,0.344134,1.0,0.0,0.475855,0.336552,1.0,0.0
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,8.381096,13.166462,83.333333,0.0,12.009182,17.836521,100.000000,0.0,...,0.063347,0.078554,0.507657,0.362174,1.0,0.0,0.510121,0.357903,1.0,0.0
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,12.394036,13.796899,83.333333,0.0,17.063580,18.097022,100.000000,0.0,...,0.096138,0.115298,0.477876,0.338497,1.0,0.0,0.476669,0.331437,1.0,0.0
14,Sentence Transformer,SEMANTIC,12.089882,12.455515,66.666667,0.0,15.568538,15.745450,85.714286,0.0,...,0.093745,0.111715,0.695169,0.365791,1.0,0.0,0.703160,0.310758,1.0,0.0
15,SenTransformer multi_qa,SEMANTIC,11.927286,11.864656,71.428571,0.0,15.364111,15.377768,100.000000,0.0,...,0.093419,0.111127,0.715174,0.354878,1.0,0.0,0.714065,0.300219,1.0,0.0
16,SenTransformer minilm_l12,SEMANTIC,12.984136,12.349759,83.333333,0.0,16.480406,15.229594,100.000000,0.0,...,0.099883,0.118783,0.708287,0.353963,1.0,0.0,0.709100,0.296196,1.0,0.0
17,minilm_l12_reranking,SEMANTIC,14.169270,12.872118,66.666667,0.0,17.231414,15.961054,100.000000,0.0,...,0.114530,0.134332,0.750344,0.352292,1.0,0.0,0.752008,0.307466,1.0,0.0
18,Hybrid Search,DENSE,17.071468,14.247436,83.333333,0.0,23.777552,20.117251,100.000000,0.0,...,0.131637,0.170402,0.784984,0.330350,1.0,0.0,0.789487,0.288096,1.0,0.0

In [9]:
df.loc[18, "Method Type"] = "HYBRID"

In [10]:
df

,Method,Method Type,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,10.360816,12.548836,83.333333,0.0,14.495339,16.820556,100.000000,0.0,...,0.080840,0.096886,0.432415,0.342429,1.0,0.0,0.430649,0.339678,1.0,0.0
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,7.398910,12.611218,83.333333,0.0,10.567355,16.846272,100.000000,0.0,...,0.056182,0.068984,0.480932,0.363727,1.0,0.0,0.482569,0.361898,1.0,0.0
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,10.287783,12.582727,83.333333,0.0,14.316609,16.524250,100.000000,0.0,...,0.079560,0.094823,0.432826,0.338533,1.0,0.0,0.429764,0.335320,1.0,0.0
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,13.627131,14.542782,83.333333,0.0,19.451965,19.650279,100.000000,0.0,...,0.108940,0.134112,0.500102,0.358471,1.0,0.0,0.501126,0.356007,1.0,0.0
4,BM25 - Lemmatization,LEXICOGRAPHIC,14.593247,14.569564,83.333333,0.0,20.865220,19.584312,100.000000,0.0,...,0.116666,0.143757,0.505786,0.353880,1.0,0.0,0.506285,0.350688,1.0,0.0
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,15.759954,14.439942,83.333333,0.0,20.865220,19.584312,100.000000,0.0,...,0.122148,0.153571,0.804835,0.327528,1.0,0.0,0.811885,0.291716,1.0,0.0
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,15.642264,14.461900,83.333333,0.0,20.540319,19.448146,100.000000,0.0,...,0.121822,0.152152,0.804181,0.326229,1.0,0.0,0.811250,0.289479,1.0,0.0
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,14.544665,14.487861,83.333333,0.0,20.671437,19.478079,100.000000,0.0,...,0.115245,0.141529,0.502118,0.354464,1.0,0.0,0.502874,0.351062,1.0,0.0
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,9.352940,13.872295,83.333333,0.0,13.876176,19.458257,100.000000,0.0,...,0.072112,0.091605,0.541213,0.369604,1.0,0.0,0.548739,0.365356,1.0,0.0
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,14.478316,14.481887,83.333333,0.0,20.702477,19.543478,100.000000,0.0,...,0.114719,0.141490,0.508070,0.349112,1.0,0.0,0.508130,0.345892,1.0,0.0
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,16.024472,14.739417,83.333333,0.0,21.604635,20.202779,100.000000,0.0,...,0.123887,0.157476,0.799510,0.331981,1.0,0.0,0.808502,0.291541,1.0,0.0
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,12.413277,13.835136,83.333333,0.0,17.267444,18.049535,100.000000,0.0,...,0.097513,0.117186,0.475983,0.344134,1.0,0.0,0.475855,0.336552,1.0,0.0
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,8.381096,13.166462,83.333333,0.0,12.009182,17.836521,100.000000,0.0,...,0.063347,0.078554,0.507657,0.362174,1.0,0.0,0.510121,0.357903,1.0,0.0
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,12.394036,13.796899,83.333333,0.0,17.063580,18.097022,100.000000,0.0,...,0.096138,0.115298,0.477876,0.338497,1.0,0.0,0.476669,0.331437,1.0,0.0
14,Sentence Transformer,SEMANTIC,12.089882,12.455515,66.666667,0.0,15.568538,15.745450,85.714286,0.0,...,0.093745,0.111715,0.695169,0.365791,1.0,0.0,0.703160,0.310758,1.0,0.0
15,SenTransformer multi_qa,SEMANTIC,11.927286,11.864656,71.428571,0.0,15.364111,15.377768,100.000000,0.0,...,0.093419,0.111127,0.715174,0.354878,1.0,0.0,0.714065,0.300219,1.0,0.0
16,SenTransformer minilm_l12,SEMANTIC,12.984136,12.349759,83.333333,0.0,16.480406,15.229594,100.000000,0.0,...,0.099883,0.118783,0.708287,0.353963,1.0,0.0,0.709100,0.296196,1.0,0.0
17,minilm_l12_reranking,SEMANTIC,14.169270,12.872118,66.666667,0.0,17.231414,15.961054,100.000000,0.0,...,0.114530,0.134332,0.750344,0.352292,1.0,0.0,0.752008,0.307466,1.0,0.0
18,Hybrid Search,HYBRID,17.071468,14.247436,83.333333,0.0,23.777552,20.117251,100.000000,0.0,...,0.131637,0.170402,0.784984,0.330350,1.0,0.0,0.789487,0.288096,1.0,0.0

In [11]:
df.isna().sum()

Method               0
Method Type          0
recall_5_mean        0
recall_5_std         0
recall_5_max         0
recall_5_min         0
recall_10_mean       0
recall_10_std        0
recall_10_max        0
recall_10_min        0
precision_5_mean     0
precision_5_std      0
precision_5_max      0
precision_5_min      0
precision_10_mean    0
precision_10_std     0
precision_10_max     0
precision_10_min     0
f_score_5_mean       0
f_score_5_std        0
f_score_5_max        0
f_score_5_min        0
f_score_10_mean      0
f_score_10_std       0
f_score_10_max       0
f_score_10_min       0
MAP_5                0
MAP_10               0
NDCG_5_mean          0
NDCG_5_std           0
NDCG_5_max           0
NDCG_5_min           0
NDCG_10_mean         0
NDCG_10_std          0
NDCG_10_max          0
NDCG_10_min          0
dtype: int64

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Method             19 non-null     str
 1   Method Type        19 non-null     str
 2   recall_5_mean      19 non-null     float64
 3   recall_5_std       19 non-null     float64
 4   recall_5_max       19 non-null     float64
 5   recall_5_min       19 non-null     float64
 6   recall_10_mean     19 non-null     float64
 7   recall_10_std      19 non-null     float64
 8   recall_10_max      19 non-null     float64
 9   recall_10_min      19 non-null     float64
 10  precision_5_mean   19 non-null     float64
 11  precision_5_std    19 non-null     float64
 12  precision_5_max    19 non-null     float64
 13  precision_5_min    19 non-null     float64
 14  precision_10_mean  19 non-null     float64
 15  precision_10_std   19 non-null     float64
 16  precision_10_max   19 non-null     float64
 17  precision_10_min   19 non-null     float64
 18  f_score_5_mean     19 non-null     float64
 19  f_score_5_std      19 non-null     float64
 20  f_score_5_max      19 non-null     float64
 21  f_score_5_min      19 non-null     float64
 22  f_score_10_mean    19 non-null     float64
 23  f_score_10_std     19 non-null     float64
 24  f_score_10_max     19 non-null     float64
 25  f_score_10_min     19 non-null     float64
 26  MAP_5              19 non-null     float64
 27  MAP_10             19 non-null     float64
 28  NDCG_5_mean        19 non-null     float64
 29  NDCG_5_std         19 non-null     float64
 30  NDCG_5_max         19 non-null     float64
 31  NDCG_5_min         19 non-null     float64
 32  NDCG_10_mean       19 non-null     float64
 33  NDCG_10_std        19 non-null     float64
 34  NDCG_10_max        19 non-null     float64
 35  NDCG_10_min        19 non-null     float64
dtypes: float64(34), str(2)
memory usage: 6.2 KB

In [13]:
df.to_csv("all_methods_results.csv")

In [16]:
df[["Method", "Method Type", "recall_5_mean"]].sort_values(by="recall_5_mean", ascending=True)

,Method,Method Type,recall_5_mean
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,7.398910
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,8.381096
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,9.352940
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,10.287783
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,10.360816
15,SenTransformer multi_qa,SEMANTIC,11.927286
14,Sentence Transformer,SEMANTIC,12.089882
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,12.394036
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,12.413277
16,SenTransformer minilm_l12,SEMANTIC,12.984136
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,13.627131
17,minilm_l12_reranking,SEMANTIC,14.169270
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,14.478316
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,14.544665
4,BM25 - Lemmatization,LEXICOGRAPHIC,14.593247
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,15.642264
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,15.759954
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,16.024472
18,Hybrid Search,HYBRID,17.071468

In [17]:
df[["Method", "Method Type", "precision_5_mean"]].sort_values(by="precision_5_mean", ascending=True)

,Method,Method Type,precision_5_mean
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,15.484765
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,17.340720
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,19.044321
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,21.855956
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,22.063712
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,25.720222
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,25.761773
15,SenTransformer multi_qa,SEMANTIC,26.855956
14,Sentence Transformer,SEMANTIC,27.049861
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,27.950139
16,SenTransformer minilm_l12,SEMANTIC,28.573407
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,29.667590
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,29.721448
4,BM25 - Lemmatization,LEXICOGRAPHIC,29.847645
17,minilm_l12_reranking,SEMANTIC,31.260388
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,32.523084
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,32.841644
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,33.067867
18,Hybrid Search,HYBRID,35.817175

In [18]:
df[["Method", "Method Type", "f_score_5_mean"]].sort_values(by="f_score_5_mean", ascending=True)

,Method,Method Type,f_score_5_mean
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,9.252260
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,10.480288
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,11.660255
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,12.915315
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,13.010022
15,SenTransformer multi_qa,SEMANTIC,15.139652
14,Sentence Transformer,SEMANTIC,15.339492
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,15.507866
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,15.534353
16,SenTransformer minilm_l12,SEMANTIC,16.445309
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,17.023097
17,minilm_l12_reranking,SEMANTIC,17.951978
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,18.079611
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,18.163435
4,BM25 - Lemmatization,LEXICOGRAPHIC,18.216890
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,19.776504
18,Hybrid Search,HYBRID,21.422804
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,22.905529
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,23.076832

In [19]:
df[["Method", "Method Type", "recall_10_mean"]].sort_values(by="recall_10_mean", ascending=True)

,Method,Method Type,recall_10_mean
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,10.567355
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,12.009182
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,13.876176
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,14.316609
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,14.495339
15,SenTransformer multi_qa,SEMANTIC,15.364111
14,Sentence Transformer,SEMANTIC,15.568538
16,SenTransformer minilm_l12,SEMANTIC,16.480406
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,17.063580
17,minilm_l12_reranking,SEMANTIC,17.231414
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,17.267444
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,19.451965
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,20.540319
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,20.671437
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,20.702477
4,BM25 - Lemmatization,LEXICOGRAPHIC,20.865220
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,20.865220
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,21.604635
18,Hybrid Search,HYBRID,23.777552

In [20]:
df[["Method", "Method Type", "precision_10_mean"]].sort_values(by="precision_10_mean", ascending=True)

,Method,Method Type,precision_10_mean
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,11.655125
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,13.026316
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,14.743767
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,15.948753
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,16.121884
15,SenTransformer multi_qa,SEMANTIC,18.448753
14,Sentence Transformer,SEMANTIC,18.614958
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,18.628809
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,18.891967
16,SenTransformer minilm_l12,SEMANTIC,19.362881
17,minilm_l12_reranking,SEMANTIC,20.519391
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,20.865651
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,22.146814
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,22.207521
4,BM25 - Lemmatization,LEXICOGRAPHIC,22.368421
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,22.640153
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,22.903311
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,23.131733
18,Hybrid Search,HYBRID,25.934903

In [21]:
df[["Method", "Method Type", "f_score_10_mean"]].sort_values(by="f_score_10_mean", ascending=True)

,Method,Method Type,f_score_10_mean
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,9.913249
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,11.261641
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,12.939341
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,13.458986
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,13.615675
15,SenTransformer multi_qa,SEMANTIC,14.739899
14,Sentence Transformer,SEMANTIC,14.959802
16,SenTransformer minilm_l12,SEMANTIC,15.786780
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,16.012440
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,16.214134
17,minilm_l12_reranking,SEMANTIC,16.588678
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,18.193116
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,19.336915
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,19.340120
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,19.385480
4,BM25 - Lemmatization,LEXICOGRAPHIC,19.510940
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,19.673399
18,Hybrid Search,HYBRID,22.321040
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,22.355875

In [23]:
df[["Method", "Method Type", "MAP_5"]].sort_values(by="MAP_5", ascending=True)

                                               Method    Method Type     MAP_5
1                     Bag of Words - Porter's Stemmer  LEXICOGRAPHIC  0.056182
12                          TF-IDF - Porter's Stemmer  LEXICOGRAPHIC  0.063347
8                             BM25 - Porter's Stemmer  LEXICOGRAPHIC  0.072112
2     Bag of Words - Porter's Stemmer Queries Stemmed  LEXICOGRAPHIC  0.079560
0                        Bag of Words - Lemmatization  LEXICOGRAPHIC  0.080840
15                            SenTransformer multi_qa       SEMANTIC  0.093419
14                               Sentence Transformer       SEMANTIC  0.093745
13          TF-IDF - Porter's Stemmer Queries Stemmed  LEXICOGRAPHIC  0.096138
11                             TF-IDF - Lemmatization  LEXICOGRAPHIC  0.097513
16                          SenTransformer minilm_l12       SEMANTIC  0.099883
3               BM25 - Lemmatization Numbers Replaced  LEXICOGRAPHIC  0.108940
17                               minilm_l12_reranking       SEMANTIC  0.114530
9             BM25 - Porter's Stemmer Queries Stemmed  LEXICOGRAPHIC  0.114719
7                BM25 - Lemmatization Numbers Deleted  LEXICOGRAPHIC  0.115245
4                                BM25 - Lemmatization  LEXICOGRAPHIC  0.116666
6   BM25 - Lemmatization Cross Encoder With Query ...  LEXICOGRAPHIC  0.121822
5                  BM25 - Lemmatization Cross Encoder  LEXICOGRAPHIC  0.122148
10                        BM25PseudoRelevanceFeedback  LEXICOGRAPHIC  0.123887
18                                      Hybrid Search         HYBRID  0.131637

In [24]:
df[["Method", "Method Type", "MAP_10"]].sort_values(by="MAP_10", ascending=True)

                                               Method    Method Type    MAP_10
1                     Bag of Words - Porter's Stemmer  LEXICOGRAPHIC  0.068984
12                          TF-IDF - Porter's Stemmer  LEXICOGRAPHIC  0.078554
8                             BM25 - Porter's Stemmer  LEXICOGRAPHIC  0.091605
2     Bag of Words - Porter's Stemmer Queries Stemmed  LEXICOGRAPHIC  0.094823
0                        Bag of Words - Lemmatization  LEXICOGRAPHIC  0.096886
15                            SenTransformer multi_qa       SEMANTIC  0.111127
14                               Sentence Transformer       SEMANTIC  0.111715
13          TF-IDF - Porter's Stemmer Queries Stemmed  LEXICOGRAPHIC  0.115298
11                             TF-IDF - Lemmatization  LEXICOGRAPHIC  0.117186
16                          SenTransformer minilm_l12       SEMANTIC  0.118783
3               BM25 - Lemmatization Numbers Replaced  LEXICOGRAPHIC  0.134112
17                               minilm_l12_reranking       SEMANTIC  0.134332
9             BM25 - Porter's Stemmer Queries Stemmed  LEXICOGRAPHIC  0.141490
7                BM25 - Lemmatization Numbers Deleted  LEXICOGRAPHIC  0.141529
4                                BM25 - Lemmatization  LEXICOGRAPHIC  0.143757
6   BM25 - Lemmatization Cross Encoder With Query ...  LEXICOGRAPHIC  0.152152
5                  BM25 - Lemmatization Cross Encoder  LEXICOGRAPHIC  0.153571
10                        BM25PseudoRelevanceFeedback  LEXICOGRAPHIC  0.157476
18                                      Hybrid Search         HYBRID  0.170402

In [26]:
df[["Method", "Method Type", "NDCG_5_mean"]].sort_values(by="NDCG_5_mean", ascending=True)

,Method,Method Type,NDCG_5_mean
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,0.432415
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,0.432826
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,0.475983
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,0.477876
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,0.480932
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,0.500102
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,0.502118
4,BM25 - Lemmatization,LEXICOGRAPHIC,0.505786
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,0.507657
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,0.508070
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,0.541213
14,Sentence Transformer,SEMANTIC,0.695169
16,SenTransformer minilm_l12,SEMANTIC,0.708287
15,SenTransformer multi_qa,SEMANTIC,0.715174
17,minilm_l12_reranking,SEMANTIC,0.750344
18,Hybrid Search,HYBRID,0.784984
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,0.799510
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,0.804181
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,0.804835

In [27]:
df[["Method", "Method Type", "NDCG_10_mean"]].sort_values(by="NDCG_10_mean", ascending=True)

,Method,Method Type,NDCG_10_mean
2,Bag of Words - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,0.429764
0,Bag of Words - Lemmatization,LEXICOGRAPHIC,0.430649
11,TF-IDF - Lemmatization,LEXICOGRAPHIC,0.475855
13,TF-IDF - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,0.476669
1,Bag of Words - Porter's Stemmer,LEXICOGRAPHIC,0.482569
3,BM25 - Lemmatization Numbers Replaced,LEXICOGRAPHIC,0.501126
7,BM25 - Lemmatization Numbers Deleted,LEXICOGRAPHIC,0.502874
4,BM25 - Lemmatization,LEXICOGRAPHIC,0.506285
9,BM25 - Porter's Stemmer Queries Stemmed,LEXICOGRAPHIC,0.508130
12,TF-IDF - Porter's Stemmer,LEXICOGRAPHIC,0.510121
8,BM25 - Porter's Stemmer,LEXICOGRAPHIC,0.548739
14,Sentence Transformer,SEMANTIC,0.703160
16,SenTransformer minilm_l12,SEMANTIC,0.709100
15,SenTransformer multi_qa,SEMANTIC,0.714065
17,minilm_l12_reranking,SEMANTIC,0.752008
18,Hybrid Search,HYBRID,0.789487
10,BM25PseudoRelevanceFeedback,LEXICOGRAPHIC,0.808502
6,BM25 - Lemmatization Cross Encoder With Query ...,LEXICOGRAPHIC,0.811250
5,BM25 - Lemmatization Cross Encoder,LEXICOGRAPHIC,0.811885