In [1]:
import ir_datasets
from nltk.stem import WordNetLemmatizer
import nltk
from helper import create_tokenized_word_list

dataset = ir_datasets.load("wikir/en1k/training")
tokenized = create_tokenized_word_list(dataset)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
nltk.download("punkt_tab")
nltk.download("wordnet")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/tahas44/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
lemmatized_tokenized_docs = []
lematizer = WordNetLemmatizer()

for query_list in tokenized:
    lemmatized_words = [lematizer.lemmatize(word) for word in query_list]
    lemmatized_tokenized_docs.append(lemmatized_words)

print("Docs lemmatized")

Docs lemmatized

In [4]:
lemmatized_tokenized_docs

[['used',
  'landing',
  'craft',
  'world',
  'war',
  'ii',
  'used',
  'today',
  'private',
  'boat',
  'training',
  'facility',
  '6',
  '71',
  'inline',
  'six',
  'cylinder',
  'diesel',
  'engine',
  '71',
  'refers',
  'displacement',
  'cubic',
  'inch',
  'cylinder',
  'firing',
  'order',
  'engine',
  '1',
  '5',
  '3',
  '6',
  '2',
  '4',
  'engine',
  'compression',
  'ratio',
  '18',
  '7',
  '1',
  '4',
  '250',
  'inch',
  'bore',
  '5',
  '00',
  'inch',
  'stroke',
  'engine',
  'weighs',
  '54',
  'inch',
  'long',
  '29',
  'inch',
  'wide',
  '41',
  'inch',
  'tall',
  '2',
  '100',
  'revolution',
  'per',
  'minute',
  'engine',
  'capable',
  'producing',
  '230',
  'horse',
  'power',
  '172',
  'kilowatt',
  'v',
  'type',
  'version',
  '71',
  'series',
  'developed',
  '1957',
  '6',
  '71',
  'two',
  'stroke',
  'engine',
  'engine',
  'naturally',
  'aspirate',
  'air',
  'provided',
  'via',
  'root',
  'type',
  'blower',
  'however',
  '6',
  '71t',
  'model',
  'turbocharger',
  'supercharger',
  'utilized',
  'fuel',
  'provided',
  'unit',
  'injector',
  'one',
  'per',
  'cylinder',
  'amount',
  'fuel',
  'injected',
  'engine',
  'controlled',
  'engine',
  'governor',
  'engine',
  'cooling',
  'via',
  'liquid',
  'water',
  'jacket',
  'boat',
  'cool',
  'external',
  'water',
  'pumped',
  'engine'],
 ['rejecting',
  'offer',
  'cambridge',
  'university',
  'moved',
  'london',
  '1954',
  'working',
  'mayfair',
  'advertising',
  'agency',
  'moonlighting',
  'hat',
  'check',
  'girl',
  'night',
  'club',
  'le',
  'club',
  'contemporain',
  'working',
  'royal',
  'college',
  'art',
  'met',
  'painter',
  'frank',
  'bowling',
  'still',
  'student',
  'married',
  '1960',
  'one',
  'son',
  'kitchen',
  'one',
  'woman',
  'interviewed',
  'nell',
  'dunn',
  'talking',
  'woman',
  '1965',
  'divorcing',
  'bowling',
  'late',
  'sixty',
  'kitchen',
  'went',
  'live',
  'later',
  'marry',
  'writer',
  'dulan',
  'barber',
  'continuing',
  'write',
  'novel',
  'also',
  'began',
  'writing',
  'non',
  'fiction',
  'biography',
  'patrick',
  'geddes',
  'gerard',
  'manley',
  'hopkins',
  'later',
  'life',
  'bought',
  'house',
  'barnwell',
  'northamptonshire',
  'became',
  'subject',
  'book',
  'name',
  'died',
  '23',
  'november',
  '2005',
  'novelist',
  'bessie',
  'head',
  'close',
  'friend',
  'pair',
  'corresponded',
  '1969',
  'head',
  'death',
  '1986',
  'range',
  'subject',
  'including',
  'head',
  'novel',
  'question',
  'power'],
 ['mat',
  'zan',
  'coached',
  'kuala',
  'lumpur',
  'fa',
  '1999',
  'malaysia',
  'fa',
  'cup',
  '1999',
  'charity',
  'cup',
  '2000',
  '2001',
  'mat',
  'zan',
  'move',
  'head',
  'coach',
  'terengganu',
  'fa',
  '2001',
  'malaysia',
  'cup',
  '2001',
  'malaysia',
  'charity',
  'cup',
  'second',
  'place',
  'malaysia',
  'league',
  'plus',
  'f',
  'c',
  '2008',
  'took',
  '2nd',
  'place',
  'premier',
  'league',
  'automatically',
  'promoted',
  'malaysia',
  'super',
  'league',
  '2012',
  'comeback',
  'terengganu',
  'fa',
  'go',
  'fa',
  'cup',
  'semi',
  'final',
  'round',
  'two',
  'afc',
  'cup',
  '2015',
  'mat',
  'zan',
  'move',
  'melaka',
  'united',
  '2015',
  'malaysia',
  'fam',
  'league',
  '2016',
  'malaysia',
  'premier',
  'league',
  'contract',
  'renewed',
  'melaka',
  'end',
  '2016',
  'appointed',
  'new',
  'head',
  'coach',
  'airasia',
  'allstars',
  'fc',
  'renamed',
  'petaling',
  'jaya',
  'ranger',
  'f',
  'c',
  '2017',
  'season',
  'signed',
  '1',
  'year',
  'contract',
  'negeri',
  'sembilan',
  'form',
  '2019',
  'season',
  'mat',
  'zan',
  'also',
  'coached',
  'club',
  'side',
  'malaysia',
  'u',
  '21',
  'squad',
  'harimau',
  'muda',
  'b',
  'plate',
  'winner',
  'singapore',
  'starhub',
  'league',
  'cup',
  'thanj',
  'nien',
  'newspaper',
  'cup',
  'vietnam',
  '3rd',
  'place',
  'hassanal',
  'bolkiah',
  'cup',
  'brunei',
  '3rd',
  'place'],
 ['barcode',
  'machine',
  'readable',
  'optical',
  'label',
  'contains',
  'information',
  'item',
  'attached',
  'practice',
  'qr',
  'code',
  'often',
  'contain',
  'data',
  'locator',
  'identifier',
  'tracker',
  'point',
  'website',
  'application',
  'qr',
  'code',
  'us',
  'four',
  'standardized',
  'encoding',
  'mode',
  'numeric',
  'alphanumeric',
  'byte',
  'binary',
  'kanji',
  'store',
  'data',
  'efficiently',
  'extension',
  'may',
  'also',
  'used',
  'quick',
  'response',
  'system',
  'became',
  'popular',
  'outside',
  'automotive',
  'industry',
  'due',
  'fast',
  'readability',
  'greater',
  'storage',
  'capacity',
  'compared',
  'standard',
  'upc',
  'barcodes',
  'application',
  'include',
  'product',
  'tracking',
  'item',
  'identification',
  'time',
  'tracking',
  'document',
  'management',
  'general',
  'marketing',
  'qr',
  'code',
  'consists',
  'black',
  'square',
  'arranged',
  'square',
  'grid',
  'white',
  'background',
  'read',
  'imaging',
  'device',
  'camera',
  'processed',
  'using',
  'reed',
  'solomon',
  'error',
  'correction',
  'image',
  'appropriately',
  'interpreted',
  'required',
  'data',
  'extracted',
  'pattern',
  'present',
  'horizontal',
  'vertical',
  'component',
  'image',
  'qr',
  'code',
  'system',
  'invented',
  '1994',
  'japanese',
  'company',
  'denso',
  'wave',
  'purpose',
  'track',
  'vehicle',
  'manufacturing',
  'designed',
  'allow',
  'high',
  'speed',
  'component',
  'scanning',
  'qr',
  'code',
  'used',
  'much'],
 ['since',
  'subordination',
  'monarchy',
  'parliament',
  'increasingly',
  'democratic',
  'method',
  'parliamentary',
  'government',
  'question',
  'whether',
  'parliament',
  'hold',
  'supreme',
  'ability',
  'legislate',
  'whether',
  'traditional',
  'view',
  'put',
  'forward',
  'v',
  'dicey',
  'parliament',
  'power',
  'make',
  'law',
  'except',
  'law',
  'bound',
  'successor',
  'reconsidered',
  'constitutional',
  'theorist',
  'including',
  'sir',
  'william',
  'wade',
  'trevor',
  'allan',
  'light',
  'european',
  'community',
  'act',
  '1972',
  'provision',
  'relating',
  'europe',
  'position',
  'human',
  'right',
  'act',
  '1998',
  'attempt',
  'make',
  'legislation',
  'entrenched',
  'issue',
  'remain',
  'contested',
  'parliamentary',
  'sovereignty',
  'description',
  'extent',
  'parliament',
  'united',
  'kingdom',
  'absolute',
  'unlimited',
  'power',
  'framed',
  'term',
  'extent',
  'authority',
  'parliament',
  'hold',
  'whether',
  'sort',
  'law',
  'pas',
  'country',
  'written',
  'constitution',
  'often',
  'bind',
  'parliament',
  'act',
  'certain',
  'way',
  'written',
  'constitution',
  'united',
  'kingdom',
  'united',
  'kingdom',
  'parliament',
  'central',
  'institution',
  'state',
  'term'],
 ['tournament',
  'brought',
  'together',
  'club',
  'champion',
  'many',
  'domestic',
  'beach',
  'soccer',
  'league',
  'across',
  'europe',
  'almost',
  'vein',
  'uefa',
  'champion',
  'league',
  'twenty',
  'team',
  'confirmed',
  'participation',
  'inaugural',
  'tournament',
  'first',
  'beach',
  'soccer',
  'winner',
  'cup',
  'held',
  'sand',
  'san',
  'benedetto',
  'del',
  'tronto',
  'rive',
  'delle',
  'palme',
  'located',
  'ascoli',
  'italy',
  '15',
  '19',
  'may',
  '2013',
  'cup',
  'involving',
  'champion',
  'different',
  'official',
  'national',
  'league',
  'across',
  'old',
  'continent',
  '18',
  'different',
  'country',
  'represented',
  'tournament',
  'first',
  'stage',
  'eighteen',
  'champion',
  'officially',
  'sanctioned',
  'beach',
  'soccer',
  'national',
  'championship',
  'plus',
  'host',
  'italian',
  'runner',
  'got',
  'distributed',
  'five',
  'group',
  'yet',
  'offering',
  'interesting',
  'battle',
  'powerful',
  'team',
  'compete',
  'head',
  'group',
  'side',
  'topping',
  'group',
  'granted',
  'ticket',
  'quarterfinal',
  'stage',
  'accompanied',
  'three',
  'best',
  'second',
  'ranked',
  'team',
  'stadium',
  'used',
  'called',
  'umpi',
  'smart',
  'beach',
  'arena',
  'new',
  'state',
  'art',
  'facility',
  'intended',
  'maximize',
  'technology',
  'environmental',
  'consciousness',
  'directive',
  'create',
  'stadium',
  'offer',
  '360',
  'degree',
  'amusement',
  'possibility',
  'citizen'],
 ['january',
  '1948',
  'ballen',
  'acquired',
  'interest',
  'goode',
  'became',
  'sole',
  'owner',
  'moved',
  'company',
  'philadelphia',
  'pennsylvania',
  'label',
  'based',
  'rest',
  'existence',
  '1956',
  'label',
  'specialized',
  'rhythm',
  'blue',
  'ivin',
  'ballen',
  'died',
  'miami',
  'beach',
  'florida',
  'february',
  '1978',
  'gotham',
  'notable',
  'contribution',
  'american',
  'music',
  'release',
  'recording',
  'acoustic',
  'bluesman',
  'dan',
  'pickett',
  'originally',
  'recorded',
  '1949',
  'another',
  'artist',
  'recorded',
  'gotham',
  'included',
  'doug',
  'quattlebaum',
  'song',
  'lizzie',
  'lou',
  'one',
  'last',
  'release',
  'label',
  'doris',
  'browne',
  'singer',
  'around',
  '1949',
  '1950',
  'period',
  'performed',
  'weekly',
  'show',
  'broadcast',
  'wpen',
  'philadelphia',
  'hour',
  'long',
  'show',
  'called',
  'parisian',
  'tailor',
  'kiddie',
  'hour',
  '1953',
  'label',
  'appeared',
  'keen',
  'push',
  'browne',
  'profile',
  'single',
  'please',
  'believe',
  'bw',
  'oh',
  'baby',
  'backed',
  'doc',
  'bagby',
  'recording',
  'also',
  'backed',
  'single',
  'end',
  'time',
  'bw',
  'love',
  'gotham',
  'g',
  '296',
  'another',
  'recording',
  'game',
  'love',
  'bw',
  'cherie'],
 ['particularly',
  'notable',
  'association',
  'several',
  'canada',
  'leading',
  'blue',
  'singer',
  'including',
  'richard',
  'hock',
  'walsh',
  'tony',
  'flaim',
  'chuck',
  'jackson',
  'also',
  'associated',
  'downchild',
  'blue',
  'band',
  'band',
  'named',
  'cameo',
  'lounge',
  'toronto',
  'hotel',
  'isabella',
  '1970s',
  '1980s',
  'cameo',
  'lounge',
  'featured',
  'primarily',
  'local',
  'blue',
  'artist',
  '1978',
  'regular',
  'house',
  'band',
  'initially',
  'led',
  'richard',
  'hock',
  'walsh',
  'one',
  'several',
  'period',
  'walsh',
  'either',
  'fired',
  'quit',
  'lead',
  'singer',
  'downchild',
  'blue',
  'band',
  'walsh',
  'soon',
  'joined',
  'former',
  'crowbar',
  'keyboard',
  'player',
  'rabbit',
  'ray',
  'harrison',
  'along',
  'guitarist',
  'john',
  'bride',
  'became',
  'core',
  'group',
  'three',
  'decade',
  'history',
  'initial',
  'band',
  'member',
  'included',
  'billy',
  'bryan',
  'later',
  'parachute',
  'club',
  'drum',
  'omar',
  'tunnock',
  'later',
  'funk',
  'blue',
  'band',
  'fathead',
  'bass',
  'hock',
  'walsh',
  'soon',
  'left',
  'band',
  'return',
  'downchild',
  'briefly',
  'replaced',
  'fraser',
  'finlayson',
  'band',
  'cueball',
  'prior',
  'band',
  'finding',
  'replacement',
  'tony',
  'flaim',
  'hock',
  'walsh',
  'replaced',
  'downchild',
  'billy',
  'bryan',
  'replaced'],
 ['also',
  'known',
  'wamba',
  'wamba',
  'wemba',
  'wemba',
  'bear',
  'strong',
  'similarity',
  'woiwurrung',
  'moravian',
  'missionary',
  'came',
  'started',
  'learn',
  'language',
  'wembawemba',
  'territory',
  'archibald',
  'macarthur',
  'camppbell',
  'gannawarra',
  'station',
  'quickly',
  'noted',
  'native',
  'perceiving',
  'understood',
  'slipped',
  'using',
  'another',
  'language',
  'willing',
  'allow',
  'cultural',
  'conquest',
  'enable',
  'whitemen',
  'learn',
  'matter',
  'wished',
  'keep',
  'secret',
  'outsider',
  'european',
  'settlement',
  'nineteenth',
  'century',
  'wemba',
  'wemba',
  'occupied',
  'area',
  'around',
  'loddon',
  'river',
  'reaching',
  'northward',
  'kerang',
  'victoria',
  'swan',
  'hill',
  'including',
  'area',
  'avoca',
  'river',
  'southward',
  'towards',
  'quambatook',
  'northeasterly',
  'direction',
  'territory',
  'ran',
  'new',
  'south',
  'wale',
  'victorian',
  'border',
  'boorrorban',
  'moulamein',
  'extended',
  'vicinity',
  'barham',
  'lake',
  'boga',
  'boora',
  'victoria',
  'also',
  'fell',
  'within',
  'domain',
  'overall',
  'extension',
  'territory',
  'calculated',
  'norman',
  'tindale',
  'roughly',
  'wembawemba',
  'registered',
  'consisting',
  'five',
  'horde',
  'stone',
  'list',
  'horde',
  'residing',
  'around',
  'towaninny',
  'meelool',
  'station',
  'name',
  'indicating',
  'thought',
  'quarrelsome',
  'lake',
  'boga',
  'gonn',
  'murray',
  'river',
  'called',
  'dietjenbaluk',
  'always'],
 ['moved',
  'south',
  'england',
  'cannock',
  'staffordshire',
  'formed',
  'balaam',
  'angel',
  'initially',
  'band',
  'self',
  'released',
  'series',
  'ep',
  'album',
  'entitled',
  'sun',
  'family',
  'via',
  'chapter',
  '22',
  'label',
  'played',
  'tour',
  'date',
  'opening',
  'cult',
  'caught',
  'attention',
  'virgin',
  'record',
  'signed',
  'released',
  'debut',
  'album',
  'greatest',
  'story',
  'ever',
  'told',
  'peaked',
  '67',
  'uk',
  'album',
  'chart',
  'august',
  '1986',
  'toured',
  'united',
  'state',
  'mission',
  'kiss',
  'label',
  'mate',
  'iggy',
  'pop',
  'second',
  'guitarist',
  'first',
  'non',
  'sibling',
  'ian',
  'mckean',
  'twenty',
  'flight',
  'rocker',
  'added',
  'band',
  '1988',
  'band',
  'began',
  'move',
  'away',
  'gothic',
  'rock',
  'music',
  'style',
  'sound',
  'common',
  'hard',
  'rock',
  'new',
  'found',
  'style',
  'recorded',
  'album',
  'live',
  'free',
  'die',
  'soon',
  'followed',
  'similar',
  'style',
  'recorded',
  'day',
  'madness',
  'leaving',
  'virgin',
  'record',
  'song',
  'show',
  'something',
  'special',
  'appeared',
  'soundtrack',
  'film',
  'plane',
  'train',
  'automobile',
  'presence',
  'largely',
  'ignored',
  'time',
  '1993',
  'album',
  'prime'],
 ['farming',
  'forestry',
  'remain',
  'central',
  'rural',
  'economy',
  'rural',
  'development',
  'also',
  'focus',
  'revitalising',
  'rural',
  'area',
  'way',
  'furthermore',
  'issue',
  'climate',
  'change',
  'renewable',
  'energy',
  'biodiversity',
  'water',
  'management',
  'becoming',
  'increasingly',
  'important',
  'aspect',
  'eu',
  'rural',
  'development',
  'policy',
  '200',
  'billion',
  'funding',
  'available',
  'support',
  'implementation',
  '94',
  'rdps',
  'across',
  'eu',
  'programming',
  'period',
  '2007',
  '2013',
  'almost',
  'half',
  'money',
  'provided',
  'eafrd',
  'overseen',
  'european',
  'commission',
  'directorate',
  'general',
  'agriculture',
  'rural',
  'development',
  'eafrd',
  'budget',
  'rdps',
  'used',
  'achieve',
  'variety',
  'rural',
  'development',
  'goal',
  'including',
  'improving',
  'competitiveness',
  'farm',
  'forest',
  'agri',
  'food',
  'business',
  'helping',
  'protect',
  'natural',
  'environment',
  'supporting',
  'rural',
  'economy',
  'assisting',
  'quality',
  'life',
  'rural',
  'area'],
 ['died',
  'working',
  'project',
  'great',
  'storm',
  '1703',
  'born',
  'saffron',
  'walden',
  'essex',
  'baptised',
  '31',
  'march',
  '1644',
  'father',
  'henry',
  'became',
  'land',
  'steward',
  'earl',
  'suffolk',
  'owner',
  'audley',
  'end',
  'house',
  '1652',
  'young',
  'henry',
  'also',
  'worked',
  'audley',
  'end',
  'first',
  'porter',
  'secretary',
  '1666',
  'audley',
  'end',
  'house',
  'bought',
  'charles',
  'ii',
  'use',
  'base',
  'attending',
  'newmarket',
  'race',
  'became',
  'effectively',
  'royal',
  'palace',
  'winstanley',
  'developed',
  'interest',
  'engraving',
  'grand',
  'tour',
  'europe',
  '1669',
  '1674',
  'impressed',
  'continental',
  'architecture',
  'engraving',
  'portrayed',
  'return',
  'believed',
  'studied',
  'engraving',
  'wenceslas',
  'hollar',
  'employed',
  'audley',
  'end',
  'house',
  'assistant',
  'clerk',
  'work',
  '1676',
  'embarked',
  'detailed',
  'set',
  'architectural',
  'engraving',
  'audley',
  'end',
  'house',
  'took',
  'ten',
  'year',
  'complete',
  'survive',
  'important',
  'early',
  'record',
  'english',
  'manor',
  'house',
  'architecture',
  'also',
  'designed',
  'set',
  'playing',
  'card',
  'became',
  'popular',
  'sold',
  'well',
  'appointed',
  'clerk'],
 ['grade',
  'listed',
  'building',
  'written',
  'history',
  'denton',
  'go',
  'back',
  'least',
  '1253',
  'owner',
  'one',
  'athelstan',
  'confused',
  'king',
  'name',
  'made',
  'estate',
  'see',
  'york',
  'already',
  'owned',
  'manorial',
  'right',
  'nearby',
  'otley',
  'subinfeuded',
  'sub',
  'let',
  'early',
  'date',
  'vavasours',
  '1284',
  'maugerus',
  'le',
  'vavasur',
  'held',
  'town',
  'fourth',
  'part',
  'knight',
  'fee',
  'archbishop',
  'york',
  'continued',
  'lord',
  'paramount',
  '1379',
  'according',
  'poll',
  'tax',
  'return',
  'one',
  'adam',
  'wayte',
  'appears',
  'farming',
  'manor',
  'time',
  'denton',
  'ordinary',
  'reputation',
  'clothes',
  'making',
  'drapery',
  'good',
  'estate',
  'passed',
  'ownership',
  'thwaites',
  'family',
  'elizabeth',
  'daughter',
  'henry',
  'thwaites',
  'married',
  'john',
  'vavasour',
  'weston',
  'died',
  '1482',
  'record',
  'show',
  'thwaites',
  'family',
  'resident',
  'denton',
  'village',
  'earlier',
  'time',
  'marriage',
  '1515',
  'estate',
  'passed',
  'fairfax',
  'family',
  'time',
  'thomas',
  'fairfax',
  '1st',
  'lord',
  'fairfax',
  'cameron',
  'denton',
  'hall',
  'repute',
  'housing',
  'one',
  'best',
  'library'],
 ['elected',
  'house',
  'representative',
  'nigeria',
  '2007',
  'represent',
  'ebonyi',
  'ohaukwu',
  'federal',
  'constituency',
  'elected',
  'platform',
  'people',
  'democratic',
  'party',
  'pdp',
  'hon',
  'elizabeth',
  'ogbaga',
  'member',
  'following',
  'committee',
  'december',
  '2009',
  'hon',
  'elizabeth',
  'ogbaga',
  'expressed',
  'dissatisfaction',
  'called',
  'low',
  'level',
  'implementation',
  'project',
  'contained',
  '2009',
  'budget',
  'sponsored',
  'numerous',
  'bill',
  'motion',
  'often',
  'decried',
  'low',
  'participation',
  'woman',
  'politics',
  'stating',
  'affected',
  'democracy',
  'hon',
  'elizabeth',
  'ogbaga',
  'attracted',
  'various',
  'project',
  'oxygen',
  'plant',
  'mammogram',
  'machine',
  'federal',
  'medical',
  'centre',
  'abakaliki',
  'free',
  'antenatal',
  'care',
  'service',
  'pregnant',
  'mother',
  'ebonyi',
  'ohaukwu',
  'federal',
  'constituency',
  'construction',
  'several',
  '3',
  'classroom',
  'block',
  'hand',
  'pump',
  'boreholes',
  'onuenyim',
  'ishieke',
  'ndiofia',
  'nkaleke',
  'igweledoha',
  'ogbala',
  'parish',
  'effenyim',
  'ongoing',
  'oterufie',
  'nkaleke',
  'ndiechi',
  'ndiugo',
  'isophumini',
  'mbeke',
  'isophumini',
  'st',
  'michael',
  'parish',
  'mbeke',
  'ishieke',
  'nwonuewo',
  'effium',
  'ohaukwu',
  'ogen',
  'ohaukwu',
  'umugadu',
  'community',
  'secondary',
  'school',
  'also',
  'constructed',
  'national',
  'health',
  'care',
  'centre',
  'izenyi',
  'agbaja',
  'izzi',
  'lga',
  'ohagelode',
  'ongoing',
  'trained',
  '50',
  'youth',
  'ict',
  'well',
  'providing',
  'computer',
  'accessory',
  'hon',
  'elizabeth',
  'ogbaga',
  'constructed',
  'bridge',
  'across',
  'ebonyi',
  'river'],
 ['held',
  'annually',
  'since',
  '2007',
  'southern',
  'bank',
  'lake',
  'balaton',
  'hungary',
  'feature',
  'live',
  'act',
  'dj',
  'around',
  'world',
  'established',
  'artist',
  'new',
  'name',
  'event',
  'co',
  'created',
  'organizer',
  'sziget',
  'festival',
  'festival',
  'get',
  'famous',
  'popular',

In [5]:
len(lemmatized_tokenized_docs)

369721

In [6]:
from helper import create_tokenized_word_list_for_query
query_tokenized = create_tokenized_word_list_for_query(dataset)
print("Queries tokenized!")

Queries tokenized!

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [7]:
lemmatized_tokenized_queries = []

for query_list in query_tokenized:
    lemmatized_words = [lematizer.lemmatize(words) for words in query_list]
    lemmatized_tokenized_queries.append(lemmatized_words)

print("Queries lemmatized")

Queries lemmatized

In [8]:
lemmatized_docs = []

for lemma_token_doc in lemmatized_tokenized_docs:
    lemmatized_docs.append(" ".join(lemma_token_doc))

lemmatized_docs

['used landing craft world war ii used today private boat training facility 6 71 inline six cylinder diesel engine 71 refers displacement cubic inch cylinder firing order engine 1 5 3 6 2 4 engine compression ratio 18 7 1 4 250 inch bore 5 00 inch stroke engine weighs 54 inch long 29 inch wide 41 inch tall 2 100 revolution per minute engine capable producing 230 horse power 172 kilowatt v type version 71 series developed 1957 6 71 two stroke engine engine naturally aspirate air provided via root type blower however 6 71t model turbocharger supercharger utilized fuel provided unit injector one per cylinder amount fuel injected engine controlled engine governor engine cooling via liquid water jacket boat cool external water pumped engine',
 'rejecting offer cambridge university moved london 1954 working mayfair advertising agency moonlighting hat check girl night club le club contemporain working royal college art met painter frank bowling still student married 1960 one son kitchen one woman interviewed nell dunn talking woman 1965 divorcing bowling late sixty kitchen went live later marry writer dulan barber continuing write novel also began writing non fiction biography patrick geddes gerard manley hopkins later life bought house barnwell northamptonshire became subject book name died 23 november 2005 novelist bessie head close friend pair corresponded 1969 head death 1986 range subject including head novel question power',
 'mat zan coached kuala lumpur fa 1999 malaysia fa cup 1999 charity cup 2000 2001 mat zan move head coach terengganu fa 2001 malaysia cup 2001 malaysia charity cup second place malaysia league plus f c 2008 took 2nd place premier league automatically promoted malaysia super league 2012 comeback terengganu fa go fa cup semi final round two afc cup 2015 mat zan move melaka united 2015 malaysia fam league 2016 malaysia premier league contract renewed melaka end 2016 appointed new head coach airasia allstars fc renamed petaling jaya ranger f c 2017 season signed 1 year contract negeri sembilan form 2019 season mat zan also coached club side malaysia u 21 squad harimau muda b plate winner singapore starhub league cup thanj nien newspaper cup vietnam 3rd place hassanal bolkiah cup brunei 3rd place',
 'barcode machine readable optical label contains information item attached practice qr code often contain data locator identifier tracker point website application qr code us four standardized encoding mode numeric alphanumeric byte binary kanji store data efficiently extension may also used quick response system became popular outside automotive industry due fast readability greater storage capacity compared standard upc barcodes application include product tracking item identification time tracking document management general marketing qr code consists black square arranged square grid white background read imaging device camera processed using reed solomon error correction image appropriately interpreted required data extracted pattern present horizontal vertical component image qr code system invented 1994 japanese company denso wave purpose track vehicle manufacturing designed allow high speed component scanning qr code used much',
 'since subordination monarchy parliament increasingly democratic method parliamentary government question whether parliament hold supreme ability legislate whether traditional view put forward v dicey parliament power make law except law bound successor reconsidered constitutional theorist including sir william wade trevor allan light european community act 1972 provision relating europe position human right act 1998 attempt make legislation entrenched issue remain contested parliamentary sovereignty description extent parliament united kingdom absolute unlimited power framed term extent authority parliament hold whether sort law pas country written constitution often bind parliament act certain way written constitution united kingdom united kingdom parliament central institution state term',
 'tournament brought together club champion many domestic beach soccer league across europe almost vein uefa champion league twenty team confirmed participation inaugural tournament first beach soccer winner cup held sand san benedetto del tronto rive delle palme located ascoli italy 15 19 may 2013 cup involving champion different official national league across old continent 18 different country represented tournament first stage eighteen champion officially sanctioned beach soccer national championship plus host italian runner got distributed five group yet offering interesting battle powerful team compete head group side topping group granted ticket quarterfinal stage accompanied three best second ranked team stadium used called umpi smart beach arena new state art facility intended maximize technology environmental consciousness directive create stadium offer 360 degree amusement possibility citizen',
 'january 1948 ballen acquired interest goode became sole owner moved company philadelphia pennsylvania label based rest existence 1956 label specialized rhythm blue ivin ballen died miami beach florida february 1978 gotham notable contribution american music release recording acoustic bluesman dan pickett originally recorded 1949 another artist recorded gotham included doug quattlebaum song lizzie lou one last release label doris browne singer around 1949 1950 period performed weekly show broadcast wpen philadelphia hour long show called parisian tailor kiddie hour 1953 label appeared keen push browne profile single please believe bw oh baby backed doc bagby recording also backed single end time bw love gotham g 296 another recording game love bw cherie',
 'particularly notable association several canada leading blue singer including richard hock walsh tony flaim chuck jackson also associated downchild blue band band named cameo lounge toronto hotel isabella 1970s 1980s cameo lounge featured primarily local blue artist 1978 regular house band initially led richard hock walsh one several period walsh either fired quit lead singer downchild blue band walsh soon joined former crowbar keyboard player rabbit ray harrison along guitarist john bride became core group three decade history initial band member included billy bryan later parachute club drum omar tunnock later funk blue band fathead bass hock walsh soon left band return downchild briefly replaced fraser finlayson band cueball prior band finding replacement tony flaim hock walsh replaced downchild billy bryan replaced',
 'also known wamba wamba wemba wemba bear strong similarity woiwurrung moravian missionary came started learn language wembawemba territory archibald macarthur camppbell gannawarra station quickly noted native perceiving understood slipped using another language willing allow cultural conquest enable whitemen learn matter wished keep secret outsider european settlement nineteenth century wemba wemba occupied area around loddon river reaching northward kerang victoria swan hill including area avoca river southward towards quambatook northeasterly direction territory ran new south wale victorian border boorrorban moulamein extended vicinity barham lake boga boora victoria also fell within domain overall extension territory calculated norman tindale roughly wembawemba registered consisting five horde stone list horde residing around towaninny meelool station name indicating thought quarrelsome lake boga gonn murray river called dietjenbaluk always',
 'moved south england cannock staffordshire formed balaam angel initially band self released series ep album entitled sun family via chapter 22 label played tour date opening cult caught attention virgin record signed released debut album greatest story ever told peaked 67 uk album chart august 1986 toured united state mission kiss label mate iggy pop second guitarist first non sibling ian mckean twenty flight rocker added band 1988 band began move away gothic rock music style sound common hard rock new found style recorded album live free die soon followed similar style recorded day madness leaving virgin record song show something special appeared soundtrack film plane train automobile presence largely ignored time 1993 album prime',
 'farming forestry remain central rural economy rural development also focus revitalising rural area way furthermore issue climate change renewable energy biodiversity water management becoming increasingly important aspect eu rural development policy 200 billion funding available support implementation 94 rdps across eu programming period 2007 2013 almost half money provided eafrd overseen european commission directorate general agriculture rural development eafrd budget rdps used achieve variety rural development goal including improving competitiveness farm forest agri food business helping protect natural environment supporting rural economy assisting quality life rural area',
 'died working project great storm 1703 born saffron walden essex baptised 31 march 1644 father henry became land steward earl suffolk owner audley end house 1652 young henry also worked audley end first porter secretary 1666 audley end house bought charles ii use base attending newmarket race became effectively royal palace winstanley developed interest engraving grand tour europe 1669 1674 impressed continental architecture engraving portrayed return believed studied engraving wenceslas hollar employed audley end house assistant clerk work 1676 embarked detailed set architectural engraving audley end house took ten year complete survive important early record english manor house architecture also designed set playing card became popular sold well appointed clerk',
 'grade listed building written history denton go back least 1253 owner one athelstan confused king name made estate see york already owned manorial right nearby otley subinfeuded sub let early date vavasours 1284 maugerus le vavasur held town fourth part knight fee archbishop york continued lord paramount 1379 according poll tax return one adam wayte appears farming manor time denton ordinary reputation clothes making drapery good estate passed ownership thwaites family elizabeth daughter henry thwaites married john vavasour weston died 1482 record show thwaites family resident denton village earlier time marriage 1515 estate passed fairfax family time thomas fairfax 1st lord fairfax cameron denton hall repute housing one best library',
 'elected house representative nigeria 2007 represent ebonyi ohaukwu federal constituency elected platform people democratic party pdp hon elizabeth ogbaga member following committee december 2009 hon elizabeth ogbaga expressed dissatisfaction called low level implementation project contained 2009 budget sponsored numerous bill motion often decried low participation woman politics stating affected democracy hon elizabeth ogbaga attracted various project oxygen plant mammogram machine federal medical centre abakaliki free antenatal care service pregnant mother ebonyi ohaukwu federal constituency construction several 3 classroom block hand pump boreholes onuenyim ishieke ndiofia nkaleke igweledoha ogbala parish effenyim ongoing oterufie nkaleke ndiechi ndiugo isophumini mbeke isophumini st michael parish mbeke ishieke nwonuewo effium ohaukwu ogen ohaukwu umugadu community secondary school also constructed national health care centre izenyi agbaja izzi lga ohagelode ongoing trained 50 youth ict well providing computer accessory hon elizabeth ogbaga constructed bridge across ebonyi river',
 'held annually since 2007 southern bank lake balaton hungary feature live act dj around world established artist new name event co created organizer sziget festival festival get famous popular year ticket usually sold go sale official ticket vendor event set new attendance record yearly first balaton sound festival held 12 july 15 july 2007 fact event held shore largest lake central europe mid summer twenty hour music schedule line gained significant public interest festival located west part zam rdi crossing panor z ldfa utca street inside festival area variable stage lounge tent established performance sponsor festival create luxurious chill facility hammock bean bag easy chair visitor balaton sound stay special campsite several pub cocktail bar restaurant equipped accoutrement absent hungary summer music',
 'co founded phillips collection husband duncan phillips born marjorie acker bourbon indiana sister six sibling parent charles ernest acker alice beal raised ossining new york phillips started drawing child uncle reynolds beal gifford beal men noticed phillips artistic ability suggested pursue art career path began attending art student league 1915 graduated 1918 studied boardman robinson marjorie phillips unmistakable style born painter duncan phillips phillips quoted stating want paint depressing picture painted primarily landscape still life work despite living socialite lifestyle alongside husband phillips made effort paint every morning washington c studio attended art exhibition duncan phillips century association january 1921 met duncan two married october year duncan art collector couple expanded collecting phillips moved washington c duncan dupont circle mansion duncan mother',
 '21 november 1811 21 may 1883 german born british botanist zoologist preiss born herzberg harz obtained doctorate probably hamburg emigrated western australia arrived swan river colony board britmart 4 december 1838 remaining january 1842 time became british subject time western australia preiss collected 200 000 plant specimen containing 3 000 4 000 specie collection together james drummond formed basis early study western australian flora 1842 left western australia london broke sold plant collection recoup cost various botanist published specie based specimen later collated johann lehmann form multi volume plantae preissianae sive enumeratio plantarum quas australasia occidentali et meridionale occidentali annis 1838 41 collegit l published hamburg 1844 1848 specimen collected preiss limited plant included bird reptile insect mollusc mollusc described karl theodor menke published hanover 1843 titled molluscorum',
 'emigrated france family 1956 due rise antisemitism egypt studied cole normale sup rieure de saint cloud sorbonne institut etude politiques de paris rousso notable work includes seminal book vichy france entitled vichy syndrome 1987 coined phrase commonly used describe era pas qui ne passe pa past pas expression possibly inspired ernst nolte june 6 1986 article entitled die vergangenheit die nicht vergehen past want pas away rousso currently serf director research french national centre scientific research cnrs involved since 1981 february 22 2017 rousso detained u custom border protection cbp agent 10 hour arrival george bush intercontinental airport houston nearly deported come give talk texas university detained entering country tourist visa paid stipend talk custom border protection agent',
 'headquarters london united kingdom stopped crowd funding service 2014 doctoral student oxford university vincent developed keen interest work muhammad yunus pioneer microfinance vincent saw peer peer microfinance brilliant alternative traditional method funding innovative idea 2009 financial crisis subsequent cut subsidy hit uk art scene highlighted need alternative community led way raising fund artist innovator prompting vincent launch sponsume site us power social network wisdom crowd help fund variety project ranging film documentary music theatre photography fashion technology scientific research green social enterprise 2012 sponsume helped crowd fund 1000 campaign project owner choose timeframe deadline target funding goal create non monetary reward generally linked project site levy 4 fee successful campaign collect 9 campaign failed reach target amount',
 'composed traditional tribe loteae sesbanieae robinieae large important clade distributed mostly temperate area specie clade share unique determinate root nodule structure clade predicted diverged legume lineage 48 3 1 0 million year ago eocene two tribe loteae robinieae traditionally included clade robinioids lavin schrire later included sesbanieae clade robinioids tribe robinieae primarily tropical arid temperate area containing mostly tree shrub new world tribe loteae herbaceous small shrubby legume closely related old world tribe galegeae loteae originally smaller group legume later 1994 polhill merged loteae tribe coronilleae greatly expanded loteae sesbanieae tribe single genus sesbania originally placed tribe robinieae loteae robinieae traditionally grouped clade robinioids two major group primarily found europe north america south america sesbanieae group included 2005 monophyly monophyly tribe loteae molecular data shown support monophyly exception new world lotus monophyly old',
 'south american conglomerate created owned germ n efromovich entrepreneur holding multiple citizenship brazil colombia poland group headquartered rio de janeiro brazil operates several airline south america among avianca holding 66 66 stake active exploration oil natural gas throughout region additionally operates hydroelectric power plant participates construction telecommunication infrastructure shipbuilding technical inspection radiochemistry radiopharmaceutical agriculture hospitality synergy group integrated airline company taca avianca holding company avianca holding synergy group owns 66 66 newly created subsidiary company kingsland holding el salvador owns 33 33 avianca taca synergy aerospace corp sub division synergy group headquartered bogota colombia major shareholder avianca holding company control eight airline four country avianca tampa cargo colombia avianca brazil variglog synerjet brazil vip aerogal ecuador grupo taca el salvador november 2012 synergy aerospace corp established synergy aerospace europe synergy aerospace established joint venture march 2011',
 'army regimental system headquarters stow ohio currently consists 1st battalion 145th armored regiment 900 soldier combined arm battalion ohio army national guard located throughout northeast ohio command control purpose within ohio army national guard 1st battaltion 145th armored regiment subordinate battalion 174th air defense artillery brigade 2013 battalion entered alignment training relationship 1st armored brigade combat team 34th infantry division may 2016 battalion donned shoulder sleeve insignia 34th infantry division anticipation formal alignment 1st armored brigade combat team september 2016 combined arm battalion 1st battalion 145th armored regiment able deploy two mechanized infantry company two armor company support company headquarters company battalion headquarters order accomplish federal state community mission headquarters company hhc four line company organic battalion combined arm battalion traditionally receive support company organic brigade support battalion bsb since battalion organic armored brigade combat team abct 737th support company',
 'unexpected object case morphology deemed exceptional term ecm coined government binding grammar framework although phenomenon closely related accusativus cum infinitivo construction latin ecm construction also studied within context raising verb license ecm known raising object verb many language lack ecm predicate even english number ecm verb small structural analysis ecm construction varies part according whether one pursues relatively flat structure layered one ecm construction licensed relatively small number verb english e g believe judge prove want let etc string bold ecm construction pronoun marked object case morphology function semantically subject infinitival verb right e acquire theta role verb right many ecm verb allow meaning expressed full object clause finite clause e g since meaning across clause remains consistent one tendency view ecm material e',

In [9]:
lemmatized_queries = []

for query_list in lemmatized_tokenized_queries:
    lemmatized_queries.append(" ".join(query_list))

lemmatized_queries

['yanni',
 'k pop',
 'venice film festival',
 'downtown brooklyn',
 'pennsylvania house representative',
 'northern premier league',
 'first national picture',
 'poland',
 'cyperaceae',
 'trinidad tobago',
 'normandy landing',
 'perry index',
 'arm architecture',
 'mi5',
 'patriarch antioch',
 'nashik district',
 'semiotics',
 'santa cruz de tenerife',
 'gastropoda',
 'zaragoza',
 'south carolina',
 'augustine hippo',
 'canton geneva',
 'leo tolstoy',
 'riemannian manifold',
 'tuzla',
 'subaru',
 'tomsk',
 'united state department agriculture',
 'north borneo',
 'isaac asimov',
 'hilbert space',
 'chechen',
 'arunachal pradesh',
 'central otago',
 'ira gershwin',
 'rock roll',
 'fiba',
 'east coast united state',
 'wikipedia',
 'pernambuco',
 'west coast eagle',
 'twin peak',
 'dutch language',
 'liberal party canada',
 'spratly island',
 'kampala',
 'national film board canada',
 'turkish war independence',
 'chania',
 'oakland raider',
 'krishnagiri district',
 'vr group',
 'trade name',
 'anglo saxon',
 'bermuda',
 'paradox development studio',
 'usenet',
 'bbc radio',
 'wallace stevens',
 'spain',
 'franchising',
 'united artist record',
 'royal corp signal',
 'palawan',
 'seine et marne',
 'west country',
 'bailiwick guernsey',
 'pleuronectidae',
 'income tax united state',
 'gp3 series',
 'septimius severus',
 'pharaoh',
 'metropolitan borough doncaster',
 'history jew poland',
 'erasure',
 'suez canal',
 'naval air station lemoore',
 'lower saxony',
 'robert stack',
 'boeing',
 'wexford gaa',
 'miss universe',
 'sydney central business district',
 'keweenaw peninsula',
 'music',
 'nba g league',
 'makati',
 'genre art',
 'aintree racecourse',
 'colchester',
 'christian rock',
 'clash',
 'friedrich schiller',
 'comedy drama',
 'tiberias',
 'fc basel',
 'new york knicks',
 'perm krai',
 'dordogne',
 'dutch west india company',
 'titian',
 'victorian burlesque',
 'tvb',
 'muridae',
 'tvxq',
 'kenneth cope',
 'london borough islington',
 'top cow production',
 'bradford bull',
 'mike oldfield',
 'shooter game',
 'hull kingston rover',
 'national science foundation',
 'grau',
 'dannii minogue',
 'christopher nolan',
 'moscow oblast',
 'british national party',
 'balochi language',
 'benjamin franklin',
 'big south conference',
 'cantabria',
 'alice chain',
 'michigan',
 'soundgarden',
 'bermondsey',
 '2017 ncaa division fbs football season',
 'northwestern united state',
 'southeast asia',
 'social psychology',
 'john coltrane',
 'roll distinguished philatelist',
 'restoration movement',
 'danny elfman',
 'konkani language',
 'dungannon',
 'united soccer league',
 'chapter verse bible',
 'isle man tt',
 'eth zurich',
 'emirate abu dhabi',
 'delaware river',
 'black sea',
 'antigua',
 'primary school',
 'berber language',
 'loch lomond',
 'african union',
 'north american numbering plan',
 'ural mountain',
 'utah',
 'algarve cup',
 'mixed martial art',
 'jaxa',
 'plateau state',
 'albanian national awakening',
 'unionidae',
 'mystery fiction',
 'metropolitan police service',
 'bukovina',
 'wilbert awdry',
 'american',
 'western bulldog',
 'christian theology',
 'patriarch',
 'skanderbeg',
 'korea japanese rule',
 'major league lacrosse',
 'perak',
 'graduate school',
 'master fine art',
 'little league world series',
 'tugboat',
 '2016 united state presidential election',
 'united state national rugby union team',
 '1906 intercalated game',
 'bocas del toro province',
 'inline four engine',
 'english feudal barony',
 'royal guelphic order',
 'bodybuilding',
 'dusty springfield',
 'caserta',
 'northrop grumman',
 'bourbon restoration',
 'sql',
 'south cambridgeshire',
 'alappuzha',
 'united state national guard',
 'korean drama',
 'thiruvananthapuram',
 'collecting',
 'uzbek',
 'vickers limited',
 'luis miguel',
 'ottoman navy',
 'truman capote',
 'arnold schwarzenegger',
 'taurus mountain',
 'easter rising',
 'henry david thoreau',
 'george jones',
 'bbc radio 1',
 'craven',
 'architecture',
 'sega',
 'second sea lord',
 'stena line',
 'wingecarribee shire',
 'fraser coast region',
 'intellivision',
 'gridiron football',
 'moreton bay region',
 'ultimate play game',
 'literature',
 'podgorica',
 'lugano',
 'smokey robinson',
 'major league soccer',
 'london borough redbridge',
 'roman britain',
 'budapest',
 'rugby football',
 'archbishop york',
 'edward ii england',
 'ajmer',
 'yamaguchi prefecture',
 'jaipur',
 'indonesian cuisine',
 'port los angeles',
 'british academy',
 'united methodist church',
 'independent music',
 'chiswick',
 'celebrity',
 'ivy league',
 'na',
 'province massachusetts bay',
 'christmas carol',
 'aix en provence',
 'black hill',
 'willamette valley',
 'master wine',
 'carl reiner',
 'podlaskie voivodeship',
 'princess',
 'collins crime club',
 'romanian naval force',
 'poxviridae',
 'koper',
 'limerick gaa',
 'ancona',
 'mauritius',
 'clark university',
 'ohio',
 'ludwigsburg',
 'province chile',
 'right wing politics',
 'horticulture',
 'richard nixon',
 'indie rock',
 'samsung',
 'virginia general assembly',
 'schutzstaffel',
 'cloud computing',
 'upper carniola',
 'crown colony',
 'metropolitan borough solihull',
 'valladolid',
 'william goldman',
 'socialist unity party germany',
 'irem',
 'turkic people',
 'coldplay',
 'prunus',
 'odin',
 'vh1',
 'twelfth grade',
 'faversham',
 'city townsville',
 'trinity college dublin',
 'tasmanian house assembly',
 'kgb',
 'idaho',
 'liao dynasty',
 'gascon language',
 'luxembourg city',
 'saddam hussein',
 'ovid',
 'venus',
 'srikakulam district',
 'vest agder',
 'comedy',
 'megadeth',
 'sioux',
 'baie james',
 'frontier martial art wrestling',
 'east lothian',
 'indomalayan realm',
 'albacete',
 'richard fleischer',
 'cincinnati red',
 'vyborg',
 'provincial assembly punjab',
 'hamburg',
 'ku ring gai council',
 'hanoi',
 'northern england',
 'nonpartisanism',
 'reserve bank india',
 'tony hatch',
 'joan arc',
 'chinese american',
 'fox broadcasting company',
 'parramatta eel',
 'duisburg',
 'oxford university press',
 'yukon',
 'tenant purchase scheme',
 'cthulhu mythos',
 'cape town',
 'phoenicia',
 'equestrianism',
 'taunton',
 '1947 ceylonese parliamentary election',
 'triathlon',
 'west coast main line',
 'ghana',
 'manchester metrolink',
 'darfur',
 'jim crockett promotion',
 'antoninus pius',
 'isle dog',
 'smith',
 'dewan rakyat',
 'jennifer rowe',
 'kaduna state',
 'dahomey',
 'nakskov',
 'ciutat vella',
 'ohio river',
 'civil engineering',
 'kaluga oblast',
 'london borough croydon',
 'guillermo del toro',
 'germany',
 'french polynesia',
 'chvrches',
 'mark twain',
 'shaheed bhagat singh nagar district',
 'cyclades',
 'strabo',
 'milton bradley company',
 'occitan language',
 'yenisei river',
 'bangladesh',
 'lake tahoe',
 'brandenburg',
 'jacob',
 'france national football team',
 'veikkausliiga',
 '2015 canadian federal election',
 'kurdistan region',
 'snk',
 'bbc television',
 'united state department defense',
 'prince elector',
 'new england',
 'rca',
 'qinghai',
 'chilean war independence',
 'daft punk',
 'ghana national football team',
 'chinese buddhism',
 'florence',
 'samara oblast',
 'yekaterinburg',
 'connecticut river',
 'indonesia',
 'vancouver',
 'miami marlin',
 'joseph stalin',
 'travel literature',
 'christian democratic appeal',
 'detroit piston',
 'taranto',
 'port washington branch',
 'yellowknife',
 'sahrawi arab democratic republic',
 'derry gaa',
 'unionism ireland',
 'soviet armed force',
 'los angeles',
 'thomas jefferson',
 'hal roach',
 'cardiff rfc',
 'government kerala',
 'regent',
 'british people',
 'american',
 'bell system',
 'sabrina carpenter',
 'danielle steel',
 'lincolnshire',
 'printmaking',
 'vicenza',
 'eric clapton',
 'dj khaled',
 'county donegal',
 'lockheed corporation',
 'southern rock',
 'george gershwin',
 'salvation army',
 'bell lab',
 'list north carolina state park',
 'falklands war',
 'gustav mahler',
 'monster movie',
 'cheap trick',
 'chinese taipei',
 'liechtenstein',
 'daily mail',
 'solan district',
 'goth',
 'british empire',
 'scholastic corporation',
 'ten pin bowling',
 'city university new york',
 'vinnytsia oblast',
 'centre national de la recherche scientifique',
 'opeth',
 'neuwied',
 'tampere',
 'international brigade',
 'north london',
 'serbian cyrillic alphabet',
 'northeastern ontario',
 'hackensack river',
 'old world warbler',
 'danish superliga',
 'niue',
 'puducherry',
 'namibia',
 'royal rumble',
 'atlantic league professional baseball',
 'bornholm',
 'alappuzha district',
 'spongebob squarepants',
 'royal caribbean international',
 'kim jong il',
 'keanu reef',
 'argentina national football team',
 'lloyd bacon',
 'annette andre',
 'british film institute',
 'second polish republic',
 'geology',
 'adventure film',
 'jeddah',
 'amitabh bachchan',
 'london school economics',
 'buryatia',
 'great purge',
 'bandai namco entertainment',
 'trojan war',
 'katy perry',
 'vincent van gogh',
 'disneyland paris',
 'islamism',
 'thor',
 'mersin',
 'clint eastwood',
 'bulgarian cup',
 'gauteng',
 'team17',
 'babur',
 'dili',
 'arabic literature',
 'traditional chinese character',
 'knight',
 'vadodara',
 'javanese language',
 'pope',
 'botany',
 'limehouse',
 'international security assistance force',
 'barranquilla',
 'met mother',
 'long island',
 'infantry',
 'developing country',
 'carmarthenshire',
 'province sweden',
 'minnesota wild',
 'roll royce limited',
 'county fermanagh',
 'steve ditko',
 'parthian empire',
 'toyota corolla',
 'great depression',
 'postage stamp',
 'napoleon iii',
 'university leicester',
 'master universe',
 'albert einstein',
 'patriotism',
 'international boxing organization',
 'massif central',
 'perennial plant',
 'fredric march',
 'malagasy language',
 'torah reading',
 'union navy',
 'nascar xfinity series',
 'tahiti',
 'lahore',
 'galois group',
 'key west',
 'john b',
 'nagoya',
 'surabaya',
 'ecumenical patriarch constantinople',
 'guadeloupe',
 'welsh government',
 'yugoslavia',
 'plain indian',
 'australian hip hop',
 'peerage scotland',
 'gambino crime family',
 'ice hockey',
 'australian defence force',
 'korean state railway',
 'monash university',
 'television channel',
 'italian renaissance',
 'hell',
 'fc porto',
 'south india',
 'government ireland',
 'legislative assembly ontario',
 'region southern denmark',
 'zagreb',
 'coahuila',
 'assyrian people',
 'percussion instrument',
 'tuam',
 'private university',
 'alicia key',
 'fox news',
 'aramaic',
 'quebec major junior hockey league',
 'osun state',
 'pablo picasso',
 'bangkok',
 'adriatic sea',
 'niger river',
 'local government area western australia',
 'lao',
 'carnatic music',
 'new mexico',
 'bangalore',
 'donald duck',
 'minister state',
 'royal college surgeon ireland',
 '3000 metre steeplechase',
 'lenape',
 'david weber',
 'tagalog language',
 'oklahoma sooner football',
 'university toronto',
 'paris foreign mission society',
 'directv',
 'hawthorn football club',
 'bromsgrove',
 'durham university',
 'badulla',
 'posix',
 'altai krai',
 'hmong people',
 'motown',
 'freestyle swimming',
 'kutaisi',
 'futurama',
 'thane',
 'order st michael st george',
 'royal college physician edinburgh',
 '20th century fox',
 'finland',
 'tina arena',
 'internet forum',
 'muromachi period',
 'county dublin',
 'meath gaa',
 'latvian higher league',
 'ecclesiastical latin',
 'spiritualism',
 'akb48',
 'vice president united state',
 'west germanic language',
 'tauranga',
 '1500 metre',
 'chukchi sea',
 'video game publisher',
 'al anbar governorate',
 'grozny',
 'bryan adam',
 'wwe network',
 'aube',
 'stephen hillenburg',
 'gascony',
 'rashtriya swayamsevak sangh',
 'abbasid caliphate',
 'bbc america',
 'reba mcentire',
 'singapore',
 'keio university',
 'antioquia department',
 'koine greek',
 'northern cyprus',
 'travel channel',
 'slade',
 'eastern europe',
 'university nottingham',
 'cinema philippine',
 'cumbernauld',
 'congregation christian brother',
 'montreux',
 'davis cup',
 'ulyanovsk oblast',
 'persian gulf',
 'planetary habitability',
 'centre right politics',
 'order ontario',
 'role playing video game',
 'dutch golden age painting',
 'herbaceous plant',
 'ba rhin',
 'physician',
 'gros de vaud district',
 'usb',
 'tom jerry',
 'mendoza province',
 'exeter chief',
 'cupressaceae',
 'book judge',
 'english study',
 'mysticism',
 'moravian silesian region',
 'volvo',
 'belarusian',
 'philippine basketball association',
 'sui dynasty',
 'dalai lama',
 'tigris',
 'rigveda',
 'political radicalism',
 'apocalyptic post apocalyptic fiction',
 'chinese folk religion',
 'trajan',
 'mark millar',
 'romeo juliet',
 'grand cayman',
 'witney',
 'palmerston north',
 'college board',
 'sam raimi',
 'berber',
 'def jam recording',
 'bahamas',
 'old irish',
 'stockholm municipality',
 'szeged',
 'london borough haringey',
 'ahvaz',
 'vilnius',
 'nanchang',
 'sarawak',
 'mainland china',
 'telugu language',
 'amazon river',
 'san francisco bay',
 'john baptist',
 'civil political right',
 'gaeltacht',
 'palatine hungary',
 'malacca',
 'sahara',
 'rascal flatts',
 'eastern wu',
 'steven spielberg',
 'university texas austin',
 'subroutine',
 'nelson rockefeller',
 'hiroshima',
 'w',
 'canterbury bankstown bulldog',
 'luhansk oblast',
 'gracillariidae',
 'mendip hill',
 'derbyshire',
 'free state prussia',
 'olympique de marseille',
 'la palma',
 'smolensk',
 'cuban revolution',
 'fa cup final',
 'distinguished service order',
 'luc besson',
 'mid north',
 'sarah jane adventure',
 'island record',
 'rice university',
 'thirteen colony',
 'treat williams',
 'riverside record',
 'greater western sydney',
 'babylon',
 'lleida',
 'department honduras',
 'volhynia',
 'guinness',
 'new york harbor',
 'gothic fiction',
 'world hockey association',
 'ganges',
 'ypres salient',
 'episcopal polity',
 'royal navy',
 'korn',
 'united state dollar',
 'minnesota twin',
 'prussian navy',
 'l',
 'vangelis',
 'virginia military institute',
 'northern ireland executive',
 'deccan plateau',
 'akira toriyama',
 'action adventure game',
 'progressive conservative party canada',
 'morobe province',
 'queensland',
 'miyagi prefecture',
 'senate philippine',
 'federico fellini',
 'australian national university',
 'rebellion',
 'biographical film',
 'lublin voivodeship',
 'louis xiv france',
 'united state declaration independence',
 'bremen',
 'duke aquitaine',
 'plymouth',
 'ian mcewan',
 'stephen king',
 'professional dart corporation',
 'international wrestling revolution group',
 'carnian',
 'tver oblast',
 'bhutan',
 'ringo starr',
 'algonquian language',
 'double bass',
 'ellesmere island',
 'albert pyun',
 'faith',
 'new york metropolitan area',
 'fc dallas',
 'olympique lyonnais',
 'edmonton',
 'braunschweig',
 'cieszyn county',
 'bill murray',
 'kingdom romania',
 'armoured warfare',
 'jagiellonian university',
 'swiss air force',
 'hawick',
 'poitier',
 'polish language',
 'middle tennessee',
 'jewish philosophy',
 'greek resistance',
 'mississauga',
 'south los angeles',
 'river state',
 'binghamton university',
 'boston red sox',
 'leeds rhino',
 'altai mountain',
 'piedmont triad',
 'nairobi',
 'east dunbartonshire',
 'hampton road',
 'hungarian revolution 1956',
 'social liberalism',
 'england cricket team',
 'actinopterygii',
 'downtown calgary',
 'greyhound racing united kingdom',
 'puntland',
 'sierra madre occidental',
 'parliament england',
 'streatham',
 'tampa bay viper',
 'tristan da cunha',
 'charles england',
 'president colombia',
 'riemannian geometry',
 'australian rule football',
 'english rugby union system',
 'twickenham',
 'felix cat',
 'university denver',
 'epiphyte',
 'wall street journal',
 'daraa',
 'lepidoptera',
 'lusitania',
 'eerste divisie',
 'columbidae',
 'cenozoic',
 'hillary clinton',
 'woody woodpecker',
 'oakland athletics',
 'lake district national park',
 'dnipropetrovsk oblast',
 'chemistry',
 'buffalo soldier',
 'local government republic ireland',
 'british indian army',
 'new orleans saint',
 'oxford english dictionary',
 'primera b nacional',
 'nfl europe',
 'nintendo switch',
 'oviedo',
 'larry niven',
 'hallmark channel',
 'sussex',
 'opus number',
 'arabian sea',
 'kranj',
 'scotland',
 'wexford senior hurling championship',
 'piraeus',
 'northern thailand',
 'toshiba',
 'alsace',
 'public university',
 'mahayana',
 'super furry animal',
 'mysore',
 '2015 pan american game',
 'indian super league',
 'maltese people',
 'cambuslang',
 'voivode',
 'carpathian ruthenia',
 'penang',
 'frank capra',
 'brandenburg prussia',
 'callichthyidae',
 'kumbakonam',
 'ames research center',
 'bananarama',
 'eastern shore virginia',
 'american reject',
 'landgraviate hesse kassel',
 'jihadism',
 'cathedral',
 'eastern bloc',
 'nvidia',
 'wim wenders',
 'philology',
 'ascot racecourse',
 'television philippine',
 'jersey',
 'archibald prize',
 'welsh rugby union',
 'fidel castro',
 'conceptual art',
 'south africa national rugby union team',
 'jet propulsion laboratory',
 'la estrellas',
 'broadway theatre',
 'university glasgow',
 'kingdom saxony',
 'wellington',
 'college justice',
 'newry',
 'greek mythology',
 'lecco',
 'boston university',
 'parliament victoria',
 'namie amuro',
 'u2',
 'greek war independence',
 'bacolod',
 'irish army',
 'maghreb',
 'pythonidae',
 'chile',
 'serbian superliga',
 'raphael',
 'spencer gulf',
 'harghita county',
 'morelos',
 'governor general canada',
 'music education',
 'downtown seattle',
 'real time computing',
 'london borough bromley',
 'world trade organization',
 'edmund goulding',
 'hanna barbera',
 'british classic race',
 'kansa city royal',
 'mumbai suburban railway',
 'mayor',
 'caryophyllaceae',
 'fawcett comic',
 'american hockey league',
 'tulane university',
 'bilateralism',
 'cannabis',
 'north sea',
 'andrew jackson',
 'african american neighborhood',
 'hokkaido railway company',
 'columbia university',
 'hellboy',
 'rijksmuseum',
 'jackson 5',
 'old testament',
 'scottish league two',
 'csx transportation',
 'porsche',
 'arecaceae',
 '2000 united state presidential election',
 'norman conquest england',
 'irish civil war',
 'cult',
 'islam',
 'rhodesia',
 'hesse',
 'paramaribo',
 'leicestershire',
 'doris lessing',
 'lake champlain',
 'huntingdon',
 'bengaluru fc',
 'grand duchy baden',
 'latvia',
 'american league championship series',
 'herodotus',
 'polygonaceae',
 'northwest territory',
 'spring autumn period',
 'metropolitan borough wigan',
 'hammersmith',
 'montreal canadiens',
 'leeds',
 'silverstone',
 'president argentina',
 'peshawar',
 'snorri sturluson',
 'rede globo',
 'comedy film',
 'cape good hope',
 'special air service',
 'archbishop canterbury',
 'voluntary association',
 'llandeilo',
 'rhine province',
 'city wakefield',
 'mindanao',
 'railway melbourne',
 'sergipe',
 'texas hill country',
 'united state soccer league system',
 'dionne warwick',
 'avignon',
 'region murcia',
 'elite ice hockey league',
 'historic county england',
 'grenada',
 'audioslave',
 'san francisco chronicle',
 'bukidnon',
 'fiji',
 'aaron kwok',
 'bridlington',
 'eurasia',
 'rhodes',
 'new jersey devil',
 'region france',
 'georgian architecture',
 ...]

### CountVectorizer

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
bag_of_words = count_vect.fit_transform(lemmatized_docs)
print("Bag of Words")

Bag of Words

In [11]:
query_vectors = count_vect.transform(lemmatized_queries)

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
similarities = cosine_similarity(query_vectors, bag_of_words)

In [13]:
from collections import defaultdict
from helper import Scoredoc

doc_dict = defaultdict(str)

for i, doc in enumerate(dataset.docs_iter()):
    doc_dict[i] = doc.doc_id

doc_dict = dict(doc_dict)

qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

score_doc_dict = dict(score_doc_dict)

print("necessary dicts ready!")

necessary dicts ready!

In [14]:
similarities

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.08944272, 0.02578553, ..., 0.        , 0.26432744,
        0.        ]], shape=(1444, 369721))

In [15]:
import pandas as pd
query_ids = [query.query_id for query in dataset.queries_iter()]
df = pd.DataFrame(query_ids, columns=["Query_ID"])
df

     Query_ID
0      123839
1      188629
2       13898
3      316959
4      515031
...       ...
1439   896124
1440    12319
1441     4421
1442   296526
1443   341793

[1444 rows x 1 columns]

In [16]:
from helper import create_AP, create_ndcg, create_statistical_columns
df = create_statistical_columns(df, qrels_dict, doc_dict, similarities)
df = create_AP(df, qrels_dict, doc_dict, similarities)
df = create_ndcg(df, doc_dict, similarities, score_doc_dict)

In [17]:
df

     Query_ID   recall_5   recall_10  ...     AP_10    NDCG_5   NDCG_10
0      123839  66.666667  100.000000  ...  0.873413  1.000000  1.000000
1      188629   0.000000   16.666667  ...  0.018519  0.568117  0.635398
2       13898   0.000000    0.000000  ...  0.000000  0.459385  0.405511
3      316959  11.111111   11.111111  ...  0.111111  0.860134  0.862121
4      515031   7.142857    7.142857  ...  0.017857  0.644618  0.483201
...       ...        ...         ...  ...       ...       ...       ...
1439   896124  12.500000   12.500000  ...  0.125000  0.438220  0.376262
1440    12319   4.545455    4.545455  ...  0.022727  0.195591  0.190641
1441     4421   0.000000    0.000000  ...  0.000000  0.288498  0.261849
1442   296526   0.000000   10.000000  ...  0.014286  0.364338  0.323567
1443   341793  14.285714   14.285714  ...  0.047619  0.466521  0.486405

[1444 rows x 11 columns]

In [18]:
mydict = {
    "Method": "Bag of Words - Lemmatization",
    "recall_5_mean": df["recall_5"].mean(),
    "recall_5_std": df["recall_5"].std(),
    "recall_5_max": df["recall_5"].max(),
    "recall_5_min": df["recall_5"].min(),
    "recall_10_mean": df["recall_10"].mean(),
    "recall_10_std": df["recall_10"].std(),
    "recall_10_max": df["recall_10"].max(),
    "recall_10_min": df["recall_10"].min(),
    "precision_5_mean": df["precision_5"].mean(),
    "precision_5_std": df["precision_5"].std(),
    "precision_5_max": df["precision_5"].max(),
    "precision_5_min": df["precision_5"].min(),
    "precision_10_mean": df["precision_10"].mean(),
    "precision_10_std": df["precision_10"].std(),
    "precision_10_max": df["precision_10"].max(),
    "precision_10_min": df["precision_10"].min(),
    "f_score_5_mean": df["f_score_5"].mean(),
    "f_score_5_std": df["f_score_5"].std(),
    "f_score_5_max": df["f_score_5"].max(),
    "f_score_5_min": df["f_score_5"].min(),
    "f_score_10_mean": df["f_score_10"].mean(),
    "f_score_10_std": df["f_score_10"].std(),
    "f_score_10_max": df["f_score_10"].max(),
    "f_score_10_min": df["f_score_10"].min(),
    "MAP_5": df["AP_5"].mean(),
    "MAP_10": df["AP_10"].mean(),
    "NDCG_5_mean": df["NDCG_5"].mean(),
    "NDCG_5_std": df["NDCG_5"].std(),
    "NDCG_5_max": df["NDCG_5"].max(),
    "NDCG_5_min": df["NDCG_5"].min(),
    "NDCG_10_mean": df["NDCG_10"].mean(),
    "NDCG_10_std": df["NDCG_10"].std(),
    "NDCG_10_max": df["NDCG_10"].max(),
    "NDCG_10_min": df["NDCG_10"].min()
}

In [19]:
df_parquet = pd.DataFrame(mydict, index=[0])
df_parquet

                         Method  recall_5_mean  ...  NDCG_10_max  NDCG_10_min
0  Bag of Words - Lemmatization      10.360816  ...          1.0          0.0

[1 rows x 35 columns]

In [20]:
df_parquet.to_parquet("BagofWordsLemmatization.parquet")
print("parquet")

parquet