In [1]:
import ir_datasets
from nltk.stem import WordNetLemmatizer
import nltk
from helper import create_tokenized_word_list

dataset = ir_datasets.load("wikir/en1k/training")
tokenized = create_tokenized_word_list(dataset)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
nltk.download("punkt_tab")
nltk.download("wordnet")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/tahas44/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
lemmatized_tokenized_docs = []
lematizer = WordNetLemmatizer()

for query_list in tokenized:
    lemmatized_words = [lematizer.lemmatize(word) for word in query_list]
    lemmatized_tokenized_docs.append(lemmatized_words)

print("Docs lemmatized")

Docs lemmatized

In [4]:
from helper import create_tokenized_word_list_for_query
query_tokenized = create_tokenized_word_list_for_query(dataset)
print("Queries tokenized!")

Queries tokenized!

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
lemmatized_tokenized_queries = []

for query_list in query_tokenized:
    lemmatized_words = [lematizer.lemmatize(words) for words in query_list]
    lemmatized_tokenized_queries.append(lemmatized_words)

print("Queries lemmatized")

Queries lemmatized

In [6]:
from rank_bm25 import BM25Okapi
bm25 = BM25Okapi(lemmatized_tokenized_docs)

In [7]:
scores_of_all_queries = []

for query in lemmatized_tokenized_queries:
    scores_of_all_queries.append(bm25.get_scores(query))

In [8]:
scores_of_all_queries

[array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 2.57180991, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([ 0.        ,  0.        , 11.54430976, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.43415237, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([4.88534099, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.73313215], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 1.75413388, ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 2.12032424,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 1.75413388, ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.92386784], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([2.03786929, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.73313215], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 2.03672634, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 2.80874403, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 1.75413388, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.       , 3.3138624, 0.       , ..., 0.       , 0.       ,
        0.       ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 1.75413388, ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([2.42362675, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([3.18276343, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.73313215], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.46520413, ..., 3.26950625, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 2.79739207, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 4.59421045, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 0.        , 1.08664881, ..., 0.        , 1.14408081,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.44711477], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 3.10363928, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 3.03534742, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.92386784], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 6.20074365, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 0.        , 1.75413388, ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        4.71685904], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 7.21933801, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 4.60858191,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        1.5838196], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 2.12032424,
        0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.62429075,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 7.16436186, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 2.79739207, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 5.02165227, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.46520413, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        1.5838196], shape=(369721,)),
 array([0.        , 2.79739207, 0.        , ..., 0.        , 0.        ,
        3.26047019], shape=(369721,)),
 array([4.12547846, 0.        , 5.46520413, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.84331914, ..., 0.        , 1.28538269,
        4.55001374], shape=(369721,)),
 array([0.        , 0.        , 1.75413388, ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([16.19601797,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([2.72968571, 3.3138624 , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 1.75413388, ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.62429075,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.18784908,
        0.        ], shape=(369721,)),
 array([2.35995965, 0.        , 1.58465995, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 1.71379207, ..., 1.7775282 , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.46520413, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 3.10363928, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([2.78831958, 0.        , 0.        , ..., 2.79868937, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 1.75413388, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.46520413, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 4.87552963,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.26047019], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 4.05406302, 2.54050617, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 1.86767451, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        5.69304625], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.92386784], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.78400501,
        1.77729542], shape=(369721,)),
 array([0.        , 2.39484835, 0.        , ..., 0.        , 0.        ,
        2.20570219], shape=(369721,)),
 array([0.        , 2.57180991, 0.        , ..., 0.        , 0.        ,
        5.69304625], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.78400501,
        1.77729542], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),

In [9]:
from collections import defaultdict
from helper import Scoredoc

doc_dict = defaultdict(str)

for i, doc in enumerate(dataset.docs_iter()):
    doc_dict[i] = doc.doc_id

doc_dict = dict(doc_dict)

qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

score_doc_dict = dict(score_doc_dict)

print("Necessary dicts created!")

Necessary dicts created!

In [10]:
query_ids = [query.query_id for query in dataset.queries_iter()]
query_ids

['123839',
 '188629',
 '13898',
 '316959',
 '515031',
 '123783',
 '4332',
 '9591',
 '114982',
 '563603',
 '104206',
 '1580851',
 '23678',
 '37480',
 '109454',
 '544250',
 '12519',
 '115015',
 '84287',
 '24998',
 '11925',
 '643',
 '113075',
 '1250387',
 '72012',
 '167865',
 '1425120',
 '24883',
 '27200',
 '136856',
 '6031',
 '1313191',
 '187115',
 '84110',
 '208234',
 '6431',
 '10799',
 '1417144',
 '32512',
 '677637',
 '97937',
 '113765',
 '12900',
 '1294909',
 '73745',
 '11692',
 '22173',
 '76662',
 '164301',
 '23344',
 '9367',
 '592217',
 '98546',
 '98175',
 '15189',
 '1256',
 '1815937',
 '1249076',
 '80274',
 '38489',
 '11311',
 '4754',
 '257711',
 '141668',
 '100895',
 '32945',
 '112321',
 '133725',
 '424464',
 '523456',
 '1327515',
 '12101',
 '9739',
 '189869',
 '143444',
 '78940',
 '12527',
 '327199',
 '7707',
 '97455',
 '1262433',
 '488875',
 '74026',
 '358108',
 '95179',
 '7862',
 '151797',
 '92980',
 '100876',
 '238228',
 '107755',
 '32539',
 '12953',
 '24843',
 '119528',
 '30765',
 '134772',
 '27711',
 '361260',
 '17874',
 '3524',
 '75902',
 '809894',
 '126362',
 '288208',
 '406254',
 '240663',
 '34848',
 '195113',
 '264822',
 '8387',
 '186363',
 '165761',
 '76875',
 '605155',
 '17836',
 '83566',
 '132697',
 '1563',
 '23924',
 '1433',
 '29737',
 '26758',
 '19717',
 '7870',
 '16093',
 '34844',
 '2234455',
 '382531',
 '12252',
 '11446',
 '21027',
 '1370698',
 '113657',
 '3348',
 '217425',
 '197576',
 '129397',
 '257126',
 '67592',
 '93136',
 '892237',
 '20605',
 '1219',
 '389032',
 '10656',
 '1778',
 '108160',
 '964897',
 '94266',
 '13744',
 '13539',
 '407598',
 '97620',
 '203795',
 '356090',
 '112731',
 '714608',
 '88181',
 '87960',
 '96791',
 '172084',
 '1836051',
 '14393',
 '1559299',
 '82801',
 '969771',
 '125685',
 '101336',
 '78856',
 '126985',
 '231130',
 '197161',
 '94693',
 '1339737',
 '273381',
 '73398',
 '179677',
 '90354',
 '1608685',
 '446634',
 '1595',
 '73102',
 '494392',
 '94832',
 '24349',
 '12374',
 '151391',
 '584158',
 '15282',
 '434927',
 '21969',
 '15987',
 '13776',
 '768304',
 '132575',
 '833105',
 '76345',
 '537',
 '181536',
 '4215',
 '17227',
 '97781',
 '1589',
 '119663',
 '1336894',
 '1568489',
 '133700',
 '147768',
 '674995',
 '1047896',
 '6368',
 '172053',
 '1045273',
 '80687',
 '1263864',
 '81739',
 '113925',
 '73285',
 '27399',
 '35101',
 '5570',
 '14758',
 '10792',
 '726995',
 '17814',
 '908',
 '85435',
 '79941',
 '140552',
 '145807',
 '107616',
 '13801',
 '357261',
 '34865',
 '2259',
 '6213',
 '72576',
 '163527',
 '75654',
 '29687',
 '1283640',
 '1703622',
 '324633',
 '37756',
 '1237543',
 '342167',
 '1058358',
 '248154',
 '330931',
 '163736',
 '488869',
 '20603',
 '8055',
 '109832',
 '9332',
 '204974',
 '339255',
 '22113',
 '94641',
 '10825',
 '71636',
 '2078947',
 '146007',
 '11481',
 '1282373',
 '605568',
 '276580',
 '190225',
 '26652',
 '14325',
 '23815',
 '119102',
 '17755',
 '29896',
 '26093',
 '1272415',
 '94442',
 '260160',
 '152382',
 '883324',
 '71191',
 '178216',
 '1408773',
 '6047',
 '1410732',
 '37218',
 '22295',
 '12601',
 '15200',
 '14027',
 '545390',
 '81411',
 '1324050',
 '8669',
 '21961',
 '612261',
 '389274',
 '39839',
 '90512',
 '185712',
 '302505',
 '2623',
 '1343759',
 '725960',
 '5554',
 '180826',
 '22170',
 '203549',
 '270009',
 '110384',
 '296861',
 '6835',
 '19342',
 '18363',
 '226344',
 '37955',
 '19145',
 '14445',
 '605066',
 '2228',
 '2613',
 '1742574',
 '28296',
 '100963',
 '561358',
 '13460',
 '85285',
 '4925',
 '104339',
 '183397',
 '156457',
 '284',
 '34937',
 '76048',
 '164182',
 '411597',
 '422208',
 '3522',
 '73430',
 '113428',
 '9399',
 '2243',
 '157351',
 '2842',
 '377416',
 '4855',
 '4397',
 '1846628',
 '75969',
 '635597',
 '2581',
 '20437',
 '76039',
 '9356',
 '22213',
 '1250',
 '70969',
 '1349',
 '6644',
 '103434',
 '384474',
 '1669212',
 '596568',
 '98507',
 '128283',
 '815972',
 '5816',
 '1344825',
 '11029',
 '82288',
 '639167',
 '80536',
 '254180',
 '97274',
 '4722',
 '159099',
 '25706',
 '104011',
 '6033',
 '14011',
 '4616',
 '6482',
 '310032',
 '25193',
 '27720',
 '21972',
 '633954',
 '37908',
 '1870966',
 '487985',
 '105462',
 '510206',
 '7560',
 '12705',
 '117619',
 '305484',
 '1090430',
 '1777480',
 '1268117',
 '1289085',
 '1338779',
 '1817436',
 '24242',
 '20898',
 '16880',
 '37945',
 '4085',
 '2130523',
 '18091',
 '19675',
 '78817',
 '5400',
 '32411',
 '1322',
 '188952',
 '4720',
 '25242',
 '763957',
 '84315',
 '107129',
 '7407',
 '83325',
 '526775',
 '5204',
 '1787',
 '112402',
 '92302',
 '2986',
 '161918',
 '71995',
 '18192',
 '85636',
 '26444',
 '6390',
 '134543',
 '923020',
 '834741',
 '184241',
 '88748',
 '391276',
 '8899',
 '26219',
 '8938',
 '166642',
 '24861',
 '1352',
 '16006',
 '473460',
 '210583',
 '75859',
 '6879',
 '152885',
 '238499',
 '473275',
 '196310',
 '5896',
 '5002',
 '226743',
 '110572',
 '543',
 '26103',
 '208058',
 '68416',
 '895072',
 '12773',
 '1182701',
 '13957',
 '28752',
 '6227',
 '119284',
 '273555',
 '17203',
 '609350',
 '117495',
 '1641154',
 '1705',
 '19435',
 '154661',
 '108269',
 '7026',
 '165900',
 '131685',
 '9643',
 '1515',
 '34957',
 '88458',
 '152413',
 '479595',
 '7647',
 '6264',
 '29411',
 '75908',
 '71994',
 '27795',
 '704769',
 '2274',
 '12626',
 '639949',
 '207327',
 '1274160',
 '10688',
 '24454',
 '128712',
 '181363',
 '80',
 '10413',
 '120973',
 '145081',
 '206583',
 '24782',
 '1365055',
 '317887',
 '740767',
 '73024',
 '25238',
 '56872',
 '5219',
 '42749',
 '1444121',
 '24145',
 '93598',
 '24066',
 '5065',
 '123063',
 '14451',
 '301383',
 '197016',
 '141405',
 '159773',
 '6138',
 '26051',
 '1712787',
 '73768',
 '12699',
 '121064',
 '681120',
 '81877',
 '197769',
 '173023',
 '194810',
 '370139',
 '21892',
 '77940',
 '108305',
 '10456',
 '243438',
 '352646',
 '23335',
 '4559',
 '762',
 '95338',
 '422214',
 '10221',
 '22149',
 '1403468',
 '9022',
 '70754',
 '7353',
 '79109',
 '9106',
 '2032420',
 '1270810',
 '102991',
 '366863',
 '750376',
 '98133',
 '1194068',
 '13415',
 '764844',
 '849899',
 '448622',
 '927392',
 '1063349',
 '128187',
 '1614640',
 '477200',
 '9748',
 '157369',
 '22800',
 '80219',
 '1403378',
 '146323',
 '97591',
 '80765',
 '125608',
 '351608',
 '81103',
 '4334',
 '21439',
 '113621',
 '90496',
 '2547',
 '488858',
 '217759',
 '189034',
 '90382',
 '814731',
 '14032',
 '75643',
 '1662573',
 '479233',
 '187769',
 '38035',
 '155722',
 '70941',
 '88077',
 '1683175',
 '30883',
 '289837',
 '28823',
 '34394',
 '19625',
 '110332',
 '92668',
 '11644',
 '133621',
 '86063',
 '1731034',
 '109201',
 '236830',
 '86499',
 '15015',
 '1467096',
 '518649',
 '1529682',
 '389454',
 '20213',
 '97540',
 '159101',
 '10524',
 '466077',
 '374708',
 '135038',
 '129387',
 '593570',
 '99196',
 '32938',
 '9755',
 '1421273',
 '13706',
 '226734',
 '100123',
 '1640988',
 '133233',
 '1608',
 '1264172',
 '1594725',
 '157511',
 '13850',
 '15277',
 '131074',
 '17237',
 '3249',
 '13326',
 '1814473',
 '1156870',
 '25280',
 '323708',
 '13016',
 '222183',
 '10968',
 '109940',
 '129732',
 '118690',
 '179517',
 '12198',
 '19019',
 '434541',
 '1248',
 '319553',
 '252889',
 '138439',
 '35022',
 '182032',
 '13954',
 '136151',
 '12030',
 '21583',
 '15741',
 '489',
 '11435',
 '6649',
 '14868',
 '37861',
 '248820',
 '1727920',
 '121664',
 '377463',
 '110662',
 '11420',
 '13685',
 '1685919',
 '1274158',
 '23083',
 '14139',
 '166211',
 '161907',
 '721863',
 '110381',
 '27264',
 '672596',
 '161341',
 '114943',
 '37957',
 '108695',
 '479110',
 '129109',
 '16266',
 '399420',
 '759288',
 '34119',
 '10963',
 '14608',
 '283712',
 '266655',
 '203968',
 '1313526',
 '7836',
 '119662',
 '140457',
 '1276229',
 '110281',
 '5195',
 '100816',
 '5103',
 '429845',
 '4088',
 '11072',
 '17962',
 '1254149',
 '8394',
 '305914',
 '665122',
 '13888',
 '126682',
 '133726',
 '154029',
 '1116',
 '172058',
 '55300',
 '374325',
 '23079',
 '2120001',
 '114890',
 '4831',
 '111289',
 '165585',
 '214810',
 '126571',
 '7755',
 '13630',
 '918270',
 '83187',
 '9865',
 '122086',
 '11428',
 '314278',
 '1062661',
 '503034',
 '155036',
 '446428',
 '10976',
 '20434',
 '3544',
 '25445',
 '717881',
 '71381',
 '117555',
 '682338',
 '245828',
 '35568',
 '20021',
 '606000',
 '38408',
 '114257',
 '332492',
 '15319',
 '229404',
 '5781',
 '20183',
 '9603',
 '192096',
 '79820',
 '411516',
 '77789',
 '1313521',
 '388950',
 '109985',
 '1585',
 '264823',
 '22226',
 '164723',
 '9041',
 '71649',
 '88210',
 '128218',
 '212288',
 '211013',
 '79',
 '438884',
 '1099352',
 '99045',
 '274498',
 '134029',
 '35023',
 '2402726',
 '13373',
 '2938',
 '103786',
 '88775',
 '809',
 '1032451',
 '35036',
 '89567',
 '170548',
 '22672',
 '82044',
 '123639',
 '20906',
 '7769',
 '385089',
 '24704',
 '2266',
 '677582',
 '90428',
 '9454',
 '211320',
 '161909',
 '1964',
 '115785',
 '409207',
 '232564',
 '9137',
 '9492',
 '497039',
 '78081',
 '2070217',
 '77289',
 '7611',
 '235972',
 '19574',
 '70946',
 '956',
 '179671',
 '11448',
 '805510',
 '36957',
 '228293',
 '23327',
 '19017',
 '344485',
 '1558158',
 '76587',
 '26910',
 '1148665',
 '1932345',
 '555050',
 '121447',
 '73560',
 '151629',
 '23266',
 '4647',
 '101622',
 '112935',
 '27673',
 '18788',
 '32955',
 '242902',
 '90776',
 '105401',
 '843489',
 '18207',
 '36683',
 '15712',
 '14076',
 '9681',
 '219237',
 '1031987',
 '6502',
 '106031',
 '225142',
 '15420',
 '84194',
 '133570',
 '6815',
 '1357000',
 '205081',
 '15850',
 '197853',
 '14293',
 '457924',
 '128345',
 '1407356',
 '103335',
 '23918',
 '269840',
 '161933',
 '20681',
 '90437',
 '114728',
 '129948',
 '126860',
 '9765',
 '2113',
 '748790',
 '17645',
 '120677',
 '108913',
 '88958',
 '15351',
 '396742',
 '182986',
 '10946',
 '35538',
 '14314',
 '479034',
 '22120',
 '488649',
 '7022',
 '133309',
 '37830',
 '102670',
 '233552',
 '92119',
 '79532',
 '146760',
 '15425',
 '8877',
 '448',
 '1117181',
 '132661',
 '2473',
 '164285',
 '11145',
 '1407349',
 '9379',
 '1909580',
 '111964',
 '10329',
 '18137',
 '13676',
 '26442',
 '6326',
 '75046',
 '746557',
 '11138',
 '15463',
 '22402',
 '23936',
 '32442',
 '7607',
 '103543',
 '1900776',
 '1973651',
 '7276',
 '1387',
 '5590',
 '9780',
 '8882',
 '81156',
 '189807',
 '87882',
 '17047',
 '864775',
 '167358',
 '97923',
 '25611',
 '1407055',
 '213595',
 '2175',
 '17512',
 '21907',
 '781',
 '1584920',
 '187188',
 '358658',
 '189862',
 '8610',
 '239821',
 '97945',
 '119644',
 '337441',
 '80187',
 '15355',
 '1310225',
 '254991',
 '91502',
 '1205882',
 '88824',
 '120183',
 '106926',
 '4383',
 '272146',
 '127768',
 '1313596',
 '1522224',
 '25771',
 '23005',
 '5326',
 ...]

In [11]:
from collections import defaultdict

query_id_vs_text = defaultdict(str)

for query in dataset.queries_iter():
    query_id_vs_text[query.query_id] = query.text

In [12]:
import numpy as np
query_id_and_its_doc = defaultdict(list)

for i in range(len(query_ids)):
    found_doc_list = []
    similarity = scores_of_all_queries[i]

    index_of_found_docs = np.where(similarity > 0)[0]

    for index in list(index_of_found_docs):
        found_doc_list.append((similarity[index], doc_dict[index]))

    if len(found_doc_list) <= 10:
        for mytuple in found_doc_list:
            query_id_and_its_doc[query_ids[i]].append(mytuple[1])
    else:
        for mytuple in sorted(found_doc_list, reverse=True):
            query_id_and_its_doc[query_ids[i]].append(mytuple[1])

            if len(query_id_and_its_doc[query_ids[i]]) == 10:
                break

In [13]:
query_id_and_its_doc

defaultdict(list,
            {'123839': ['806300',
              '123839',
              '806326',
              '836567',
              '806075',
              '1793430',
              '806263',
              '799188',
              '1727316',
              '1901730'],
             '188629': ['188629',
              '2185399',
              '2191096',
              '2304431',
              '1046396',
              '1990307',
              '2296288',
              '533438',
              '2290269',
              '221705'],
             '13898': ['13898',
              '2213954',
              '1921403',
              '2108627',
              '1874948',
              '525283',
              '2216860',
              '2248373',
              '1440180',
              '1698181'],
             '316959': ['316959',
              '348869',
              '1836641',
              '2156815',
              '930698',
              '1326263',
              '2215542',
              '1525222',
              '1457673',
              '1294742'],
             '515031': ['887826',
              '832086',
              '1842084',
              '1176215',
              '1569953',
              '1376470',
              '515031',
              '836749',
              '1125994',
              '888195'],
             '123783': ['1210005',
              '1209576',
              '1209561',
              '2200269',
              '1675282',
              '123783',
              '1630942',
              '579503',
              '2260318',
              '810375'],
             '4332': ['4332',
              '1516841',
              '989116',
              '1815319',
              '1863594',
              '1090555',
              '1442076',
              '1991105',
              '816040',
              '1196898'],
             '9591': ['908435',
              '138626',
              '2416624',
              '390102',
              '1898638',
              '2250838',
              '143444',
              '1966629',
              '1483036',
              '1759147'],
             '114982': ['1341103',
              '2444081',
              '1191721',
              '917379',
              '2305216',
              '2305139'],
             '563603': ['390174',
              '2207107',
              '373237',
              '12846',
              '349302',
              '563603',
              '394294',
              '270469',
              '1233547',
              '219324'],
             '104206': ['104018',
              '2096056',
              '1673999',
              '1281151',
              '1858334',
              '200511',
              '149391',
              '985149',
              '1858542',
              '1972988'],
             '1580851': ['1549040',
              '1528190',
              '1580851',
              '2187550',
              '1126483',
              '2218736',
              '2279707',
              '1298253',
              '1255868',
              '461900'],
             '23678': ['23678',
              '1708807',
              '1537291',
              '1815535',
              '349822',
              '2200763',
              '1771004',
              '608269',
              '342272',
              '936323'],
             '37480': ['246157',
              '77763',
              '1017336',
              '154685',
              '702790',
              '1589436',
              '845773',
              '1027733',
              '1571906',
              '305953'],
             '109454': ['109454',
              '2045342',
              '1450070',
              '2100641',
              '2069260',
              '1280868',
              '1746976',
              '1648909',
              '82801',
              '702222'],
             '544250': ['544250',
              '2095411',
              '682657',
              '1937433',
              '630265',
              '1322312',
              '2347517',
              '730726',
              '1880207',
              '2012111'],
             '12519': ['1374322',
              '1091625',
              '869618',
              '1005711',
              '1739665',
              '12519',
              '82510',
              '2264749',
              '943622',
              '175050'],
             '115015': ['2202113',
              '1351327',
              '115015',
              '1978384',
              '2133651',
              '458160',
              '1591706',
              '2315210',
              '2215175',
              '1290856'],
             '84287': ['189580',
              '1095591',
              '1422745',
              '1571607',
              '1427890',
              '891543',
              '1907688',
              '84287',
              '1308897',
              '2332777'],
             '24998': ['1409082',
              '2149920',
              '1394401',
              '1941659',
              '2339264',
              '1323056',
              '917063',
              '59107',
              '1553086',
              '2407468'],
             '11925': ['580492',
              '1148523',
              '2108567',
              '975838',
              '232799',
              '2207088',
              '555629',
              '1355039',
              '1687991',
              '1595836'],
             '643': ['1115256',
              '643',
              '1769441',
              '88810',
              '33435',
              '2246138',
              '1495790',
              '1892260',
              '1786083',
              '143150'],
             '113075': ['113075',
              '100596',
              '21628',
              '1217819',
              '1733437',
              '572485',
              '344421',
              '1704209',
              '1043682',
              '2334418'],
             '1250387': ['1727869',
              '2195293',
              '297902',
              '1683108',
              '599253',
              '1207201',
              '1250387',
              '2217046',
              '1589325',
              '1133175'],
             '72012': ['72012',
              '111443',
              '103174',
              '111938',
              '191745',
              '2371473',
              '111442',
              '863599',
              '1806360',
              '496440'],
             '167865': ['167865',
              '385342',
              '1964134',
              '221442',
              '1846426',
              '2229172',
              '299025',
              '1303512',
              '737868',
              '1820245'],
             '1425120': ['2316655',
              '1083694',
              '836205',
              '1737940',
              '1425120',
              '2198169',
              '12523',
              '546380',
              '2348752',
              '2147182'],
             '24883': ['24883',
              '1394026',
              '2172776',
              '2393527',
              '1877437',
              '1734607',
              '2355895',
              '647047',
              '2178291',
              '1603081'],
             '27200': ['923643',
              '1833536',
              '1834661',
              '148043',
              '1352641',
              '2389598',
              '1493043',
              '1750849',
              '2314961',
              '292569'],
             '136856': ['136856',
              '1445582',
              '2272554',
              '2037574',
              '817838',
              '2312312',
              '2059311',
              '506684',
              '2444515',
              '357239'],
             '6031': ['123675',
              '117413',
              '975229',
              '23531',
              '1466349',
              '1298646',
              '306781',
              '1620199',
              '623176',
              '101000'],
             '1313191': ['1313191',
              '94675',
              '216370',
              '1641900',
              '1198513',
              '443142',
              '2158753',
              '840735',
              '933159',
              '1797855'],
             '187115': ['187115',
              '1464470',
              '975998',
              '1012100',
              '964282',
              '2449992',
              '70941',
              '2246466',
              '1301843',
              '2442546'],
             '84110': ['1924159',
              '1670119',
              '1395090',
              '1987297',
              '1936088',
              '1935764',
              '2087053',
              '1052069',
              '1275995',
              '306509'],
             '208234': ['208234',
              '263739',
              '1685838',
              '1629265',
              '795404',
              '1697013',
              '1665946',
              '423289',
              '1011406',
              '505721'],
             '6431': ['6431',
              '5400',
              '32256',
              '713517',
              '273681',
              '556999',
              '603672',
              '336647',
              '510840',
              '872358'],
             '10799': ['10799',
              '313344',
              '242372',
              '1439685',
              '1294553',
              '164172',
              '1415399',
              '684799',
              '2322567',
              '635234'],
             '1417144': ['2168362',
              '1593467',
              '1599859',
              '1122564',
              '1077838',
              '2077423',
              '1008029',
              '424500',
              '491879',
              '1861636'],
             '32512': ['827758',
              '2052704',
              '1454938',
              '1975061',
              '168470',
              '4128',
              '1135484',
              '1990265',
              '28484',
              '758040'],
             '677637': ['1797233',
              '1364109',
              '1214837',
              '311557',
              '122359',
              '322640',
              '424385',
              '1102365',
              '1577989',
              '677637'],
             '97937': ['1096276',
              '1604490',
              '902154',
              '1383368',
              '2130224',
              '1885628',
              '2391516',
              '1206431',
              '2226421',
              '2194096'],
             '113765': ['557100',
              '1132759',
              '1807222',
              '1276605',
              '624238',
              '1737172',
              '707880',
              '1697156',
              '445999',
              '1714965'],
             '12900': ['925414',
              '379149',
              '171087',
              '2315670',
              '1150042',
              '889438',
              '984273',
              '405319',
              '326390',
              '740408'],
             '1294909': ['140477',
              '127179',
              '1395726',
              '1437752',
              '2413308',
              '1076256',
              '160522',
              '129833',
              '2056552',
              '75643'],
             '73745': ['144080',
              '73745',
              '238326',
              '555598',
              '55300',
              '80609',
              '179605',
              '941681',
              '231320',
              '881619'],
             '11692': ['11692',
              '1869155',
              '2158113',
              '1789375',
              '938197',
              '1664266',
              '186017',
              '212300',
              '1471707',
              '378055'],
             '22173': ['22173',
              '1996894',
              '2451809',
              '2333975',
              '1652701',
              '1481423',
              '1405463',
              '1081052',
              '2296579',
              '161142'],
             '76662': ['1508270',
              '765779',
              '1503801',
              '848651',
              '2215345',
              '2261937',
              '2422497',
              '1335769',
              '1676360',
              '749253'],
             '164301': ['2352467',
              '674438',
              '614691',
              '414892',
              '163054',
              '139800',
              '1703770',
              '1791930',
              '1426820',
              '169941'],
             '23344': ['23344',
              '2176190',
              '2063227',
              '1911804',
              '2448301',
              '1865562',
              '2093481',
              '1192138',
              '2002375',
              '420936'],
             '9367': ['1080010',
              '1942436',
              '1014015',
              '2377011',
              '613453',
              '833316',
              '1920332',
              '2321702',
              '1920437',
              '945729'],
             '592217': ['592217',
              '728912',
              '2371077',
              '1932439',
              '350482',
              '901650',
              '419529',
              '722653',
              '2014806',
              '2446809'],
             '98546': ['98546',
              '630445',
              '1651627',
              '888182',
              '1876890',
              '2016946',
              '2165734',
              '869968',
              '2164008',
              '329702'],
             '98175': ['98175',
              '1863235',
              '1514310',
              '1824993',
              '105110',
              '1476590',
              '1562537',
              '1377443',
              '576789',
              '1634510'],
             '15189': ['124228',
              '15189',
              '1942441',
              '2402251',
              '557967',
              '1638193',
              '1423601',
              '1903962',
              '465902',
              '84799'],
             '1256': ['876761',
              '113333',
              '1235263',
              '538932',
              '271822',
              '2440176',
              '1256',
              '2157777',
              '2314072',
              '2311645'],
             '1815937': ['1815937',
              '243805',
              '2289785',
              '2086664',
              '565326',
              '204845',
              '10342',
              '1275085',
              '850359',
              '247379'],
             '1249076': ['776649',
              '148739',
              '1249076',
              '582125',
              '271184',
              '1218390',
              '597808',
              '1404931',
              '117077',
              '577424'],
             '80274': ['849206',
              '150130',
              '340664',
              '80274',
              '176310',
              '304719',
              '716455',
              '405231',
              '2035264',
              '1873712'],
             '38489': ['461229',
              '1130473',
              '282393',
              '2390162',
              '1845290',
              '585857',
              '2441739',
              '1222036',
              '992021',
              '2310760'],
             '11311': ['1971400',
              '2445017',
              '2335274',
              '1513312',
              '11811',
              '2445229',
              '2299615',
              '1485803',
              '77619',
              '2195076'],
             '4754': ['4754',
              '1096243',
              '2015409',
              '236496',
              '1194767',
              '553733',
              '547188',
              '2356140',
              '2149205',
              '1938630'],
             '257711': ['357261',
              '257711',
              '1484995',
              '825222',
              '1347610',
              '1628781',
              '300746',
              '408205',
              '158574',
              '496318'],
             '141668': ['1238621',
              '1722747',
              '395221',
              '165351',
              '1914607',
              '1958630',
              '954750',
              '1062897',
              '753613',
              '2148663'],
             '100895': ['100895',
              '1673670',
              '2077781',
              '1137894',
              '2357750',
              '551090',
              '232851',
              '414800',
              '1511933',
              '558572'],
             '32945': ['32945',
              '2282975',
              '30883',
              '661736',
              '781080',
              '1304274',
              '2026880',
              '583542',
              '2096142',
              '1445894'],
             '112321': ['112321',
              '8105',
              '956494',
              '2095641',
              '1101174',
              '722441',
              '492372',
              '1852415',
              '2187',
              '107590'],
             '133725': ['133725',
              '6502',
              '73573',
              '2123315',
              '1959279',
              '415845',
              '449439',
              '1014143',
              '9140',
              '176330'],
             '424464': ['1487470', '18386', '424464', '663519'],
             '523456': ['1111392',
              '524668',
              '523456',
              '1124756',
              '1077052',
              '341506',
              '1597524',
              '414850',
              '114881',
              '1097635'],
             '1327515': ['2288752',
              '1327515',
              '2156783',
              '1926176',
              '1537119',
              '952689',
              '2194210',
              '1715843',
              '1505058',
              '1412780'],
             '12101': ['859022',
              '2140400',
              '1602439',
              '1815846',
              '1836521',
              '138606',
              '350923',
              '1939375',
              '1436095',
              '1939353'],
             '9739': ['274722',
              '1096838',
              '1024639',
              '1375473',
              '370163',
              '9739',
              '1949261',
              '1912766',
              '706941',
              '473870'],
             '189869': ['367496',
              '128794',
              '134672',
              '1324666',
              '142177',
              '298520',
              '1142186',
              '132340',
              '2127341',
              '189807'],
             '143444': ['390102',
              '143444',
              '1363154',
              '1719779',
              '760591',
              '619180',
              '654690',
              '1595491',
              '6490',
              '1284955'],
             '78940': ['400988',
              '1225575',
              '2187325',
              '400966',
              '663857',
              '663465',
              '78940',
              '1519096',
              '129940',
              '273488'],
             '12527': ['2428193',
              '12527',
              '1557331',
              '1263830',
              '2421049',
              '1555649',
              '85080',
              '756172',
              '462386',
              '108457'],
             '327199': ['1121851',
              '2431271',
              '327199',
              '163489',
              '446190',
              '1475136',
              '824648',
              '40891',
              '2201943',
              '739227'],
             '7707': ['7707',
              '607670',
              '662426',
              '2431336',
              '1450844',
              '2307061',
              '86731',
              '2080398',
              '2024588',
              '1330041'],
             '97455': ['931552',
              '193928',
              '355309',
              '390447',

In [14]:
doc_id_vs_text = defaultdict(str)

for doc in dataset.docs_iter():
    doc_id_vs_text[doc.doc_id] = doc.text

In [15]:
import gc 
del dataset
del tokenized
del lematizer
del lemmatized_tokenized_docs
del lemmatized_tokenized_queries
del lemmatized_words
del query_tokenized
del bm25
gc.collect()

0

In [16]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for doc_id in query_id_and_its_doc[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

In [17]:
query_doc_pairs["123839"]

[('yanni',
  'it is a compilation of tracks from his five previous studio albums released between 1980 and 1989 plus three new compositions yanni was encouraged to release the album by his then partner actress linda evans reflections of passion became yanni s fastest selling and most successful album of his career upon release it reached no 1 on the billboard top new age albums chart and no 29 on the billboard 200 yanni supported the album with a nationwide concert tour in 1990 that featured his band and an orchestra in 1995 it was certified double platinum for selling 2 million copies in the us in august 1989 yanni released his fifth studio album niki nana the album marked his stylistic development from solo keyboard music towards rock with the addition of additional vocalists musicians and choir around the same time of its release yanni s newfound relationship with american actress linda evans who had become a fan of his music received press attention not long into their relationship evans pitched an idea she had for an album from yanni which was long in duration reflected a single mood throughout and something that she could play at dinner parties she mentioned'),
 ('yanni',
  'although this genre of music was not well suited for commercial pop radio and music television yanni received international recognition by producing concerts at historic monuments and by producing videos that were broadcast on public television his breakthrough concert live at the acropolis yielded the second best selling music concert video of all time additional historic sites for yanni s concerts have included india s taj mahal china s forbidden city the united arab emirates burj khalifa russia s kremlin puerto rico s el morro castle lebanon s ancient city of byblos tunisia s roman theatre of carthage india s laxmi vilas palace the egyptian pyramids and great sphinx of giza and the amman citadel at least sixteen of yanni s albums have peaked at no 1 in billboard s top new age album category and two albums dare to dream and in my time received grammy award nominations yanni has performed in more than 30 countries on five continents and through late 2015 yanni had performed live in concert before more than 5 million people and had accumulated more than 40 platinum and gold albums globally with sales totaling over 25 million copies a longtime fundraiser for public television'),
 ('yanni',
  'the album peaked at no 1 on billboard s top new age album chart and at no 21 on the billboard 200 chart in the same year the corresponding concert tour in 1998 was the tribute world tour 1998 tribute pays musical homage to india on several songs greek born composer and keyboardist yanni describes the album as a tribute to the builders of the taj and the forbidden city as well as to the people of india and china yanni s ethereal keyboard work is backed by orchestra vocalists a choir and various world instruments including didgeridoo duduk charango and bamboo saxophone yanni hired armen anassian as conductor on faith as he had never watched him conduct an orchestra that s how yanni does many things anassian said in a 1998 interview with the toledo blade anassian concedes that he had some doubts about the artist s plans to perform at india s taj mahal and china s forbidden city for tribute to be honest a few years ago when he was talking about it the idea was so amazing i myself was very skeptical understandably so but the truth is it happened we did it anassian said the'),
 ('yanni',
  'adams was born in joliet illinois band members of regional rock band chameleon included adams on drums vocals and percussion yanni on keyboards and synthesizers dugan mcneill on lead vocals and bass guitars johnny donaldson on all guitars and mark anthony on lead vocals and keyboards their albums included chameleon techno color hologram sky and balance the group was noted for adams revolving gyroscope drum kit who played his rapidly spinning drums before m tley cr e s tommy lee s similar arrangement in 1987 yanni was putting together his first touring band to promote his album out of silence as well as selections from keys to imagination this early band included yanni john tesh and joyce imbesi on keyboards and adams on drums adams is widely recognized for his drum solo on the live at the acropolis concert film he is also featured in the live at royal albert hall released in 1995 when yanni staged his tribute concerts in 1996 1997 adams did not join him as he had to stay back in the united states to deal with issues on his son s autism and help raise him joel taylor became the substitute drummer for the said'),
 ('yanni',
  'it was recorded at the herodes atticus theatre in athens greece during his 1993 tour in support of his eighth studio album in my time 1993 the concert took a year and a half to organise and cost yanni 2 million of his own money to fund he performs with his six piece band and the royal philharmonic orchestra conducted by shahrdad rohani the album was mixed and produced by yanni in his studio and was made into a television special which aired in the united states on public broadcasting service pbs live at the acropolis received a mostly positive reception from music critics it was an instant commercial success reaching number one on the billboard new age albums chart and number 5 on the billboard 200 it remains yanni s highest selling release with 4 million albums and 600 000 home videos sold in the united states and an estimated 7 million copies sold worldwide in 1994 the video received a primetime emmy award nomination for outstanding individual achievement in lighting direction electronic for a drama series variety series miniseries or a special a remastered edition with bonus material to commemorate the album s 25th anniversary was released in'),
 ('yanni',
  'the two concerts were performed outdoors on the grounds of el morro castle in san juan puerto rico in december 2011 the cd peaked at 1 on billboard s new age album list in both 2012 and 2013 live at el morro puerto rico was recorded and filmed during two sold out concerts performed outdoors on december 16 and 17 2011 on the grounds of the castillo san felipe del morro el morro a unesco world heritage site in the old san juan yanni had reportedly planned for twenty years to perform at the historic site yanni explained that two concerts were planned for friday and saturday night with the ensuing sunday being a contingent rain day it reportedly rained for 25 days in a row preceding the first night s concert on friday and the first concert itself was interrupted and eventually cut short three quarters of the way through by rain and wind causing danger for the outdoor performance the evening of the second show saturday the weather was better and the show was completed as planned yanni said that 35 cameras and three live camera operators were able to capture the show departing the island on sunday'),
 ('yanni',
  'its corresponding concert tour was the 1987 concert series the liner notes dedicate the album to his homeland in kalamata greece respectively dedicated to the town of kalamata greece which stood strong and waited for me one last time the album was reissued in 2009 by valley entertainment in a review by william ruhlmann of allmusic yanni s second album like his first keys to imagination was recorded entirety on synthesizers at his home studio the composer performer makes extensive use of the orchestral possibilities of electronics creating big themes to play across elaborate echoing rhythm tracks unlike much adult alternative music it s constantly stimulating foreground music with an extremely modern sound 1987 selections from keys to imagination and out of silence it was during this year that yanni was putting together his first touring band to promote his album out of silence as well as selections from keys to imagination although i d written as always with an orchestra in mind i couldn t afford one so i reproduced that sound in my studio with my synthesizers but because i wanted to play everything live onstage and not against tape i needed three keyboard players and a drummer'),
 ('yanni',
  'singles from the album included rabba released in 2003 and sajan released in 2004 the tunes on sampooran were written incorporating traditional material from the eastern classical tradition and adapting these with music which was based on the jazz rock fusion explosion of the seventies it possesses arguably the finest musical arrangements that have ever been experienced in the country and the compositions really light up the album the album starts with the lukewarm sajan whose lyrics have been taken from a kaafi written by shah hussain a moderate mix of acoustic guitars and percussion and some sweet flute playing renders this a really good opening track waris shah is next with its yanni isque musical intonations and lyrics inspired from texts by amrita preetam the album seems to be getting into a groove as the vocals start getting tuned up and the music gets more and more passionate a classically inspired flute arrangement mixed with soft bass drums and javed bashir does total justice with the lyrics the song has probably lingered on a bit and some pieces seem a bit lengthy but overall it is the vocals that stand out on waris shah more than anything else rabba'),
 ('yanni',
  'contrary to some sources this film was never released under the title vampire playgirls count dracula s great love opens outside a creepy old sanitorium in the carpathian mountains as two delivery men arrive with a large heavy man shaped crate the owner doctor wendell marlow paul naschy has just purchased the sanitorium but has not yet moved in realizing that these rich castle owning types have money and jewels just lying around they decide to wander about and see if there is anything they can steal one is struck in the head with an axe and the other gets his throat ripped out by a man in a black cape with velvet lining the opening scene is repeated over and over again as the opening credits roll meanwhile a stagecoach loaded with four young women karen haydee politoff senta rosanna yanni marlene ingrid garbo and elke mirta miller and imre polvi vic winner a strapping young male who is really nothing more than an extended cameo loses a carriage wheel in the infamous borgo pass when the stagecoach driver is killed in a freak accident the five passengers seek shelter from an oncoming storm in the nearby sanitorium where'),
 ('yanni',
  'at age 16 lavie toured canada as a backup singer with the french canadian hip hop group dubmatique after which she recorded her own demo cd lavie s demo cd reached the same producer who had co written mariah carey s first album and lavie accepted his invitation to move to california to work with him in 2006 lavie s vocals were included on the soundtracks of the motion pictures stick it and the guardian in 2007 lavie became one of the earliest to use the internet to reach fans and arouse interest of record labels by october her music video angel was featured on youtube s front page and became a finalist in the 2007 youtube awards music category lavie was listed as singer songwriter in her first album everything or nothing which was released under an independent record label in february 2010 lavie produced and performed in the charity collaboration video we are the world 25 for haiti youtube edition for relief of victims of the 2010 haiti earthquake journalist diane sawyer named the video s contributors abc news persons of the week since 2010 lavie has been a vocalist of contemporary instrumentalist yanni on his tours contributing')]

In [18]:
len(query_doc_pairs.keys())

1442

In [19]:
len(query_ids)

1444

In [20]:
from sentence_transformers import CrossEncoder
model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 13192.01it/s]

In [21]:
dict_keys_set = set(query_doc_pairs.keys())

In [22]:
scores = model.predict([
    ("How many people live in Berlin?", "Berlin had a population of 3,520,031 registered inhabitants in an area of 891.82 square kilometers."),
    ("How many people live in Berlin?", "Berlin is well known for its museums."),
])
print(scores)

[ 8.607138 -4.320079]

In [23]:
type(scores)

numpy.ndarray

In [25]:
list(scores)

[np.float32(8.607138), np.float32(-4.320079)]

In [27]:
query_score_dict = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        query_score_dict[query_id] = list(model.predict(query_doc_pairs[query_id]))

In [28]:
query_score_dict["123839"]

[np.float32(6.4627924),
 np.float32(6.419842),
 np.float32(4.9677753),
 np.float32(3.0357656),
 np.float32(5.5189133),
 np.float32(2.3268332),
 np.float32(4.384878),
 np.float32(0.7513137),
 np.float32(-3.6361036),
 np.float32(-4.7235107)]

In [29]:
del query_doc_pairs
gc.collect()

2425

In [49]:
most_related_5_dict = defaultdict(list)
most_related_5_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_5_dict[query_id].append(query_id_and_its_doc[query_id][mytuple[1]])
            most_related_5_dict_with_scores[query_id].append((query_id_and_its_doc[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_5_dict[query_id]) == 5:
                break

In [65]:
most_related_10_dict = defaultdict(list)
most_related_10_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_10_dict[query_id].append(query_id_and_its_doc[query_id][mytuple[1]])
            most_related_10_dict_with_scores[query_id].append((query_id_and_its_doc[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_10_dict[query_id]) == 10:
                break

In [31]:
most_related_5_dict

defaultdict(list,
            {'123839': ['806300', '123839', '806075', '806326', '806263'],
             '188629': ['188629', '2185399', '1990307', '2304431', '2191096'],
             '13898': ['13898', '2213954', '1698181', '1921403', '525283'],
             '316959': ['316959', '1326263', '930698', '348869', '1294742'],
             '515031': ['515031', '888195', '832086', '887826', '1376470'],
             '123783': ['1210005', '1209576', '123783', '579503', '1209561'],
             '4332': ['4332', '1442076', '989116', '1516841', '1815319'],
             '9591': ['143444', '1898638', '2416624', '2250838', '1966629'],
             '114982': ['2305139', '2305216', '1341103', '1191721', '917379'],
             '563603': ['12846', '563603', '349302', '270469', '373237'],
             '104206': ['1281151', '1972988', '104018', '149391', '200511'],
             '1580851': ['1549040',
              '2218736',
              '2187550',
              '1528190',
              '2279707'],
             '23678': ['23678', '936323', '342272', '1771004', '608269'],
             '37480': ['77763', '305953', '1027733', '246157', '154685'],
             '109454': ['109454', '2069260', '2100641', '2045342', '1450070'],
             '544250': ['544250', '2095411', '630265', '2347517', '1937433'],
             '12519': ['1091625', '1739665', '1005711', '869618', '12519'],
             '115015': ['115015', '1351327', '2202113', '1290856', '1591706'],
             '84287': ['84287', '891543', '1422745', '1095591', '189580'],
             '24998': ['2149920', '2339264', '1394401', '1409082', '1553086'],
             '11925': ['1148523', '580492', '2108567', '975838', '1595836'],
             '643': ['1115256', '643', '2246138', '33435', '88810'],
             '113075': ['113075', '572485', '1733437', '344421', '100596'],
             '1250387': ['1250387', '2217046', '297902', '2195293', '1683108'],
             '72012': ['111938', '111443', '72012', '2371473', '1806360'],
             '167865': ['167865', '385342', '1964134', '299025', '1846426'],
             '1425120': ['2316655',
              '1425120',
              '1083694',
              '1737940',
              '2147182'],
             '24883': ['24883', '647047', '2393527', '2178291', '2355895'],
             '27200': ['2389598', '292569', '1493043', '923643', '1834661'],
             '136856': ['136856', '2272554', '2037574', '817838', '2059311'],
             '6031': ['123675', '975229', '23531', '1466349', '101000'],
             '1313191': ['1313191', '94675', '2158753', '216370', '933159'],
             '187115': ['187115', '964282', '70941', '1464470', '1012100'],
             '84110': ['1987297', '1052069', '1924159', '1395090', '1275995'],
             '208234': ['208234', '263739', '1685838', '795404', '1665946'],
             '6431': ['6431', '5400', '510840', '872358', '273681'],
             '10799': ['10799', '1439685', '242372', '2322567', '313344'],
             '1417144': ['1077838', '1122564', '2168362', '491879', '1861636'],
             '32512': ['28484', '1975061', '4128', '1990265', '827758'],
             '677637': ['122359', '1797233', '677637', '424385', '1364109'],
             '97937': ['2130224', '1604490', '1885628', '902154', '1096276'],
             '113765': ['1807222', '707880', '557100', '1132759', '1697156'],
             '12900': ['1150042', '2315670', '326390', '379149', '171087'],
             '1294909': ['140477', '1437752', '75643', '2413308', '1395726'],
             '73745': ['144080', '73745', '55300', '179605', '80609'],
             '11692': ['11692', '1789375', '2158113', '938197', '1664266'],
             '22173': ['1405463', '1996894', '22173', '1481423', '1652701'],
             '76662': ['2261937', '1503801', '1508270', '848651', '2215345'],
             '164301': ['163054', '2352467', '139800', '169941', '1703770'],
             '23344': ['23344', '1911804', '2176190', '2063227', '1865562'],
             '9367': ['1080010', '1942436', '1014015', '1920437', '613453'],
             '592217': ['592217', '350482', '1932439', '2371077', '728912'],
             '98546': ['2165734', '98546', '1876890', '630445', '1651627'],
             '98175': ['98175', '1514310', '105110', '1824993', '576789'],
             '15189': ['15189', '2402251', '124228', '1423601', '1942441'],
             '1256': ['1256', '113333', '538932', '1235263', '876761'],
             '1815937': ['1815937', '1275085', '204845', '2086664', '10342'],
             '1249076': ['1249076', '271184', '117077', '1218390', '776649'],
             '80274': ['80274', '176310', '150130', '849206', '2035264'],
             '38489': ['461229', '2441739', '282393', '2310760', '1130473'],
             '11311': ['77619', '11811', '2445017', '1513312', '1971400'],
             '4754': ['4754', '2149205', '1096243', '1194767', '236496'],
             '257711': ['825222', '257711', '408205', '496318', '300746'],
             '141668': ['1238621', '2148663', '1722747', '165351', '1958630'],
             '100895': ['100895', '1673670', '2077781', '414800', '551090'],
             '32945': ['32945', '2282975', '1445894', '1304274', '583542'],
             '112321': ['112321', '956494', '107590', '1101174', '8105'],
             '133725': ['133725', '6502', '2123315', '1959279', '415845'],
             '424464': ['18386', '424464', '663519', '1487470'],
             '523456': ['523456', '414850', '1097635', '1077052', '1111392'],
             '1327515': ['2288752',
              '1327515',
              '1926176',
              '2194210',
              '1412780'],
             '12101': ['1602439', '2140400', '1939353', '1815846', '1436095'],
             '9739': ['9739', '370163', '473870', '1096838', '274722'],
             '189869': ['367496', '142177', '128794', '298520', '189807'],
             '143444': ['143444', '1363154', '390102', '619180', '654690'],
             '78940': ['129940', '400988', '400966', '78940', '1225575'],
             '12527': ['12527', '756172', '1555649', '2428193', '1263830'],
             '327199': ['327199', '1121851', '824648', '163489', '1475136'],
             '7707': ['7707', '2080398', '1330041', '86731', '2024588'],
             '97455': ['931552', '97455', '841488', '1774524', '355309'],
             '1262433': ['1262433', '138787', '2096993', '835238', '1340254'],
             '488875': ['488875', '1468866', '924773', '175119', '979767'],
             '74026': ['74026', '1212400', '1917430', '992240', '1827074'],
             '358108': ['2399039', '203958', '77900', '243022', '268308'],
             '95179': ['215045', '95179', '833428', '973662', '1431105'],
             '7862': ['31959', '104958', '1213179', '1021126', '588997'],
             '151797': ['151797', '1026962', '308871', '280333', '2282492'],
             '92980': ['92980', '1332097', '2449764', '926663', '1557037'],
             '100876': ['100876', '2091746', '222669', '504611', '663908'],
             '238228': ['238228', '1379427', '1663108', '1217535', '2037104'],
             '107755': ['107755', '44834', '736844', '1580406', '1409192'],
             '32539': ['1435368', '32539', '2149417', '619852', '620335'],
             '12953': ['453850', '198529', '2331536', '1708353', '381420'],
             '24843': ['1585346', '24843', '1642342', '1402911', '1928145'],
             '119528': ['119528', '435219', '362056', '275657', '1191258'],
             '30765': ['30765', '1663392', '403630', '2388837', '1632168'],
             '134772': ['1747453', '2402212', '1715223', '694614', '1728163'],
             '27711': ['1970676', '27711', '1159074', '1392846', '1461132'],
             '361260': ['361260', '1167923', '1139701', '344439', '159298'],
             '17874': ['987714', '1559204', '17874', '1122254', '311896'],
             '3524': ['1078977', '2406059', '312864', '295562', '646810'],
             '75902': ['1707214', '1701864', '1294898', '1704267', '1701932'],
             '809894': ['809894', '981873', '1929305', '1635656', '824756'],
             '126362': ['126362', '1788275', '847633', '1502762', '1516131'],
             '288208': ['2038287', '1028489'],
             '406254': ['406254', '2085523', '1826790', '2054691', '1679140'],
             '240663': ['240663', '142967', '1757413', '753648', '1676368'],
             '34848': ['34848', '764750', '35883', '854079', '156316'],
             '195113': ['195113', '512045', '1278027', '1611709', '1057582'],
             '264822': ['264822', '971142', '1546929', '971136', '1831265'],
             '8387': ['961577', '1929813', '228678', '1020632', '954839'],
             '186363': ['186363', '1477370', '307321', '488282', '1900825'],
             '165761': ['165761', '1708821', '2418542', '1412216', '930776'],
             '76875': ['525565', '76875', '1713010', '933176', '1649854'],
             '605155': ['605155', '278103', '1945317', '260551', '964269'],
             '17836': ['2312089', '681981', '1770705', '1519096', '899817'],
             '83566': ['405127', '1394872', '1592245', '1081980', '1518191'],
             '132697': ['132697', '676336', '157351', '1553238', '158852'],
             '1563': ['1618763', '370062', '235562', '1675166', '1619355'],
             '23924': ['164214', '1123817', '23924', '626624', '1315546'],
             '1433': ['759076', '1034593', '457952', '598439', '2109236'],
             '29737': ['2013840', '2108118', '29725', '2385784', '852564'],
             '26758': ['26758', '2076571', '783497', '1441118', '2112580'],
             '19717': ['19717', '197786', '897561', '1782889', '463885'],
             '7870': ['1485191', '679711', '651143', '2103632', '1920834'],
             '16093': ['16093', '88824', '473674', '411203', '96347'],
             '34844': ['34844', '250649', '2217226', '2019053', '1142186'],
             '2234455': ['2234455',
              '2141640',
              '1185954',
              '1444846',
              '2141731'],
             '382531': ['382531', '804041', '1354075', '2009905', '2237820'],
             '12252': ['12252', '1352426', '1355090', '2175577', '1100605'],
             '11446': ['2235819', '2036847', '2172471', '1872320', '889746'],
             '21027': ['21027', '2360154', '179968', '1862638', '122096'],
             '1370698': ['1980203',
              '1698174',
              '1370698',
              '2009222',
              '1374420'],
             '113657': ['107744', '314346', '677226', '891332', '963878'],
             '3348': ['1799474', '1044923', '2454319', '1341098', '1150100'],
             '217425': ['217425', '1252303', '2087267', '2265979', '2258338'],
             '197576': ['197576', '2167463', '583354', '609498', '641855'],
             '129397': ['129395', '129397', '1876925', '337441', '947729'],
             '257126': ['257126', '2278890', '1421735', '703777', '659465'],
             '67592': ['67592', '1222054', '1652321', '1471839', '1348313'],
             '93136': ['1763306', '2249779', '2080743', '662301', '1051409'],
             '892237': ['892237', '13602', '1890005', '1816516', '1887223'],
             '20605': ['20605', '196435', '2369296', '1780945', '441197'],
             '1219': ['1219', '279916', '1960738', '1248799', '12312'],
             '389032': ['12272', '414013', '640557', '207162', '1736398'],
             '10656': ['2424571', '1275607', '1292547', '1300376', '739776'],
             '1778': ['1778', '1724183', '19019', '205062', '217133'],
             '108160': ['108160', '1099114', '591392', '168690', '2277555'],
             '964897': ['964897', '1684564', '479549', '2187584', '1736514'],
             '94266': ['94266', '649096', '342200', '394294', '352548'],
             '13744': ['13744', '2190600', '2140823', '541791', '2138861'],
             '13539': ['277538', '1465507', '630127', '2411483', '1085300'],
             '407598': ['1971358', '1985313', '407598', '1754892', '2236705'],
             '97620': ['1423868', '1774656', '1096878', '1367832', '827012'],
             '203795': ['203795', '2134753', '2381133', '1175805', '1285016'],
             '356090': ['356090', '528928', '1535978', '1091225', '516926'],
             '112731': ['1342092', '2147684', '1965175', '2309847', '2001417'],
             '714608': ['714608', '1281195', '156180', '1486438'],
             '88181': ['88181', '656218', '588468', '2431841', '557693'],
             '87960': ['458741', '556337', '587228', '2281956', '2113092'],
             '96791': ['96791', '1114237', '181114', '708746', '662552'],
             '172084': ['283954', '700833', '172084', '2055377', '172202'],
             '1836051': ['1522614', '19342', '93722', '622603', '123911'],
             '14393': ['580610', '1141467', '699848', '2200083', '2432929'],
             '1559299': ['1559299',
              '1534860',
              '1889526',
              '1601751',
              '1486729'],
             '82801': ['82801', '109458', '1633082', '1678935', '487817'],
             '969771': ['1534783', '1529604', '370103', '1608272', '350209'],
             '125685': ['125685', '732193', '1571770', '548190', '2359633'],
             '101336': ['992327', '2442722', '723364', '1440107', '1023506'],
             '78856': ['78856', '1374910', '983910', '1234278', '1142068'],
             '126985': ['126985', '1035524', '2196806', '1128876', '484957'],
             '231130': ['2177956', '2137040', '2052103', '986949', '1029988'],
             '197161': ['197161', '754196', '1636113', '1575757', '1434980'],
             '94693': ['94693', '951006', '1225202', '1161151', '2243670'],
             '1339737': ['2151851',
              '2203733',
              '1124204',
              '2030368',
              '1943090'],
             '273381': ['2306578', '1144915', '743550', '2205510', '1507231'],
             '73398': ['774600', '813538', '838534', '1599976', '578578'],
             '179677': ['179677', '346430', '809096', '869325', '1228423'],
             '90354': ['90354', '89589', '812990', '14004', '2054353'],
             '1608685': ['856217', '2156109', '1561291', '1608685', '2075260'],
             '446634': ['1318941', '2438685', '510967', '2374339', '1526075'],
             '1595': ['888134', '1960118', '1499759', '1831922', '342314'],
             '73102': ['840361', '884888', '2297408', '364933', '350207'],
             '494392': ['494392', '313393', '1986461', '1183899', '978624'],
             '94832': ['94832', '94799', '595508', '1056056', '1989428'],
             '24349': ['133149', '24349', '2040373', '1974824', '1001705'],
             '12374': ['12374', '639852', '11139', '1781645', '1009258'],
             '151391': ['151391', '2344487', '1072063', '317031', '2430132'],
             '584158': ['584158', '16006', '1699242', '1172854', '251127'],
             '15282': ['643115', '15282', '116506', '644703', '137949'],
             '434927': ['1815312', '434927', '1116176', '2069740', '1458556'],
             '21969': ['21969', '1342497', '1569117', '2077207', '1490094'],
             '15987': ['1889773', '158483', '491822', '1536921', '1136439'],
             '13776': ['140100', '935549', '1448247', '979470', '682506'],
             '768304': ['178907', '806092', '2415064', '274041', '768304'],
             '132575': ['132575', '1235422', '1013072', '1733488', '1564447'],
             '833105': ['1418862', '1476051', '2404494', '2057393', '1574628'],
             '76345': ['969818', '205113', '888259', '1728668', '2065800'],
             '537': ['537', '842143', '556979', '1586008', '2110850'],
             '181536': ['181536', '362030', '2438006', '608416', '687472'],
             '4215': ['1363945', '244269', '72988', '1162201', '80535'],
             '17227': ['1222837', '2376958', '168722', '112870', '1103431'],
             '97781': ['2171414', '1551645', '1370210', '1950994', '1067913'],
             '1589': ['1589', '80274', '304719', '1137971', '316652'],
             '119663': ['119663', '385340', '1435726', '344639', '1594860'],
             '1336894': ['506495', '1856164', '1843535', '1323862', '816834'],
             '1568489': ['1568489', '367482', '1061347', '1185889', '2439988'],
             '133700': ['133700', '1433013', '1247892', '2253956', '537500'],
             '147768': ['147768', '1221847', '1419755', '1550026', '989914'],
             '674995': ['674995', '2377822', '180934', '175671', '201466'],
             '1047896': ['1047896', '780983', '1613615', '516926', '122821'],
             '6368': ['6368', '465821', '687049', '446807', '328785'],
             '172053': ['1001864', '1456217', '172053', '917557', '1421089'],
             '1045273': ['1045273', '690024', '87860', '2098459', '2067009'],
             '80687': ['207264', '80687', '2314600', '1888244', '911294'],
             '1263864': ['20711', '1898350', '493275', '2286338', '1742059'],
             '81739': ['81739', '396970', '1491329', '2207653', '2236215'],
             '113925': ['1182338', '1042610', '113925', '1801693', '297278'],
             '73285': ['73285', '1586232', '1178786', '313257', '940359'],
             '27399': ['1171402', '1391135', '1085631', '1391108', '1059933'],
             '35101': ['35101', '566928', '100840', '1657100', '376301'],
             '5570': ['934088', '15955', '5570', '2417455', '107755'],
             '14758': ['14758', '367980', '512502', '1650714', '250032'],
             '10792': ['10792', '1473373', '308356', '1648428', '530425'],
             '726995': ['726995', '77104', '538799', '878661', '545582'],
             '17814': ['1176814', '142213', '1729746', '761169', '1707983'],
             '908': ['908', '1143167', '2443105', '2156973', '1762851'],
             '85435': ['2017706', '85435', '301309', '897792', '572024'],
             '79941': ['79941', '1705119', '2320491', '1895534', '886219'],
             '140552': ['140552', '1903014', '727372', '1916672', '1694433'],
             '145807': ['145807', '89595', '147835', '854391', '2452212'],
             '107616': ['107616', '497277', '910719', '2355972', '1510318'],
             '13801': ['13801', '113055', '1978463', '1490799', '948477'],
             '357261': ['357261', '1017124', '1319850', '1834743', '1772337'],
             '34865': ['481179', '34865', '580016', '1214019', '999934'],
             '2259': ['1427998', '753861', '656403', '480421', '1345297'],
             '6213': ['6213', '1387836', '2024782', '1770012', '2216578'],
             '72576': ['1231040', '2320928', '512547', '1969600', '2320100'],
             '163527': ['2055561', '163527', '1467740', '1480433', '560415'],
             '75654': ['75654', '98297', '1820818', '1003003', '870184'],
             '29687': ['29687', '895773', '1950969', '1950673', '1950308'],
             '1283640': ['1476134', '1283640', '2013098', '2201083', '321631'],
             '1703622': ['1703622', '772007', '1391703', '1159164', '906660'],
             '324633': ['324633', '1250916', '1366701', '1452644', '1535670'],
             '37756': ['37756', '1366728', '995537', '704722', '1243020'],
             '1237543': ['1138593', '136819', '126571', '85239', '295094'],
             '342167': ['81830', '111259', '755016', '509206', '1619528'],
             '1058358': ['1058358', '1023064', '2131984', '2403463', '925089'],
             '248154': ['248154', '2189403', '2190309', '2366391', '1068055'],
             '330931': ['93973', '2143116', '330931'],
             '163736': ['163736', '1303180', '1890776', '1989469', '1611759'],
             '488869': ['1178803', '2033887', '924773', '1557755', '1194240'],
             '20603': ['20603', '283895', '897906', '427192', '212042'],
             '8055': ['8055', '151703', '1866298', '1805090', '690537'],
             '109832': ['598292', '865817', '2389970', '1019023', '1330175'],
             '9332': ['1990636', '755333', '701067', '1158569', '1487565'],
             '204974': ['204974', '2217571', '1021589', '1837783', '1777338'],

In [32]:
def recall(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(test_list)) * 100

In [40]:
def precision(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(found_docs)) * 100

In [66]:
def precision_AP(found_docs: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for doc in found_docs:
        if doc in test_set:
            counter += 1

    return counter / len(found_docs)


def AP(found_docs: list, test_list: list) -> float:
    total = 0

    for i in range(1, 10 + 1):
        if i < len(found_docs):
            precision_k = precision_AP(found_docs[:i], test_list)
            total += precision_k * (found_docs[i - 1] in set(test_list))

    return total / len(test_list)

In [41]:
recall_5_list, precision_5_list, AP_5_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_5_value = recall(most_related_5_dict[query_id], qrels_dict[query_id])
        precision_5_value = precision(most_related_5_dict[query_id], qrels_dict[query_id])
        AP_5_value = AP(most_related_5_dict[query_id], qrels_dict[query_id])

        recall_5_list.append(recall_5_value)
        precision_5_list.append(precision_5_value)
        AP_5_list.append(AP_5_value)
    else:
        recall_5_list.append(0)
        precision_5_list.append(0)
        AP_5_list.append(0)

In [67]:
recall_10_list, precision_10_list, AP_10_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_10_value = recall(most_related_10_dict[query_id], qrels_dict[query_id])
        precision_10_value = precision(most_related_10_dict[query_id], qrels_dict[query_id])
        AP_10_value = AP(most_related_10_dict[query_id], qrels_dict[query_id])

        recall_10_list.append(recall_10_value)
        precision_10_list.append(precision_10_value)
        AP_10_list.append(AP_10_value)
    else:
        recall_10_list.append(0)
        precision_10_list.append(0)
        AP_10_list.append(0)

In [42]:
recall_5_list

[66.66666666666666,
 33.33333333333333,
 33.33333333333333,
 22.22222222222222,
 7.142857142857142,
 26.666666666666668,
 8.333333333333332,
 0.322234156820623,
 16.666666666666664,
 4.081632653061225,
 0.0,
 0.0,
 50.0,
 22.22222222222222,
 28.57142857142857,
 33.33333333333333,
 33.33333333333333,
 62.5,
 16.666666666666664,
 8.333333333333332,
 0.6172839506172839,
 11.11111111111111,
 14.285714285714285,
 18.181818181818183,
 30.0,
 27.27272727272727,
 57.14285714285714,
 22.22222222222222,
 5.555555555555555,
 33.33333333333333,
 5.714285714285714,
 14.285714285714285,
 16.666666666666664,
 6.451612903225806,
 14.285714285714285,
 12.5,
 11.11111111111111,
 0.0,
 0.0,
 18.181818181818183,
 15.384615384615385,
 10.0,
 0.0,
 0.0,
 3.8461538461538463,
 33.33333333333333,
 12.5,
 3.8461538461538463,
 0.0,
 25.0,
 2.4390243902439024,
 33.33333333333333,
 16.666666666666664,
 16.666666666666664,
 4.166666666666666,
 4.761904761904762,
 16.666666666666664,
 16.666666666666664,
 8.333333333333332,
 9.090909090909092,
 0.1958863858961802,
 11.11111111111111,
 16.666666666666664,
 12.5,
 33.33333333333333,
 25.0,
 16.666666666666664,
 20.0,
 12.5,
 12.5,
 66.66666666666666,
 33.33333333333333,
 7.6923076923076925,
 0.0,
 14.285714285714285,
 30.0,
 50.0,
 16.666666666666664,
 0.8620689655172413,
 28.57142857142857,
 6.666666666666667,
 16.666666666666664,
 27.27272727272727,
 0.0,
 50.0,
 16.666666666666664,
 6.25,
 6.25,
 3.225806451612903,
 15.789473684210526,
 4.3478260869565215,
 4.545454545454546,
 10.0,
 9.090909090909092,
 3.4482758620689653,
 28.57142857142857,
 23.076923076923077,
 14.285714285714285,
 25.0,
 7.142857142857142,
 30.0,
 33.33333333333333,
 42.857142857142854,
 5.0,
 10.0,
 50.0,
 16.666666666666664,
 15.384615384615385,
 16.666666666666664,
 30.0,
 38.46153846153847,
 11.11111111111111,
 14.285714285714285,
 16.666666666666664,
 11.11111111111111,
 16.666666666666664,
 33.33333333333333,
 10.0,
 0.0,
 16.666666666666664,
 0.0,
 0.0,
 21.052631578947366,
 30.76923076923077,
 0.0,
 33.33333333333333,
 12.5,
 8.333333333333332,
 12.5,
 0.8403361344537815,
 12.5,
 28.57142857142857,
 16.666666666666664,
 0.0,
 50.0,
 28.57142857142857,
 14.285714285714285,
 7.6923076923076925,
 9.090909090909092,
 23.076923076923077,
 0.0,
 28.57142857142857,
 10.0,
 5.0,
 0.0,
 0.0,
 8.333333333333332,
 33.33333333333333,
 27.27272727272727,
 33.33333333333333,
 8.333333333333332,
 0.8,
 50.0,
 2.2222222222222223,
 50.0,
 14.285714285714285,
 14.285714285714285,
 33.33333333333333,
 2.083333333333333,
 5.0,
 20.0,
 33.33333333333333,
 0.0,
 0.0,
 2.7777777777777777,
 18.181818181818183,
 40.0,
 12.5,
 0.0,
 10.0,
 14.285714285714285,
 0.0,
 50.0,
 11.11111111111111,
 7.142857142857142,
 28.57142857142857,
 0.0,
 33.33333333333333,
 11.11111111111111,
 28.57142857142857,
 15.384615384615385,
 0.0,
 50.0,
 12.5,
 10.0,
 9.090909090909092,
 30.0,
 16.666666666666664,
 28.57142857142857,
 14.285714285714285,
 2.7027027027027026,
 14.285714285714285,
 0.0,
 0.0,
 16.666666666666664,
 33.33333333333333,
 18.181818181818183,
 50.0,
 30.0,
 14.285714285714285,
 0.0,
 33.33333333333333,
 0.0,
 14.285714285714285,
 6.25,
 0.0,
 7.6923076923076925,
 16.666666666666664,
 37.5,
 22.22222222222222,
 25.0,
 40.0,
 25.0,
 5.0,
 14.285714285714285,
 11.11111111111111,
 30.0,
 17.647058823529413,
 12.5,
 0.0,
 11.11111111111111,
 7.894736842105263,
 2.142857142857143,
 14.285714285714285,
 23.076923076923077,
 0.0,
 42.857142857142854,
 11.11111111111111,
 15.789473684210526,
 9.090909090909092,
 33.33333333333333,
 7.6923076923076925,
 3.571428571428571,
 7.142857142857142,
 25.0,
 0.0,
 13.333333333333334,
 0.0,
 11.11111111111111,
 11.76470588235294,
 11.11111111111111,
 14.285714285714285,
 37.5,
 66.66666666666666,
 16.666666666666664,
 4.166666666666666,
 0.0,
 14.285714285714285,
 33.33333333333333,
 33.33333333333333,
 33.33333333333333,
 16.666666666666664,
 28.57142857142857,
 9.433962264150944,
 0.0,
 0.33670033670033667,
 10.0,
 25.0,
 5.263157894736842,
 28.57142857142857,
 0.0,
 4.761904761904762,
 21.428571428571427,
 9.090909090909092,
 0.0,
 11.11111111111111,
 4.545454545454546,
 11.11111111111111,
 42.857142857142854,
 7.6923076923076925,
 12.5,
 0.0,
 50.0,
 12.5,
 23.52941176470588,
 28.57142857142857,
 57.14285714285714,
 6.25,
 7.142857142857142,
 22.22222222222222,
 6.25,
 8.333333333333332,
 10.0,
 11.11111111111111,
 2.0202020202020203,
 66.66666666666666,
 25.0,
 15.384615384615385,
 15.0,
 33.33333333333333,
 13.333333333333334,
 20.0,
 5.555555555555555,
 0.0,
 44.44444444444444,
 7.6923076923076925,
 9.090909090909092,
 0.0,
 3.3333333333333335,
 14.285714285714285,
 50.0,
 14.285714285714285,
 1.3513513513513513,
 25.0,
 14.285714285714285,
 1.5151515151515151,
 12.5,
 7.4074074074074066,
 4.3478260869565215,
 0,
 14.285714285714285,
 16.666666666666664,
 10.0,
 20.0,
 0.6369426751592357,
 14.285714285714285,
 15.384615384615385,
 6.25,
 5.714285714285714,
 50.0,
 8.333333333333332,
 2.1505376344086025,
 12.5,
 0.0,
 15.384615384615385,
 42.857142857142854,
 12.5,
 0.0,
 0.5181347150259068,
 36.36363636363637,
 12.5,
 25.0,
 18.181818181818183,
 33.33333333333333,
 0.0,
 11.11111111111111,
 0.0,
 50.0,
 22.22222222222222,
 16.666666666666664,
 16.666666666666664,
 1.694915254237288,
 14.285714285714285,
 20.0,
 16.666666666666664,
 0.0,
 0.11372251705837756,
 10.256410256410255,
 37.5,
 6.666666666666667,
 21.73913043478261,
 27.27272727272727,
 16.666666666666664,
 22.22222222222222,
 15.384615384615385,
 33.33333333333333,
 0.6535947712418301,
 14.285714285714285,
 4.918032786885246,
 14.285714285714285,
 22.22222222222222,
 33.33333333333333,
 16.666666666666664,
 50.0,
 11.11111111111111,
 11.11111111111111,
 1.6666666666666667,
 12.5,
 0.0,
 27.27272727272727,
 20.0,
 14.285714285714285,
 25.0,
 22.22222222222222,
 10.0,
 0.0,
 25.0,
 9.090909090909092,
 4.166666666666666,
 0.591715976331361,
 0.0,
 11.76470588235294,
 0.0,
 7.6923076923076925,
 5.555555555555555,
 14.285714285714285,
 37.5,
 16.666666666666664,
 40.0,
 50.0,
 9.090909090909092,
 16.666666666666664,
 0.0,
 0.4319654427645789,
 5.263157894736842,
 11.11111111111111,
 14.285714285714285,
 0.0,
 16.666666666666664,
 1.0344827586206897,
 0.11037527593818984,
 16.666666666666664,
 42.857142857142854,
 16.666666666666664,
 2.0408163265306123,
 0.0,
 7.142857142857142,
 11.76470588235294,
 62.5,
 5.128205128205128,
 0.0,
 10.0,
 27.27272727272727,
 14.285714285714285,
 42.857142857142854,
 33.33333333333333,
 0.0,
 12.5,
 11.11111111111111,
 50.0,
 37.5,
 11.11111111111111,
 16.666666666666664,
 14.285714285714285,
 28.57142857142857,
 1.1904761904761905,
 16.666666666666664,
 0.0,
 0.0,
 25.0,
 0.0,
 66.66666666666666,
 16.666666666666664,
 23.809523809523807,
 16.666666666666664,
 4.0,
 3.3333333333333335,
 11.76470588235294,
 28.57142857142857,
 7.142857142857142,
 0.0,
 22.22222222222222,
 19.047619047619047,
 3.9215686274509802,
 33.33333333333333,
 12.5,
 16.666666666666664,
 14.285714285714285,
 33.33333333333333,
 16.666666666666664,
 20.0,
 12.5,
 0.0,
 10.0,
 0.0,
 20.0,
 0.0,
 7.142857142857142,
 2.857142857142857,
 20.0,
 12.5,
 0.0,
 12.5,
 12.5,
 11.11111111111111,
 8.333333333333332,
 22.22222222222222,
 13.636363636363635,
 25.0,
 0.0,
 16.666666666666664,
 28.57142857142857,
 6.666666666666667,
 33.33333333333333,
 8.333333333333332,
 14.285714285714285,
 16.666666666666664,
 14.285714285714285,
 11.11111111111111,
 5.88235294117647,
 0.0,
 12.5,
 40.0,
 0.0,
 0.0,
 37.5,
 0.0,
 33.33333333333333,
 3.7037037037037033,
 2.7027027027027026,
 12.5,
 16.666666666666664,
 10.0,
 28.57142857142857,
 8.333333333333332,
 14.285714285714285,
 2.941176470588235,
 16.666666666666664,
 8.333333333333332,
 42.857142857142854,
 5.0,
 0.0,
 12.5,
 33.33333333333333,
 50.0,
 9.090909090909092,
 12.5,
 16.666666666666664,
 28.57142857142857,
 8.0,
 16.666666666666664,
 50.0,
 42.857142857142854,
 6.024096385542169,
 36.36363636363637,
 26.666666666666668,
 5.084745762711865,
 42.857142857142854,
 20.0,
 0.0,
 16.666666666666664,
 21.428571428571427,
 6.666666666666667,
 14.814814814814813,
 16.666666666666664,
 3.076923076923077,
 16.666666666666664,
 33.33333333333333,
 12.5,
 22.22222222222222,
 7.142857142857142,
 22.22222222222222,
 14.285714285714285,
 20.0,
 16.666666666666664,
 5.88235294117647,
 16.666666666666664,
 9.090909090909092,
 1.5384615384615385,
 0.0,
 11.76470588235294,
 12.5,
 5.084745762711865,
 11.11111111111111,
 17.857142857142858,
 8.333333333333332,
 50.0,
 2.631578947368421,
 42.857142857142854,
 12.5,
 11.11111111111111,
 15.384615384615385,
 28.57142857142857,
 0.0,
 2.631578947368421,
 3.7037037037037033,
 27.27272727272727,
 12.5,
 7.142857142857142,
 5.714285714285714,
 1.36986301369863,
 1.3333333333333335,
 0.0,
 16.666666666666664,
 12.5,
 0.0,
 25.0,
 0.0,
 9.090909090909092,
 21.428571428571427,
 3.4482758620689653,
 33.33333333333333,
 28.57142857142857,
 11.538461538461538,
 57.14285714285714,
 18.75,
 33.33333333333333,
 28.57142857142857,
 50.0,
 42.857142857142854,
 2.1739130434782608,
 6.666666666666667,
 37.5,
 0.0,
 28.57142857142857,
 1.2987012987012987,
 11.11111111111111,
 3.7037037037037033,
 0.819672131147541,
 57.14285714285714,
 0.0,
 14.285714285714285,
 12.5,
 11.11111111111111,
 33.33333333333333,
 16.666666666666664,
 12.5,
 28.57142857142857,
 8.333333333333332,
 25.0,
 33.33333333333333,
 0.0,
 28.57142857142857,
 7.6923076923076925,
 57.14285714285714,
 10.0,
 25.0,
 16.129032258064516,
 33.33333333333333,
 28.57142857142857,
 15.384615384615385,
 0.0,
 5.88235294117647,
 16.666666666666664,
 8.333333333333332,
 0.8021390374331552,
 33.33333333333333,
 6.666666666666667,
 11.11111111111111,
 30.76923076923077,
 14.285714285714285,
 0.0,
 2.857142857142857,
 10.0,
 8.333333333333332,
 27.27272727272727,
 14.285714285714285,
 50.0,
 9.090909090909092,
 33.33333333333333,
 3.0303030303030303,
 16.666666666666664,
 0.0,
 16.666666666666664,
 8.333333333333332,
 0.0,
 10.0,
 10.0,
 3.125,
 55.55555555555556,
 33.33333333333333,
 29.411764705882355,
 33.33333333333333,
 25.0,
 0.0,
 14.285714285714285,
 14.285714285714285,
 11.11111111111111,
 22.22222222222222,
 12.5,
 8.333333333333332,
 1.7241379310344827,
 25.0,
 28.57142857142857,
 15.384615384615385,
 33.33333333333333,
 16.666666666666664,
 1.7241379310344827,
 20.0,
 28.57142857142857,
 0.0,
 50.0,
 37.5,
 25.0,
 21.052631578947366,
 9.090909090909092,
 28.57142857142857,
 6.25,
 9.090909090909092,
 12.5,
 14.285714285714285,
 16.666666666666664,
 12.5,
 18.181818181818183,
 50.0,
 2.380952380952381,
 50.0,
 2.631578947368421,
 9.090909090909092,
 1.0416666666666665,
 12.5,
 9.67741935483871,
 14.285714285714285,
 12.5,
 33.33333333333333,
 40.0,
 20.0,
 11.11111111111111,
 20.0,
 33.33333333333333,
 5.88235294117647,
 0.0,
 28.57142857142857,
 11.11111111111111,
 25.0,
 0.0,
 0.0,
 37.5,
 12.5,
 20.0,
 1.4598540145985401,
 33.33333333333333,
 0.0,
 33.33333333333333,
 14.285714285714285,
 16.666666666666664,
 0.0,
 0.0,
 14.285714285714285,
 11.11111111111111,
 25.0,
 7.6923076923076925,
 20.0,
 5.88235294117647,
 14.285714285714285,
 16.666666666666664,
 5.263157894736842,
 9.090909090909092,
 44.44444444444444,
 0.0,
 25.0,
 28.57142857142857,
 14.285714285714285,
 7.6923076923076925,
 0.0,
 15.0,
 11.11111111111111,
 14.285714285714285,
 0.23923444976076555,
 10.0,
 11.11111111111111,
 2.7027027027027026,
 42.857142857142854,
 0.0,
 42.857142857142854,
 16.666666666666664,
 20.0,
 12.5,
 16.666666666666664,
 3.9215686274509802,
 9.090909090909092,
 11.11111111111111,
 0.3645200486026731,
 7.6923076923076925,
 20.0,
 16.666666666666664,
 9.523809523809524,
 16.666666666666664,
 0.0,
 16.666666666666664,
 0.0,
 11.11111111111111,
 2.4390243902439024,
 25.0,
 8.571428571428571,
 16.666666666666664,
 0.0,
 0.0,
 8.108108108108109,
 14.285714285714285,
 20.0,
 2.127659574468085,
 10.0,
 33.33333333333333,
 10.0,
 50.0,
 33.33333333333333,
 0.0,
 8.333333333333332,
 50.0,
 11.11111111111111,
 1.680672268907563,
 10.0,
 10.0,
 14.285714285714285,
 7.142857142857142,
 12.5,
 12.5,
 28.57142857142857,
 28.57142857142857,
 14.285714285714285,
 4.761904761904762,
 6.666666666666667,
 16.666666666666664,
 33.33333333333333,
 15.0,
 33.33333333333333,
 0.0,
 33.33333333333333,
 1.5873015873015872,
 14.285714285714285,
 37.5,
 25.0,
 9.090909090909092,
 28.57142857142857,
 8.333333333333332,
 14.285714285714285,
 11.11111111111111,
 2.1739130434782608,
 11.11111111111111,
 50.0,
 6.666666666666667,
 50.0,
 37.5,
 3.7037037037037033,
 42.857142857142854,
 12.5,
 50.0,
 4.3478260869565215,
 9.090909090909092,
 42.857142857142854,
 0.6920415224913495,
 0.0,
 6.666666666666667,
 50.0,
 9.090909090909092,
 6.25,
 0.0,
 33.33333333333333,
 11.11111111111111,
 12.5,
 23.076923076923077,
 0.0,
 12.5,
 0.0,
 33.33333333333333,
 3.3333333333333335,
 0.0,
 16.666666666666664,
 0.0,
 16.666666666666664,
 12.5,
 3.125,
 7.4074074074074066,
 25.0,
 25.0,
 28.57142857142857,
 14.285714285714285,
 9.090909090909092,
 0.0,
 33.33333333333333,
 12.5,
 1.8181818181818181,
 7.142857142857142,
 33.33333333333333,
 0.08149959250203749,
 50.0,
 16.666666666666664,
 14.285714285714285,
 14.285714285714285,
 5.88235294117647,
 0.0,
 10.0,
 42.857142857142854,
 9.090909090909092,
 10.0,
 3.7037037037037033,
 10.526315789473683,
 57.14285714285714,
 0.0,
 33.33333333333333,
 5.660377358490567,
 14.285714285714285,
 0.0,
 14.285714285714285,
 37.5,
 42.857142857142854,
 45.45454545454545,
 33.33333333333333,
 33.33333333333333,
 33.33333333333333,
 16.666666666666664,
 0.0,
 8.333333333333332,
 25.0,
 25.0,
 8.333333333333332,
 8.333333333333332,
 12.5,
 5.405405405405405,
 14.285714285714285,
 9.090909090909092,
 16.666666666666664,
 12.5,
 4.761904761904762,
 0.0,
 14.285714285714285,
 3.6363636363636362,
 5.0,
 13.333333333333334,
 2.941176470588235,
 0.0,
 28.57142857142857,
 0.684931506849315,
 16.666666666666664,
 15.0,
 11.11111111111111,
 33.33333333333333,
 8.571428571428571,
 0.0,
 42.857142857142854,
 16.666666666666664,
 0.0,
 0.0,
 0.5235602094240838,
 18.181818181818183,
 9.090909090909092,
 20.0,
 22.22222222222222,
 9.090909090909092,
 14.285714285714285,
 0.0,
 16.666666666666664,
 0.0,
 13.636363636363635,
 0.0,
 16.666666666666664,
 6.451612903225806,
 0.0,
 9.67741935483871,
 16.666666666666664,
 0.0,
 12.5,
 16.666666666666664,
 0.0,
 10.0,
 9.090909090909092,
 33.33333333333333,
 3.1746031746031744,
 7.6923076923076925,
 16.666666666666664,
 16.666666666666664,
 1.6129032258064515,
 57.14285714285714,
 0.0,
 12.5,
 0.0,
 6.666666666666667,
 0.0,
 26.31578947368421,
 7.5,
 0.0,
 0.0,
 28.57142857142857,
 0.0,
 0.7633587786259541,
 8.333333333333332,
 3.4090909090909087,
 11.11111111111111,
 1.2195121951219512,
 18.181818181818183,
 9.090909090909092,
 16.666666666666664,
 11.11111111111111,
 30.0,
 1.1976047904191618,
 10.0,
 0.0,
 18.181818181818183,
 3.571428571428571,
 4.166666666666666,
 23.076923076923077,
 7.6923076923076925,
 8.823529411764707,
 2.2222222222222223,
 12.5,
 20.0,
 14.285714285714285,
 14.285714285714285,
 0.0,
 2.272727272727273,
 33.33333333333333,
 22.22222222222222,
 14.285714285714285,
 12.5,
 50.0,
 22.22222222222222,
 33.33333333333333,
 4.3478260869565215,
 28.57142857142857,
 25.0,
 25.0,
 16.666666666666664,
 28.57142857142857,
 22.22222222222222,
 20.0,
 7.6923076923076925,
 0.0,
 13.043478260869565,
 57.14285714285714,
 25.0,
 33.33333333333333,
 2.857142857142857,
 11.11111111111111,
 33.33333333333333,
 6.666666666666667,
 7.6923076923076925,
 21.428571428571427,
 0.0,
 3.125,
 ...]

In [43]:
len(recall_5_list)

1444

In [44]:
len(precision_5_list)

1444

In [68]:
recall_10_list

[100.0,
 33.33333333333333,
 33.33333333333333,
 22.22222222222222,
 14.285714285714285,
 33.33333333333333,
 8.333333333333332,
 0.5370569280343717,
 25.0,
 7.142857142857142,
 16.666666666666664,
 7.6923076923076925,
 50.0,
 44.44444444444444,
 28.57142857142857,
 33.33333333333333,
 66.66666666666666,
 87.5,
 16.666666666666664,
 8.333333333333332,
 0.6172839506172839,
 11.11111111111111,
 14.285714285714285,
 18.181818181818183,
 30.0,
 27.27272727272727,
 85.71428571428571,
 22.22222222222222,
 5.555555555555555,
 33.33333333333333,
 11.428571428571429,
 14.285714285714285,
 33.33333333333333,
 16.129032258064516,
 14.285714285714285,
 12.5,
 11.11111111111111,
 0.0,
 0.0,
 31.818181818181817,
 38.46153846153847,
 20.0,
 14.285714285714285,
 1.1904761904761905,
 7.6923076923076925,
 50.0,
 25.0,
 7.6923076923076925,
 0.0,
 37.5,
 2.4390243902439024,
 33.33333333333333,
 16.666666666666664,
 16.666666666666664,
 4.166666666666666,
 7.142857142857142,
 16.666666666666664,
 50.0,
 8.333333333333332,
 9.090909090909092,
 0.4897159647404506,
 11.11111111111111,
 16.666666666666664,
 12.5,
 44.44444444444444,
 25.0,
 16.666666666666664,
 20.0,
 12.5,
 12.5,
 66.66666666666666,
 33.33333333333333,
 7.6923076923076925,
 0.0,
 14.285714285714285,
 60.0,
 83.33333333333334,
 33.33333333333333,
 1.7241379310344827,
 28.57142857142857,
 13.333333333333334,
 16.666666666666664,
 27.27272727272727,
 0.0,
 66.66666666666666,
 16.666666666666664,
 6.25,
 12.5,
 3.225806451612903,
 21.052631578947366,
 4.3478260869565215,
 6.0606060606060606,
 20.0,
 9.090909090909092,
 3.4482758620689653,
 28.57142857142857,
 30.76923076923077,
 23.809523809523807,
 37.5,
 14.285714285714285,
 30.0,
 50.0,
 42.857142857142854,
 10.0,
 10.0,
 60.0,
 16.666666666666664,
 23.076923076923077,
 16.666666666666664,
 40.0,
 53.84615384615385,
 11.11111111111111,
 28.57142857142857,
 16.666666666666664,
 11.11111111111111,
 33.33333333333333,
 33.33333333333333,
 10.0,
 0.0,
 16.666666666666664,
 10.0,
 16.666666666666664,
 26.31578947368421,
 53.84615384615385,
 0.0,
 55.55555555555556,
 25.0,
 8.333333333333332,
 12.5,
 0.8403361344537815,
 12.5,
 57.14285714285714,
 16.666666666666664,
 0.0,
 66.66666666666666,
 42.857142857142854,
 28.57142857142857,
 7.6923076923076925,
 15.151515151515152,
 23.076923076923077,
 10.0,
 42.857142857142854,
 10.0,
 6.666666666666667,
 12.5,
 0.0,
 8.333333333333332,
 66.66666666666666,
 27.27272727272727,
 33.33333333333333,
 16.666666666666664,
 1.2,
 50.0,
 4.444444444444445,
 50.0,
 14.285714285714285,
 14.285714285714285,
 33.33333333333333,
 2.083333333333333,
 10.0,
 30.0,
 33.33333333333333,
 0.0,
 15.0,
 2.7777777777777777,
 18.181818181818183,
 70.0,
 12.5,
 0.0,
 15.0,
 14.285714285714285,
 0.0,
 75.0,
 11.11111111111111,
 7.142857142857142,
 28.57142857142857,
 16.666666666666664,
 33.33333333333333,
 11.11111111111111,
 42.857142857142854,
 30.76923076923077,
 0.0,
 83.33333333333334,
 37.5,
 10.0,
 18.181818181818183,
 30.0,
 16.666666666666664,
 28.57142857142857,
 28.57142857142857,
 2.7027027027027026,
 19.047619047619047,
 0.0,
 14.285714285714285,
 16.666666666666664,
 33.33333333333333,
 18.181818181818183,
 66.66666666666666,
 30.0,
 14.285714285714285,
 15.384615384615385,
 33.33333333333333,
 23.52941176470588,
 28.57142857142857,
 6.25,
 0.0,
 7.6923076923076925,
 16.666666666666664,
 75.0,
 22.22222222222222,
 25.0,
 50.0,
 25.0,
 5.0,
 14.285714285714285,
 11.11111111111111,
 30.0,
 35.294117647058826,
 50.0,
 0.0,
 11.11111111111111,
 7.894736842105263,
 2.857142857142857,
 14.285714285714285,
 38.46153846153847,
 0.0,
 57.14285714285714,
 11.11111111111111,
 15.789473684210526,
 9.090909090909092,
 33.33333333333333,
 7.6923076923076925,
 3.571428571428571,
 7.142857142857142,
 37.5,
 0.0,
 13.333333333333334,
 0.0,
 22.22222222222222,
 23.52941176470588,
 11.11111111111111,
 14.285714285714285,
 37.5,
 83.33333333333334,
 16.666666666666664,
 4.166666666666666,
 0.0,
 14.285714285714285,
 50.0,
 33.33333333333333,
 66.66666666666666,
 16.666666666666664,
 28.57142857142857,
 9.433962264150944,
 0.0,
 0.5050505050505051,
 30.0,
 25.0,
 10.526315789473683,
 28.57142857142857,
 4.545454545454546,
 4.761904761904762,
 28.57142857142857,
 9.090909090909092,
 0.0,
 16.666666666666664,
 4.545454545454546,
 11.11111111111111,
 42.857142857142854,
 7.6923076923076925,
 12.5,
 0.0,
 66.66666666666666,
 16.666666666666664,
 35.294117647058826,
 42.857142857142854,
 57.14285714285714,
 6.25,
 7.142857142857142,
 22.22222222222222,
 31.25,
 8.333333333333332,
 10.0,
 27.77777777777778,
 2.0202020202020203,
 83.33333333333334,
 25.0,
 23.076923076923077,
 15.0,
 50.0,
 20.0,
 30.0,
 16.666666666666664,
 0.0,
 55.55555555555556,
 7.6923076923076925,
 9.090909090909092,
 0.0,
 3.3333333333333335,
 14.285714285714285,
 66.66666666666666,
 14.285714285714285,
 1.3513513513513513,
 37.5,
 35.714285714285715,
 2.272727272727273,
 12.5,
 7.4074074074074066,
 4.3478260869565215,
 0,
 28.57142857142857,
 33.33333333333333,
 30.0,
 20.0,
 1.2738853503184715,
 14.285714285714285,
 23.076923076923077,
 6.25,
 14.285714285714285,
 50.0,
 33.33333333333333,
 3.225806451612903,
 12.5,
 0.0,
 19.230769230769234,
 100.0,
 25.0,
 8.333333333333332,
 1.0362694300518136,
 54.54545454545454,
 25.0,
 37.5,
 27.27272727272727,
 33.33333333333333,
 0.0,
 11.11111111111111,
 0.0,
 62.5,
 44.44444444444444,
 16.666666666666664,
 16.666666666666664,
 3.389830508474576,
 14.285714285714285,
 20.0,
 16.666666666666664,
 16.666666666666664,
 0.22744503411675512,
 15.384615384615385,
 37.5,
 6.666666666666667,
 43.47826086956522,
 36.36363636363637,
 16.666666666666664,
 33.33333333333333,
 23.076923076923077,
 50.0,
 1.3071895424836601,
 42.857142857142854,
 4.918032786885246,
 14.285714285714285,
 22.22222222222222,
 33.33333333333333,
 16.666666666666664,
 62.5,
 11.11111111111111,
 11.11111111111111,
 1.6666666666666667,
 37.5,
 1.25,
 36.36363636363637,
 30.0,
 14.285714285714285,
 75.0,
 22.22222222222222,
 20.0,
 0.8695652173913043,
 25.0,
 18.181818181818183,
 8.333333333333332,
 0.9861932938856016,
 1.744186046511628,
 11.76470588235294,
 0.0,
 7.6923076923076925,
 16.666666666666664,
 42.857142857142854,
 37.5,
 16.666666666666664,
 50.0,
 50.0,
 9.090909090909092,
 16.666666666666664,
 0.0,
 0.6479481641468683,
 15.789473684210526,
 22.22222222222222,
 14.285714285714285,
 0.0,
 16.666666666666664,
 1.0344827586206897,
 0.11037527593818984,
 16.666666666666664,
 42.857142857142854,
 16.666666666666664,
 4.081632653061225,
 0.0,
 7.142857142857142,
 11.76470588235294,
 87.5,
 7.6923076923076925,
 0.0,
 10.0,
 27.27272727272727,
 14.285714285714285,
 42.857142857142854,
 33.33333333333333,
 0.0,
 12.5,
 11.11111111111111,
 70.0,
 62.5,
 22.22222222222222,
 16.666666666666664,
 28.57142857142857,
 28.57142857142857,
 1.1904761904761905,
 16.666666666666664,
 18.181818181818183,
 0.0,
 50.0,
 0.0,
 100.0,
 33.33333333333333,
 38.095238095238095,
 33.33333333333333,
 4.0,
 3.3333333333333335,
 11.76470588235294,
 28.57142857142857,
 7.142857142857142,
 0.0,
 50.0,
 23.809523809523807,
 5.88235294117647,
 66.66666666666666,
 12.5,
 33.33333333333333,
 14.285714285714285,
 53.333333333333336,
 16.666666666666664,
 60.0,
 25.0,
 7.142857142857142,
 10.0,
 0.0,
 20.0,
 0.0,
 7.142857142857142,
 2.857142857142857,
 26.666666666666668,
 12.5,
 0.0,
 25.0,
 12.5,
 22.22222222222222,
 16.666666666666664,
 22.22222222222222,
 22.727272727272727,
 25.0,
 0.0,
 16.666666666666664,
 35.714285714285715,
 6.666666666666667,
 33.33333333333333,
 8.333333333333332,
 14.285714285714285,
 33.33333333333333,
 28.57142857142857,
 11.11111111111111,
 5.88235294117647,
 0.0,
 12.5,
 50.0,
 0.0,
 5.0,
 50.0,
 0.0,
 50.0,
 3.7037037037037033,
 2.7027027027027026,
 12.5,
 16.666666666666664,
 12.5,
 57.14285714285714,
 8.333333333333332,
 14.285714285714285,
 8.823529411764707,
 16.666666666666664,
 16.666666666666664,
 57.14285714285714,
 5.0,
 0.0,
 12.5,
 50.0,
 50.0,
 9.090909090909092,
 12.5,
 16.666666666666664,
 28.57142857142857,
 12.0,
 16.666666666666664,
 50.0,
 57.14285714285714,
 6.024096385542169,
 45.45454545454545,
 33.33333333333333,
 8.47457627118644,
 71.42857142857143,
 40.0,
 0.0,
 22.22222222222222,
 21.428571428571427,
 6.666666666666667,
 18.51851851851852,
 16.666666666666664,
 3.076923076923077,
 50.0,
 33.33333333333333,
 20.833333333333336,
 22.22222222222222,
 7.142857142857142,
 22.22222222222222,
 14.285714285714285,
 30.0,
 16.666666666666664,
 5.88235294117647,
 16.666666666666664,
 18.181818181818183,
 1.5384615384615385,
 0.0,
 11.76470588235294,
 12.5,
 8.47457627118644,
 22.22222222222222,
 25.0,
 8.333333333333332,
 50.0,
 2.631578947368421,
 42.857142857142854,
 12.5,
 11.11111111111111,
 15.384615384615385,
 28.57142857142857,
 0.0,
 2.631578947368421,
 3.7037037037037033,
 27.27272727272727,
 12.5,
 7.142857142857142,
 8.571428571428571,
 2.73972602739726,
 2.666666666666667,
 8.333333333333332,
 16.666666666666664,
 37.5,
 0.0,
 25.0,
 0.0,
 13.636363636363635,
 21.428571428571427,
 3.4482758620689653,
 33.33333333333333,
 28.57142857142857,
 11.538461538461538,
 57.14285714285714,
 18.75,
 50.0,
 28.57142857142857,
 62.5,
 57.14285714285714,
 2.1739130434782608,
 6.666666666666667,
 37.5,
 0.0,
 42.857142857142854,
 1.2987012987012987,
 11.11111111111111,
 7.4074074074074066,
 1.4344262295081966,
 57.14285714285714,
 0.0,
 14.285714285714285,
 12.5,
 11.11111111111111,
 44.44444444444444,
 16.666666666666664,
 12.5,
 42.857142857142854,
 16.666666666666664,
 25.0,
 33.33333333333333,
 0.0,
 57.14285714285714,
 7.6923076923076925,
 71.42857142857143,
 10.0,
 37.5,
 22.58064516129032,
 66.66666666666666,
 57.14285714285714,
 23.076923076923077,
 12.5,
 5.88235294117647,
 16.666666666666664,
 25.0,
 1.06951871657754,
 33.33333333333333,
 6.666666666666667,
 16.666666666666664,
 30.76923076923077,
 14.285714285714285,
 8.333333333333332,
 2.857142857142857,
 10.0,
 16.666666666666664,
 54.54545454545454,
 14.285714285714285,
 66.66666666666666,
 18.181818181818183,
 50.0,
 3.0303030303030303,
 33.33333333333333,
 0.0,
 16.666666666666664,
 16.666666666666664,
 14.285714285714285,
 10.0,
 10.0,
 3.125,
 77.77777777777779,
 50.0,
 58.82352941176471,
 33.33333333333333,
 50.0,
 0.0,
 14.285714285714285,
 14.285714285714285,
 11.11111111111111,
 33.33333333333333,
 12.5,
 8.333333333333332,
 1.7241379310344827,
 25.0,
 28.57142857142857,
 23.076923076923077,
 33.33333333333333,
 16.666666666666664,
 1.7241379310344827,
 20.0,
 42.857142857142854,
 16.666666666666664,
 50.0,
 50.0,
 37.5,
 31.57894736842105,
 9.090909090909092,
 42.857142857142854,
 6.25,
 27.27272727272727,
 12.5,
 14.285714285714285,
 16.666666666666664,
 12.5,
 18.181818181818183,
 66.66666666666666,
 2.380952380952381,
 50.0,
 13.157894736842104,
 9.090909090909092,
 1.5625,
 25.0,
 9.67741935483871,
 14.285714285714285,
 12.5,
 33.33333333333333,
 60.0,
 33.33333333333333,
 11.11111111111111,
 30.0,
 55.55555555555556,
 11.76470588235294,
 4.3478260869565215,
 28.57142857142857,
 22.22222222222222,
 25.0,
 0.0,
 9.090909090909092,
 50.0,
 12.5,
 30.0,
 1.4598540145985401,
 33.33333333333333,
 0.0,
 33.33333333333333,
 28.57142857142857,
 16.666666666666664,
 0.0,
 0.0,
 28.57142857142857,
 11.11111111111111,
 50.0,
 7.6923076923076925,
 20.0,
 5.88235294117647,
 14.285714285714285,
 16.666666666666664,
 5.263157894736842,
 9.090909090909092,
 55.55555555555556,
 0.0,
 25.0,
 42.857142857142854,
 14.285714285714285,
 15.384615384615385,
 0.0,
 20.0,
 11.11111111111111,
 14.285714285714285,
 0.3588516746411483,
 30.0,
 22.22222222222222,
 2.7027027027027026,
 42.857142857142854,
 0.0,
 71.42857142857143,
 16.666666666666664,
 20.0,
 12.5,
 16.666666666666664,
 3.9215686274509802,
 9.090909090909092,
 11.11111111111111,
 0.6075334143377886,
 7.6923076923076925,
 20.0,
 16.666666666666664,
 9.523809523809524,
 16.666666666666664,
 0.0,
 25.0,
 0.0,
 11.11111111111111,
 2.4390243902439024,
 50.0,
 11.428571428571429,
 50.0,
 0.0,
 2.5,
 13.513513513513514,
 14.285714285714285,
 40.0,
 6.382978723404255,
 40.0,
 44.44444444444444,
 10.0,
 66.66666666666666,
 66.66666666666666,
 0.0,
 8.333333333333332,
 50.0,
 22.22222222222222,
 3.361344537815126,
 15.0,
 10.0,
 14.285714285714285,
 7.142857142857142,
 12.5,
 25.0,
 28.57142857142857,
 42.857142857142854,
 28.57142857142857,
 4.761904761904762,
 6.666666666666667,
 33.33333333333333,
 33.33333333333333,
 15.0,
 50.0,
 0.0,
 33.33333333333333,
 1.5873015873015872,
 14.285714285714285,
 50.0,
 37.5,
 11.363636363636363,
 28.57142857142857,
 8.333333333333332,
 28.57142857142857,
 11.11111111111111,
 2.1739130434782608,
 11.11111111111111,
 50.0,
 13.333333333333334,
 83.33333333333334,
 37.5,
 3.7037037037037033,
 42.857142857142854,
 25.0,
 62.5,
 8.695652173913043,
 9.090909090909092,
 42.857142857142854,
 1.384083044982699,
 0.0,
 6.666666666666667,
 66.66666666666666,
 9.090909090909092,
 6.25,
 12.5,
 33.33333333333333,
 11.11111111111111,
 12.5,
 23.076923076923077,
 0.0,
 12.5,
 0.0,
 66.66666666666666,
 3.3333333333333335,
 0.0,
 16.666666666666664,
 0.0,
 16.666666666666664,
 12.5,
 6.25,
 7.4074074074074066,
 25.0,
 25.0,
 28.57142857142857,
 14.285714285714285,
 9.090909090909092,
 16.666666666666664,
 33.33333333333333,
 15.0,
 1.8181818181818181,
 7.142857142857142,
 50.0,
 0.24449877750611246,
 50.0,
 16.666666666666664,
 14.285714285714285,
 14.285714285714285,
 14.705882352941178,
 0.0,
 20.0,
 42.857142857142854,
 9.090909090909092,
 10.0,
 14.814814814814813,
 10.526315789473683,
 57.14285714285714,
 0.0,
 50.0,
 13.20754716981132,
 14.285714285714285,
 14.285714285714285,
 14.285714285714285,
 50.0,
 42.857142857142854,
 72.72727272727273,
 33.33333333333333,
 33.33333333333333,
 33.33333333333333,
 16.666666666666664,
 0.0,
 8.333333333333332,
 41.66666666666667,
 25.0,
 8.333333333333332,
 8.333333333333332,
 12.5,
 5.405405405405405,
 57.14285714285714,
 9.090909090909092,
 33.33333333333333,
 12.5,
 4.761904761904762,
 0.0,
 14.285714285714285,
 3.6363636363636362,
 5.0,
 13.333333333333334,
 4.411764705882353,
 0.0,
 42.857142857142854,
 0.684931506849315,
 33.33333333333333,
 15.0,
 11.11111111111111,
 44.44444444444444,
 17.142857142857142,
 11.11111111111111,
 71.42857142857143,
 16.666666666666664,
 0.0,
 0.0,
 1.3089005235602094,
 27.27272727272727,
 9.090909090909092,
 20.0,
 66.66666666666666,
 18.181818181818183,
 14.285714285714285,
 0.0,
 16.666666666666664,
 0.0,
 13.636363636363635,
 0.0,
 33.33333333333333,
 12.903225806451612,
 3.8461538461538463,
 9.67741935483871,
 50.0,
 0.0,
 12.5,
 16.666666666666664,
 1.2345679012345678,
 20.0,
 9.090909090909092,
 33.33333333333333,
 3.1746031746031744,
 7.6923076923076925,
 16.666666666666664,
 16.666666666666664,
 1.6129032258064515,
 85.71428571428571,
 25.0,
 12.5,
 0.0,
 6.666666666666667,
 7.142857142857142,
 36.84210526315789,
 7.5,
 0.0,
 0.0,
 42.857142857142854,
 0.0,
 0.7633587786259541,
 12.5,
 4.545454545454546,
 22.22222222222222,
 2.4390243902439024,
 36.36363636363637,
 27.27272727272727,
 16.666666666666664,
 22.22222222222222,
 30.0,
 2.3952095808383236,
 10.0,
 6.25,
 18.181818181818183,
 8.928571428571429,
 4.166666666666666,
 23.076923076923077,
 15.384615384615385,
 11.76470588235294,
 4.444444444444445,
 37.5,
 20.0,
 23.809523809523807,
 14.285714285714285,
 0.0,
 2.272727272727273,
 33.33333333333333,
 22.22222222222222,
 23.809523809523807,
 12.5,
 50.0,
 22.22222222222222,
 33.33333333333333,
 4.3478260869565215,
 28.57142857142857,
 37.5,
 37.5,
 16.666666666666664,
 28.57142857142857,
 22.22222222222222,
 33.33333333333333,
 7.6923076923076925,
 0.0,
 26.08695652173913,
 57.14285714285714,
 25.0,
 33.33333333333333,
 3.8095238095238098,
 22.22222222222222,
 33.33333333333333,
 6.666666666666667,
 7.6923076923076925,
 21.428571428571427,
 0.0,
 3.125,
 ...]

In [69]:
len(recall_10_list)

1444

In [48]:
import pandas as pd

df = pd.DataFrame({
    "Query_ID": query_ids,
    "recall_5": recall_5_list,
    "precision_5": precision_5_list,
    "AP_5": AP_5_list
})

df

     Query_ID   recall_5  precision_5      AP_5
0      123839  66.666667         80.0  0.500000
1      188629  33.333333         40.0  0.333333
2       13898  33.333333         40.0  0.333333
3      316959  22.222222         40.0  0.222222
4      515031   7.142857         20.0  0.071429
...       ...        ...          ...       ...
1439   896124  12.500000         20.0  0.062500
1440    12319   4.545455         20.0  0.045455
1441     4421   0.000000          0.0  0.000000
1442   296526  10.000000         20.0  0.050000
1443   341793  14.285714         20.0  0.142857

[1444 rows x 4 columns]

In [70]:
import pandas as pd

df_10 = pd.DataFrame({
    "Query_ID": query_ids,
    "recall_10": recall_10_list,
    "precision_10": precision_10_list,
    "AP_10": AP_10_list
})

df_10

     Query_ID   recall_10  precision_10     AP_10
0      123839  100.000000          60.0  0.915079
1      188629   33.333333          20.0  0.333333
2       13898   33.333333          20.0  0.333333
3      316959   22.222222          20.0  0.222222
4      515031   14.285714          20.0  0.095238
...       ...         ...           ...       ...
1439   896124   12.500000          10.0  0.062500
1440    12319    4.545455          10.0  0.045455
1441     4421    0.000000           0.0  0.000000
1442   296526   10.000000          10.0  0.050000
1443   341793   14.285714          10.0  0.142857

[1444 rows x 4 columns]

In [47]:
import numpy as np
print(f"recall 5 mean: {np.mean(recall_5_list)}")
print(f"precision 5 mean: {np.mean(precision_5_list)}")
print(f"MAP 5: {np.mean(AP_5_list)}")

recall 5 mean: 15.759953800074289
precision 5 mean: 32.841643582640806
MAP 5: 0.12214835351980342

In [53]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_5_list = []

for idx in range(len(df)):
    query_id = df.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_5_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_5_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_5_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=5))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_5_list.append(0)

In [71]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_10_list = []

for idx in range(len(df)):
    query_id = df.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_10_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_10_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_10_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=10))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_10_list.append(0)

In [54]:
len(ndcg_5_list)

1444

In [72]:
len(ndcg_10_list)

1444

In [55]:
df["NDCG_5"] = ndcg_5_list
df

     Query_ID   recall_5  precision_5      AP_5    NDCG_5
0      123839  66.666667         80.0  0.500000  0.998041
1      188629  33.333333         40.0  0.333333  0.997851
2       13898  33.333333         40.0  0.333333  0.000000
3      316959  22.222222         40.0  0.222222  0.990788
4      515031   7.142857         20.0  0.071429  0.750615
...       ...        ...          ...       ...       ...
1439   896124  12.500000         20.0  0.062500  0.989962
1440    12319   4.545455         20.0  0.045455  0.894518
1441     4421   0.000000          0.0  0.000000  0.986699
1442   296526  10.000000         20.0  0.050000  0.698425
1443   341793  14.285714         20.0  0.142857  1.000000

[1444 rows x 5 columns]

In [73]:
df_10["NDCG_10"] = ndcg_10_list
df_10

     Query_ID   recall_10  precision_10     AP_10   NDCG_10
0      123839  100.000000          60.0  0.915079  0.995386
1      188629   33.333333          20.0  0.333333  0.998514
2       13898   33.333333          20.0  0.333333  0.000000
3      316959   22.222222          20.0  0.222222  0.988966
4      515031   14.285714          20.0  0.095238  0.784951
...       ...         ...           ...       ...       ...
1439   896124   12.500000          10.0  0.062500  0.990022
1440    12319    4.545455          10.0  0.045455  0.844191
1441     4421    0.000000           0.0  0.000000  0.987909
1442   296526   10.000000          10.0  0.050000  0.717821
1443   341793   14.285714          10.0  0.142857  0.739614

[1444 rows x 5 columns]

In [56]:
df["NDCG_5"].mean()

np.float64(0.8048346515946609)

In [57]:
df["f_score_5"] = 2 * df["recall_5"] * df["precision_5"] / (df["recall_5"] + df["precision_5"])
df

     Query_ID   recall_5  precision_5      AP_5    NDCG_5  f_score_5
0      123839  66.666667         80.0  0.500000  0.998041  72.727273
1      188629  33.333333         40.0  0.333333  0.997851  36.363636
2       13898  33.333333         40.0  0.333333  0.000000  36.363636
3      316959  22.222222         40.0  0.222222  0.990788  28.571429
4      515031   7.142857         20.0  0.071429  0.750615  10.526316
...       ...        ...          ...       ...       ...        ...
1439   896124  12.500000         20.0  0.062500  0.989962  15.384615
1440    12319   4.545455         20.0  0.045455  0.894518   7.407407
1441     4421   0.000000          0.0  0.000000  0.986699        NaN
1442   296526  10.000000         20.0  0.050000  0.698425  13.333333
1443   341793  14.285714         20.0  0.142857  1.000000  16.666667

[1444 rows x 6 columns]

In [74]:
df_10["f_score_10"] = 2 * df_10["recall_10"] * df_10["precision_10"] / (df_10["recall_10"] + df_10["precision_10"])
df_10

     Query_ID   recall_10  precision_10     AP_10   NDCG_10  f_score_10
0      123839  100.000000          60.0  0.915079  0.995386   75.000000
1      188629   33.333333          20.0  0.333333  0.998514   25.000000
2       13898   33.333333          20.0  0.333333  0.000000   25.000000
3      316959   22.222222          20.0  0.222222  0.988966   21.052632
4      515031   14.285714          20.0  0.095238  0.784951   16.666667
...       ...         ...           ...       ...       ...         ...
1439   896124   12.500000          10.0  0.062500  0.990022   11.111111
1440    12319    4.545455          10.0  0.045455  0.844191    6.250000
1441     4421    0.000000           0.0  0.000000  0.987909         NaN
1442   296526   10.000000          10.0  0.050000  0.717821   10.000000
1443   341793   14.285714          10.0  0.142857  0.739614   11.764706

[1444 rows x 6 columns]

In [59]:
df["f_score_5"] = df["f_score_5"].fillna(0)
df.isna().sum()

Query_ID       0
recall_5       0
precision_5    0
AP_5           0
NDCG_5         0
f_score_5      0
dtype: int64

In [75]:
df_10["f_score_10"] = df_10["f_score_10"].fillna(0)
df_10.isna().sum()

Query_ID        0
recall_10       0
precision_10    0
AP_10           0
NDCG_10         0
f_score_10      0
dtype: int64

In [60]:
df

     Query_ID   recall_5  precision_5      AP_5    NDCG_5  f_score_5
0      123839  66.666667         80.0  0.500000  0.998041  72.727273
1      188629  33.333333         40.0  0.333333  0.997851  36.363636
2       13898  33.333333         40.0  0.333333  0.000000  36.363636
3      316959  22.222222         40.0  0.222222  0.990788  28.571429
4      515031   7.142857         20.0  0.071429  0.750615  10.526316
...       ...        ...          ...       ...       ...        ...
1439   896124  12.500000         20.0  0.062500  0.989962  15.384615
1440    12319   4.545455         20.0  0.045455  0.894518   7.407407
1441     4421   0.000000          0.0  0.000000  0.986699   0.000000
1442   296526  10.000000         20.0  0.050000  0.698425  13.333333
1443   341793  14.285714         20.0  0.142857  1.000000  16.666667

[1444 rows x 6 columns]

In [62]:
mydict = {
    "Method": "BM25 - Lemmatization Cross Encoder",
    "recall_5_mean": df["recall_5"].mean(),
    "recall_5_std": df["recall_5"].std(),
    "recall_5_max": df["recall_5"].max(),
    "recall_5_min": df["recall_5"].min(),
    "precision_5_mean": df["precision_5"].mean(),
    "precision_5_std": df["precision_5"].std(),
    "precision_5_max": df["precision_5"].max(),
    "precision_5_min": df["precision_5"].min(),
    "f_score_5_mean": df["f_score_5"].mean(),
    "f_score_5_std": df["f_score_5"].std(),
    "f_score_5_max": df["f_score_5"].max(),
    "f_score_5_min": df["f_score_5"].min(),
    "MAP_5": df["AP_5"].mean(),
    "NDCG_5_mean": df["NDCG_5"].mean(),
    "NDCG_5_std": df["NDCG_5"].std(),
    "NDCG_5_max": df["NDCG_5"].max(),
    "NDCG_5_min": df["NDCG_5"].min(),
}

In [77]:
mydict = {
    "Method": "BM25 - Lemmatization Cross Encoder",
    "recall_10_mean": df_10["recall_10"].mean(),
    "recall_10_std": df_10["recall_10"].std(),
    "recall_10_max": df_10["recall_10"].max(),
    "recall_10_min": df_10["recall_10"].min(),
    "precision_10_mean": df_10["precision_10"].mean(),
    "precision_10_std": df_10["precision_10"].std(),
    "precision_10_max": df_10["precision_10"].max(),
    "precision_10_min": df_10["precision_10"].min(),
    "f_score_10_mean": df_10["f_score_10"].mean(),
    "f_score_10_std": df_10["f_score_10"].std(),
    "f_score_10_max": df_10["f_score_10"].max(),
    "f_score_10_min": df_10["f_score_10"].min(),
    "MAP_10": df_10["AP_10"].mean(),
    "NDCG_10_mean": df_10["NDCG_10"].mean(),
    "NDCG_10_std": df_10["NDCG_10"].std(),
    "NDCG_10_max": df_10["NDCG_10"].max(),
    "NDCG_10_min": df_10["NDCG_10"].min(),
}

In [63]:
df_parquet = pd.DataFrame(mydict, index=[0])
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,precision_5_mean,precision_5_std,precision_5_max,precision_5_min,f_score_5_mean,f_score_5_std,f_score_5_max,f_score_5_min,MAP_5,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min
0,BM25 - Lemmatization Cross Encoder,15.759954,14.439942,83.333333,0.0,32.841644,23.152133,100.0,0.0,19.776504,16.665978,90.909091,0.0,0.122148,0.804835,0.327528,1.0,0.0

In [78]:
df_parquet_10 = pd.DataFrame(mydict, index=[0])
df_parquet_10

,Method,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_10_mean,precision_10_std,precision_10_max,precision_10_min,f_score_10_mean,f_score_10_std,f_score_10_max,f_score_10_min,MAP_10,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25 - Lemmatization Cross Encoder,20.86522,19.584312,100.0,0.0,22.903311,17.788971,100.0,0.0,19.673399,16.680059,100.0,0.0,0.153571,0.811885,0.291716,1.0,0.0

In [64]:
df_parquet.to_parquet("BM25LemmatizationCrossEncoder.parquet")

In [3]:
mydict_final = {
    "Method": "BM25 - Lemmatization Cross Encoder",
    "recall_5_mean": 15.759954,
    "recall_5_std": 14.439942,
    "recall_5_max": 83.333333,
    "recall_5_min": 0.0,
    "precision_5_mean": 32.841644,
    "precision_5_std": 23.152133,
    "precision_5_max": 100.0,
    "precision_5_min": 0.0,
    "f_score_5_mean": 19.776504,
    "f_score_5_std": 16.665978,
    "f_score_5_max": 90.909091,
    "f_score_5_min": 0.0,
    "MAP_5": 0.122148,
    "NDCG_5_mean": 0.804835,
    "NDCG_5_std": 0.327528,
    "NDCG_5_max": 1.0,
    "NDCG_5_min": 0.0,
    "recall_10_mean": 20.86522,
    "recall_10_std": 19.584312,
    "recall_10_max": 100.0,
    "recall_10_min": 0.0,
    "precision_10_mean": 22.903311,
    "precision_10_std": 17.788971,
    "precision_10_max": 100.0,
    "precision_10_min": 0.0,
    "f_score_10_mean": 19.673399,
    "f_score_10_std": 16.680059,
    "f_score_10_max": 100.0,
    "f_score_10_min": 0.0,
    "MAP_10": 0.153571,
    "NDCG_10_mean": 0.811885,
    "NDCG_10_std": 0.291716,
    "NDCG_10_max": 1.0,
    "NDCG_10_min": 0.0
}

In [4]:
import pandas as pd
df_final = pd.DataFrame(mydict_final, index=[0])
df_final

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,precision_5_mean,precision_5_std,precision_5_max,precision_5_min,f_score_5_mean,...,precision_10_min,f_score_10_mean,f_score_10_std,f_score_10_max,f_score_10_min,MAP_10,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25 - Lemmatization Cross Encoder,15.759954,14.439942,83.333333,0.0,32.841644,23.152133,100.0,0.0,19.776504,...,0.0,19.673399,16.680059,100.0,0.0,0.153571,0.811885,0.291716,1.0,0.0

In [5]:
df_final.to_parquet("BM25LemmatizationCrossEncoder.parquet")